### ISSUE TITLE
QAT_Engine/.tools/configure: No such file or directory

### ISSUE THREAD

**Issue by onioner** [intel/QAT_Engine#101]
Hello Team,
When I bulid the QAT_Engine, an error occurred while running the autogen.sh : 
 
autoreconf: Entering directory ‘.' 
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/autoconf2.68/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
./autogen.sh: line 16: /usr/local/openssl-1.1.0i/QAT_Engine/.tools/configure: No such file or directory
chmod: cannot access ’../configure': No such file or directory

yes, there is no file named configure in QAT_Engine/.tools/
What should I do? 

OS: CentOS 6.8
kernel: 2.6.32-642.el6.x86_64
QAT_Engine version: v0.5.39

Because the default version of autoconf is 2.63,  I installed a 2.68 version of the autoconf. 

Thanks in advance!

**Comment by Yogaraj-Alamenda** [comment]
Hi @onioner ,
                     The problem you mentioned is due to autoreconf failure in the autogen.sh which I suspect is because automake not available in your system .
        As per README.md, "The prerequisite to run autogen.sh is to have autotools (autoconf, automake and libtool) installed in the system".
Could you please install the above said tools in your system and try running ./autogen.sh. 
Upon successful execution of autogen.sh, necessary automake files (eg:configure ) will get generated and then follow the build section link below in the README.md to proceed further.
https://github.com/intel/QAT_Engine/blob/master/README.md#build-the-intel-quickassist-technology-openssl-engine
