### ISSUE TITLE
intel QAT icp_adf_userProcessToStart: Error reading /dev/qat_dev_processes file

### ISSUE THREAD

**Issue by ben-feng** [intel/QAT_Engine#108]
software info
Operating system: CentOS Linux release 7.5.1804 (Core)
Kernel: GNU*/Linux* 4.14.69
openssl : 1.1.1
qat_driver : qat1.7.l.4.5.0-00034
qat_engine : master branch, latest

qat_service looks ok
ops]# service qat_service status
Checking status of all devices.
There is 1 QAT acceleration device(s) in the system:
 qat_dev0 - type: dh895xcc,  inst_id: 0,  node_id: 0,  bsf: 0000:06:00.0,  #accel: 6 #engines: 12 state: up

lsmod | grep usdm_drv
usdm_drv               94208  0
intel_qat             270336  2 usdm_drv,qat_dh895xcc

apps]# ./openssl engine -t -c -vvvv qat
(qat) Reference implementation of QAT crypto engine
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF]
     ADF_UIO_PROXY err: icp_adf_userProcessToStart: Error reading /dev/qat_dev_processes file
[ unavailable ]
     ENABLE_EXTERNAL_POLLING: Enables the external polling interface to the engine.
          (input flags): NO_INPUT
     POLL: Polls the engine for any completed requests
          (input flags): NO_INPUT
     SET_INSTANCE_FOR_THREAD: Set instance to be used by this thread
          (input flags): NUMERIC
     GET_NUM_OP_RETRIES: Get number of retries
          (input flags): NO_INPUT
     SET_MAX_RETRY_COUNT: Set maximum retry count
          (input flags): NUMERIC
     SET_INTERNAL_POLL_INTERVAL: Set internal polling interval
          (input flags): NUMERIC
     GET_EXTERNAL_POLLING_FD: Returns non blocking fd for crypto engine
          (input flags): NO_INPUT
     ENABLE_EVENT_DRIVEN_POLLING_MODE: Set event driven polling mode
          (input flags): NO_INPUT
     GET_NUM_CRYPTO_INSTANCES: Get the number of crypto instances
          (input flags): NO_INPUT
     DISABLE_EVENT_DRIVEN_POLLING_MODE: Unset event driven polling mode
          (input flags): NO_INPUT
     SET_EPOLL_TIMEOUT: Set epoll_wait timeout
          (input flags): NUMERIC
     SET_CRYPTO_SMALL_PACKET_OFFLOAD_THRESHOLD: Set QAT small packet threshold
          (input flags): STRING
     ENABLE_INLINE_POLLING: Enables the inline polling mode.
          (input flags): NO_INPUT
     ENABLE_HEURISTIC_POLLING: Enable the heuristic polling mode
          (input flags): NO_INPUT
     GET_NUM_REQUESTS_IN_FLIGHT: Get the number of in-flight requests
          (input flags): NUMERIC
     INIT_ENGINE: Initializes the engine if not already initialized
          (input flags): NO_INPUT

Troubleshooting list check is ok

**Comment by paulturx** [comment]
Hi Ben
It's difficult to pin-point the exact problem here.  Could you uninstall the QAT driver and then add/modify a/the 'blacklist.conf' file in folder  /etc/modprobe.d , adding the following lines:-
blacklist qat_dh895xcc
blacklist qat_dh895xccvf
blacklist qat_c62x
blacklist qat_c62xvf
blacklist qat_c6xx
blacklist qat_c6xxvf
blacklist qat_c3xxx
blacklist qat_c3xxxvf
blacklist qat_d15xx
blacklist qat_d15xxvf
blacklist qat_c4xxx
blacklist qat_c4xxxvf
blacklist intel_qat 

Then reboot your board  and re-install the QAT driver code to see if this solves the issue..

Also could you forward the configure commands you used in the build processes for QAT driver, OpenSSL & QAT Engine, together with the ENV variables you have set.
Thanks,
    Paul Turner

**Comment by ben-feng** [comment]
ok, I will try it

**Comment by paulturx** [comment]
Hi Ben
At this stage I don't think it is necessary to rebuild the openssl & qat engine.  It should suffice to make the blacklisting changes,  uninstall the QAT driver and reboot using for example 'shutdown -r now'.  Then rebuild & reinstall the QAT driver once the board is back up.  Note that this QAT driver re-install will reinstall its own driver conf files back again in /etc, so the crypto conf files mentioned below will need to be copied over again.

By the way I have never run your 'echo /usr/local/ssl/lib > /etc/ld.so.conf.d/qat.conf' command.  Is it somewhere in the documentation?
You are using the upstream driver therefore you should be selecting a config files from isg_cid-qat_engine/qat/config/dh895xcc_upstream NOT qat/config/dh895xcc.
I suggest just selecting isg_cid-qat_engine/qat/config/dh895xcc_upstream/multi_process_optimized/dh895xcc_dev0.conf in the first instance while we are sorting out this problem.

Regards,
    Paul Turner

**Comment by paulturx** [comment]
You will need to run '/etc/init.d/qat_service restart' once you have copied over the conf file for the new conf file to be read.

**Comment by ben-feng** [comment]
@paulturx

**Comment by ben-feng** [comment]
hi paulturx
I install asynch_mode_nginx， use wrk to performance test，the result not as good as expected
, and cpu usage rate has not dropped。 I check /sys/kernel/debug/qat_device_id/fw_counters it looks ok.
cat /sys/kernel/debug/qat_dh895xcc_0000\:06\:00.0/fw_counters
+------------------------------------------------+
| FW Statistics for Qat Device                   |
+------------------------------------------------+
| Firmware Requests [AE  0]:              363227 |
| Firmware Responses[AE  0]:              363227 |
+------------------------------------------------+
| Firmware Requests [AE  1]:              352851 |
| Firmware Responses[AE  1]:              352851 |
+------------------------------------------------+
| Firmware Requests [AE  2]:              348281 |
| Firmware Responses[AE  2]:              348281 |
+------------------------------------------------+
| Firmware Requests [AE  3]:              349242 |
| Firmware Responses[AE  3]:              349242 |
+------------------------------------------------+
| Firmware Requests [AE  4]:              348508 |
| Firmware Responses[AE  4]:              348508 |
+------------------------------------------------+
| Firmware Requests [AE  5]:              352792 |
| Firmware Responses[AE  5]:              352792 |
+------------------------------------------------+
| Firmware Requests [AE  6]:              348304 |
| Firmware Responses[AE  6]:              348304 |
+------------------------------------------------+
| Firmware Requests [AE  7]:              351721 |
| Firmware Responses[AE  7]:              351721 |
+------------------------------------------------+
| Firmware Requests [AE  8]:              362864 |
| Firmware Responses[AE  8]:              362864 |
+------------------------------------------------+
| Firmware Requests [AE  9]:              363580 |
| Firmware Responses[AE  9]:              363580 |
+------------------------------------------------+
| Firmware Requests [AE 10]:              352055 |
| Firmware Responses[AE 10]:              352055 |
+------------------------------------------------+
| Firmware Requests [AE 11]:              362788 |
| Firmware Responses[AE 11]:              362788 |
+------------------------------------------------+

the result of qps has not improved
use software cpu:
Running 1m test @ https://127.0.0.1:443/
  32 threads and 3200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.62ms    2.17ms 383.51ms   96.69%
    Req/Sec   727.82    281.25     1.97k    66.82%
  Latency Distribution
     50%    1.33ms
     75%    1.97ms
     90%    2.79ms
     99%    5.09ms
  1387361 requests in 1.00m, 1.09GB read
Requests/sec:  23086.76
Transfer/sec:     18.60MB

use asynch 
Running 1m test @ https://127.0.0.1:443/
  32 threads and 3200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.19ms    1.91ms  90.71ms   93.98%
    Req/Sec   744.18    259.75     2.16k    68.05%
  Latency Distribution
     50%    1.88ms
     75%    2.61ms
     90%    3.53ms
     99%    7.63ms
  1416259 requests in 1.00m, 1.11GB read
  Socket errors: connect 57, read 0, write 0, timeout 0
  Non-2xx or 3xx responses: 6
Requests/sec:  23568.52

the nginx.conf like this
worker_processes  8;
user root;
load_module modules/ngx_ssl_engine_qat_module.so;
events {
    use epoll;
    worker_connections  100000;
    accept_mutex_delay  10ms;
}

ssl_engine {
    use_engine qat;
    default_algorithms ALL;

    qat_engine {
        qat_offload_mode async;
        qat_notify_mode poll;
        qat_poll_mode heuristic;
    }
}

http {
    ....
    server {
        server_name www.test.com;
        ssl_asynch on;
        listen 443 ssl;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:50m;
        ssl_session_timeout 50m;

        ssl_certificate /usr/local/nginx/cert/www.test.com.crt;
        ssl_certificate_key /usr/local/nginx/cert/www.test.com.key;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}

Any comment/suggestion?

**Comment by paulturx** [comment]
Hi Ben
If you are using usdm then you do not install qat_config_mem.
I do not have usdm vs qat_config_mem performance figures readily available unfortunately.   I'll see if I can get some for you.   I'm glad your system is now running.
Regards,
    Paul

**Comment by pmiloslavsky** [comment]
I have the same issue. I cant use the openssl utility with qatengine unless I am root. 


coloperf3 Linux-x86_64 qat$ sudo rm /etc/modprobe.d/blacklist.conf
coloperf3 Linux-x86_64 qat$ sudo service qat_service stop
Stopping all devices.
coloperf3 Linux-x86_64 qat$ sudo service qat_service start
Restarting all devices.
Processing /etc/c6xx_dev0.conf
Processing /etc/c6xx_dev1.conf
Processing /etc/c6xx_dev2.conf
Checking status of all devices.
There is 3 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 1,  bsf: 0000:8a:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 1,  bsf: 0000:8b:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 1,  bsf: 0000:8c:00.0,  #accel: 5 #engines: 10 state: up
coloperf3 Linux-x86_64 qat$ lsmod | grep qat
qat_c62x               18061  0 
intel_qat             249414  2 usdm_drv,qat_c62x
uio                    19338  1 intel_qat
coloperf3 Linux-x86_64 qat$ /usr/local/ssl/bin/openssl speed -engine qatengine -elapsed rsa2048
ADF_UIO_PROXY err: icp_adf_userProcessToStart: Cannot open /dev/qat_dev_processes file
can't use that engine
140264581109568:error:800A50AB:lib(128):qat_init:icp sal userstart fail:qat_hw_init.c:383:
140264581109568:error:260B806D:engine routines:engine_table_register:init failed:crypto/engine/eng_table.c:130:
You have chosen to measure elapsed time instead of user CPU time.
Doing 2048 bits private rsa's for 10s: ^C
coloperf3 Linux-x86_64 qat$ sudo /usr/local/ssl/bin/openssl speed -engine qatengine -elapsed rsa2048
engine "qatengine" set.

**Comment by pmiloslavsky** [comment]
@paulturx maybe you have suggestions?

**Comment by Yogaraj-Alamenda** [comment]
@pmiloslavsky Could you please check **section 3.14 Running Applications as Non-Root User** in programmers guide -[336210_QAT_SW_PG.book (01.org)](https://01.org/sites/default/files/downloads/336210-017-intel-qat-programmers-guide-v1.7.pdf) and see if the steps mentioned solves the issue you are seeing

**Comment by pmiloslavsky** [comment]
@Yogaraj-Alamenda Thank you, that works

**Comment by pmiloslavsky** [comment]
@Yogaraj-Alamenda I think another root cause is the driver.conf files can come from 2 places: either the qat driver package or the QAT_Engine package.  If you use the QAT_engine ones the qat driver sample code doesnt work but ssl does. Something about SHIM section maybe.

**Comment by Yogaraj-Alamenda** [comment]
@pmiloslavsky  You should be using driver config files from QAT Engine  qat/config as described in [Installation Instructions](https://github.com/intel/QAT_Engine#installation-instructions) - Copy the Intel® QuickAssist Technology Driver config file(s) as the QAT Engine expects the SHIM section in config file.

**Comment by jimthedj65** [comment]
I can confirm that the latest driver install will over write the /etc/c6xx_dev0.conf files and the QAT_Engine version under lqat_hw_config for the appropriate device will work other wise the error [error] ADF_UIO_PROXY: icp_adf_userProcessToStart: Error reading /dev/qat_dev_processes file will appear.

**Comment by SercanKaraoglu** [comment]
For me, the configuration files located in the /etc/ directory with the naming convention 4xxx_dev0.conf had a section titled 
[SSL]. I modified these sections to [SHIM], and subsequently, my error log changed to the following entries:
```
[error] SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time
[error] do_userStart() - : Failed to start services
```

Additionally, I observed the following log entries in the /var/log/messages file:
```
kernel: 4xxx 0000:f7:00.0: FW version: 1.0.50
kernel: 4xxx 0000:f7:00.0: Cannot use PF with IOMMU enabled
```

Ultimately, disabling the IOMMU (Input/Output Memory Management Unit) resolved all the aforementioned errors. However, I am curious to know if there exists a more appropriate or recommended solution to address this issue.
