### ISSUE TITLE
intel QAT  SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time

### ISSUE THREAD

**Issue by ben-feng** [intel/QAT_Engine#109]
build software is ok, but run openssl test, error occurring
Error Info ：
apps]# ./openssl engine -t -c -vvvv qat
(qat) Reference implementation of QAT crypto engine
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF]
[error] SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time

[error] do_userStart() - : Failed to start services

     [ unavailable ]
     ENABLE_EXTERNAL_POLLING: Enables the external polling interface to the engine.
          (input flags): NO_INPUT
     POLL: Polls the engine for any completed requests
          (input flags): NO_INPUT
     SET_INSTANCE_FOR_THREAD: Set instance to be used by this thread
          (input flags): NUMERIC
     GET_NUM_OP_RETRIES: Get number of retries
          (input flags): NO_INPUT
     SET_MAX_RETRY_COUNT: Set maximum retry count
          (input flags): NUMERIC
     SET_INTERNAL_POLL_INTERVAL: Set internal polling interval
          (input flags): NUMERIC
     GET_EXTERNAL_POLLING_FD: Returns non blocking fd for crypto engine
          (input flags): NO_INPUT
     ENABLE_EVENT_DRIVEN_POLLING_MODE: Set event driven polling mode

Software Info
Kernel: GNU*/Linux* 4.19.12
openssl : 1.1.1
qat_driver : qat1.7.l.4.5.0-00034
qat_engine : master branch, latest

configure commands list
1.QAT_driver
cd /tmp/qat/qat-driver
./configure
make
make install

2.openssl
cd /tmp/qat/openssl
./config --prefix=/usr/local/ssl -Wl,-rpath=/usr/local/ssl/lib
make depend
make
make install
export OPENSSL_ENGINES=/usr/local/ssl/lib/engines-1.1

3.QAT_ENGINE
cd /tmp/qat/qat-engine
./autogen.sh
./configure --with-qat_dir=../qat-driver
--with-openssl_dir=../openssl
--with-openssl_install_dir=/usr/local/ssl
--enable-upstream_driver 
--enable-usdm
make
make install

cp /tmp/qat/qat-engine/qat/config/c6xx/multi_process_optimized/* /etc/

# lsmod | grep qat
qat_c62x               20480  0
intel_qat             266240  2 qat_c62x,usdm_drv
dh_generic             16384  1 intel_qat
uio                    20480  1 intel_qat
authenc                16384  1 intel_qat

**Comment by ben-feng** [comment]
I find some suggest in 336211qatrelnotespublicrev001.pdf, but not resolve my question
link : https://01.org/sites/default/files/downloads/intelr-quickassist-technology/336211qatrelnotespublicrev001.pdf

QATE-3978 - GEN - The QuickAssist service must be restarted after a reboot -
I add  /etc/modprobe.d/qat.conf and adding the following lines:-
blacklist qat_dh895xcc
blacklist qat_dh895xccvf
blacklist qat_c62x
blacklist qat_c62xvf
blacklist qat_c6xx
blacklist qat_c6xxvf
blacklist qat_c3xxx
blacklist qat_c3xxxvf
blacklist qat_d15xx
blacklist qat_d15xxvf
blacklist qat_c4xxx
blacklist qat_c4xxxvf
blacklist intel_qat

next,  I reboot board and re-install the QAT driver， but question also exist

QATE-3693 - SRIOV - Incorrect config file for PFs when VFs are enabled in the host - 
Reference # QATE-3693
but This is resolved with the 0.8.1 release.

**Comment by paulturx** [comment]
Hi Ben
Again, it's difficult to determine the problem remotely but here are a few things that might help:-

- I suggest uninstalling the QAT driver and then rebooting your board.

- When the board is back up and before you re-install the QAT driver, run 'lsmod|grep qat' to check that the blacklisting worked and there are no modules loaded from the kernel.

- You seem to have all your code (QAT driver, QAT Engine, etc) installed in the /tmp directory.  This is not a good idea. I assume you have root privileges so I suggest putting all the source code in a subdirectory of the /root directory.  Doing this you should recompile all the code after you have re-installed the driver.  

- Please send me a copy of the environment variables you have set, the QAT driver config files you are using.

- In you last issue #108 it looks like you are using Coleto, but in this issue number you are copying over c6xx config files.  Please state what type of hardware you are using?  Remember you need to reload the config files after copying them to /etc for them to take effect.

Regards,
    Paul

**Comment by ben-feng** [comment]
hi paulturx 

According your suggest

1. I uninstall qat-driver, openssl and qat-engine,
2. I reboot 
3. run 'lsmod | grep qat', the res is null
4. I exec modprobe qat_c62x, 
lsmod | grep qat
qat_c62x               16384  0
intel_qat             155648  1 qat_c62x
dh_generic             16384  1 intel_qat
authenc                16384  1 intel_qat

5. re-install qat-driver, openssl qat-engine (code installed /root)

run './openssl engine -t -c -vvvv qat', question also exist

environment variables set:
export OPENSSL_ENGINES=/usr/local/ssl/lib/engines-1.1
export PERL5LIB=/root/qat/openssl

QAT driver config:
copy from 'qat/config/c6xx/multi_process_optimized/*'

hardware type :
lspci |fgrep Co-processor
63:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
64:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
65:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)

**Comment by paulturx** [comment]
Hi Ben
The installation of the qat kernel modules is done as part of the QAT driver installation process.  You do not need/must not carry out line 4 of your process above.  I suggest you uninstall the QAT driver and reboot the board and start over.  Out of interest, is there anything in the documentation which says to carry out line 4?
Kind regards,
    Paul

**Comment by paulturx** [comment]
Hi Ben
Also could you send a list of all your environment variables ('env') as you only say above that you have set just 2.

Thanks in advance, Paul

**Comment by ben-feng** [comment]
Hi paulturx
I remove line 4,  uninstall QAT driver,  reboot my board,  re-install QAT driver,  the result not change
err is also 'SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time'

Install QAT driver, openssl and QAT Engine, I' m only set 2 environment variables

The list of all enviroument variables:
# env
XDG_SESSION_ID=1752
SHELL=/bin/bash
TERM=xterm-256color
HISTSIZE=1000
PERL5LIB=/root/qat/openssl
OPENSSL_ENGINES=/usr/local/ssl/lib/engines-1.1
USER=root
LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
SUDO_USER=ops
SUDO_UID=201
USERNAME=root
PATH=/usr/local/java8/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
MAIL=/var/spool/mail/ops
PWD=/home/ops
JAVA_HOME=/usr/local/java8
LANG=zh_CN.UTF-8
SHLVL=1
SUDO_COMMAND=/bin/bash
HOME=/root
LOGNAME=root
LESSOPEN=||/usr/bin/lesspipe.sh %s
PROMPT_COMMAND={ msg=$(history 1 | { read x y; echo $y; }); user=$(whoami); logger -p local4.err $(date "+%Y-%m-%d %H:%M:%S") "$user" "$msg"; }
SUDO_GID=201
HISTTIMEFORMAT=%F %T
_=/bin/env

**Comment by paulturx** [comment]
Hi Ben
You do not appear to be setting ICP_ROOT as the path to the QAT driver source top directory?
~P

**Comment by paulturx** [comment]
Hi Ben
My colleague has noticed that you don't have with_qat_install_dir set in the QAT Engine configure command.  Perhaps you could  run the command:-
ldd $OPENSSL_ENGINES/qat.so
and post the results.
My previous comment can be ignored as this env variable is not mentioned in the guide https://01.org/sites/default/files/downloads//336212-005qatswgettingstarted.pdf in the installation section, so apologies for that. It is quite useful to set this as an env variable however but is not essential.

regards, Paul

**Comment by ben-feng** [comment]
Hi paulturx

Results of run 'ldd $OPENSSL_ENGINES/qat.so'
# ldd $OPENSSL_ENGINES/qat.so
	linux-vdso.so.1 =>  (0x00007ffc1a5b1000)
	libqat_s.so => /usr/local/lib/libqat_s.so (0x00007f9dea81e000)
	libusdm_drv_s.so => /usr/local/lib/libusdm_drv_s.so (0x00007f9dea606000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9dea239000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9dea01d000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f9de9e07000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9dead28000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f9de9bff000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f9de99fa000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9de96f8000)
	libdw.so.1 => /lib64/libdw.so.1 (0x00007f9de94a9000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9de92a5000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9de908f000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007f9de8e8a000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007f9de8c72000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9de8a5c000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f9de8836000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f9de8626000)

**Comment by paulturx** [comment]
Hi Ben 
So this is an 'ldd' of the qat.so at /usr/local/ssl/lib/engines-1.1.  You say you have moved the QAT driver source code to /root/qat/qat-driver.  Unless you have set the env variable ICP_BUILD_OUTPUT to /usr/local/lib, which according to your 'env' dump you have not, then by default when building the QAT driver the build output would be put in /root/qat/qat-driver/build, so, for example, on one of my boards where the QAT driver is at root/QAT1.7.L.4.5.0-00034/ then if I run ldd $OPENSSL_ENGINES/qat.so' I get the following output:-

ldd /root/paulturx/install/opensslfor_1_1_1a/lib/engines-1.1/qat.so
        linux-vdso.so.1 (0x00007ffeafbc2000)
        libqat_s.so => /root/QAT1.7.L.4.5.0-00034/build/libqat_s.so (0x00007efdeaded000)
        libusdm_drv_s.so => /root/QAT1.7.L.4.5.0-00034/build/libusdm_drv_s.so (0x00007efdeabd4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007efdea7fe000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efdea5e0000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00007efdea5be000)
        /lib64/ld-linux-x86-64.so.2 (0x0000560541e83000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007efdea39b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007efdea197000)
        librt.so.1 => /lib64/librt.so.1 (0x00007efde9f8e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007efde9c8c000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007efde9a71000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00007efde9826000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007efde9621000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007efde940a000)
        libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x00007efde91ed000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007efde8fd5000)
        libz.so.1 => /lib64/libz.so.1 (0x00007efde8dbe000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007efde8b98000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007efde8988000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007efde8782000)

Notice the library libqat_s.so => /root/QAT1.7.L.4.5.0-00034/build/libqat_s.so

The equivalent for your set-up should be :-
libqat_s.so => /root/qat/qat-driver/build/libqat_s.so 

I suggest, since you say that you install the QAT driver with:-
cd /root/qat/qat-driver
./configure
make
make install

then, without ICP_BUILD_OUTPUT set, the build output should be sent to directory /root/qat/qat-driver/build.

Please could you confirm that after the QAT driver build & installation procedure this file exists at least on your board:-
/root/qat/qat-driver/build/libqat_s.so
and the time of the file creation matches the installation time.

I'm expecting that your QAT engine build process is as follows now:-

3.QAT_ENGINE
cd /root/qat/qat-engine
./autogen.sh
./configure --with-qat_dir=/root/qat/qat-driver
--with-openssl_dir=/root/qat/openssl
--with-openssl_install_dir=/usr/local/ssl
--enable-upstream_driver
--enable-usdm
make
make install

Please note that I have changed the paths to be absolute rather than relative.  If this is not what you are running please let me know where it differs.

Regards,
    Paul Turner

**Comment by ben-feng** [comment]
Hi paulturx
I confirm that after the QAT driver build & installation,  /root/qat/qat-driver/build/libqat_s.so create and the time of the file creation matches the installation time

I build QAT_Engine as absulute path,  the result as same as history

I notice this follow lines when make install qat-driver:
Creating startup and kill scripts
Copying libqat_s.so to /usr/local/lib
Copying libusdm_drv_s.so to /usr/local/lib
Copying usdm module to system drivers

so ldd /usr/local/ssl/lib/engines-1.1/qat.so
libqat_s.so => /usr/local/lib/libqat_s.so (0x00007f9dea81e000)
this looks ok

I Notice on other machines， hardware type is Intel Corporation DH895XCC Series QAT
QAT_Engine is runs ok,  exec 'll /dev/uio*' ,  follow lines appear
crw-rw---- 1 root root 240,  0 6月   6 17:00 /dev/uio0
crw-rw---- 1 root root 240,  1 6月   6 17:00 /dev/uio1
crw-rw---- 1 root root 240,  0 6月   6 17:00 /dev/uio3
crw-rw---- 1 root root 240,  1 6月   6 17:00 /dev/uio4
...

but in this machines, exec 'll /dev/uio*'    the result is dir or file not found 

I hope this information will help you.

**Comment by paulturx** [comment]
Hi Ben
Thanks for the information.  Looking at the QAT driver Makefile regarding the copying of the .so files, I'm guessing you should have a /etc/ld.so.conf.d/qat.conf file in which is the string '/usr/local/lib'.

You confirm that after the QAT driver build & installation, /root/qat/qat-driver/build/libqat_s.so was created and the time of the file creation matches the installation time.  Could you please confirm whether the files in /root/qat/qat-driver/build/libqat_s.so and /usr/local/lib/libqat_s.so are indeed identical, i.e., they are copies?

If not, I can only suggest that we use the optional QAT Engine build configuration listed from the README.md:-

Optional

--with-qat_install_dir=/path/to/qat_driver/build
    Specify the path to the location of the built Intel(R) QAT Driver library
    files. This path is needed in order to link to the userspace libraries of
    the Intel(R) QAT Driver.
    The default if not specified is to use the path specified by --with-qat_dir
    with '/build' appended.  You only need to specify this parameter if the
    driver library files have been built somewhere other than the default.

Regards,
    Paul

**Comment by ben-feng** [comment]
Hi paulturx
Ths you reply.
In my machine， the files in /root/qat/qat-driver/build/libqat_s.so and /usr/local/lib/libqat_s.so are  not 
indeed identical,  they are copies.

The problem is solved， I find some message in /var/log/messages
 kernel: [46526.320033] c6xx 0000:65:00.0: qat_dev2 started 10 acceleration engines
 kernel: [46526.341091] c6xx 0000:65:00.0: Cannot use PF with IOMMU enabled
 
I closed iommu option and reboot,  the question is ok. 
Although I don't know the specific reason

Recently, I am testing different types of accelerator cards. Is there a baseline performance data reference?

**Comment by paulturx** [comment]
Hi Ben
Glad to hear your problem has been resolved.  If you look in https://01.org/sites/default/files/downloads//336212-005qatswgettingstarted.pdf section 2.4 there is an overview of this issue.  
Regarding performance there is some discussion of performance here:- https://01.org/sites/default/files/downloads/intelr-quickassist-technology/337003-001-intelquickassisttechnologyandopenssl-110.pdf .  I suggest you contact the Intel customer QuickAssist Technology support team if you have further queries on performance.

Regards,
    Paul
