### ISSUE TITLE
./openssl speed -engine qat -elapsed rsa2048 failed by non-root user 

### ISSUE THREAD

**Issue by lcmmhcc** [intel/QAT_Engine#111]
hello,
im trying to run engine by non-root user.
Everything is ok by root user, but failed  by non-root user
part of the "strace ./openssl speed -engine qat -elapsed rsa2048" as below:

open("/dev/qat_mem", O_RDWR)            = 8
ioctl(8, 0xc0209500, 0x7fff656e4d90)    = 0
mmap(NULL, 131040, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_LOCKED, 8, 0xffff882783b80000) = -1 EAGAIN (Resource temporarily unavailable)
write(2, "mmap: 11 Resource temporarily un"..., 76mmap: 11 Resource temporarily unavailable: Resource temporarily unavailable
) = 76
write(2, "crypto_alloc_from_slab error, cr"..., 75crypto_alloc_from_slab error, create_slab failed - memory allocation error
) = 75
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
Segmentation fault

I have followed the steps of the documents 
3.14 Running Applications as Non-Root User
https://01.org/sites/default/files/downloads/intelr-quickassist-technology/336210qatswprogguiderev001review.pdf 

groupadd ssl_work
usermod -G ssl_work work
chgrp ssl_work /dev/qat_*
chgrp ssl_work /dev/icp_*

as the work user have the write access, as below:
[work@tc-op bin]$ ll /dev/qat_mem
crw-rw---- 1 root ssl_work 246, 0 Jun  4 16:29 /dev/qat_mem
[work@tc-op bin]$ cat /etc/group | grep ssl_work
ssl_work:x:508:work

**Comment by paulturx** [comment]
Hi
You appear to be using quite an old version of QAT Engine if, as the error messages above seem to indicate, you are using the qat_mem.ko kernel module.  Could you let me know what versions of QAT driver and QAT Engine you are using?
Thanks.

**Comment by lcmmhcc** [comment]
it seems my work user was limited to use mmap by MAP_LOCK flag

**Comment by lcmmhcc** [comment]
solved by this answer, https://answers.launchpad.net/ubuntu/+question/268682

**Comment by mythi** [comment]
> it seems my work user was limited to use mmap by MAP_LOCK flag

This is also discussed https://github.com/intel/QAT_Engine/issues/135#issuecomment-611533715

@Yogaraj-Alamenda perhaps we should add a note about this to README/Troubleshooting?

**Comment by Yogaraj-Alamenda** [comment]
@mythi Sure we will add a note to the trouble shooting section in the README.

**Comment by lcmmhcc** [comment]
more details:
My work user was using  the default  "memlock"  limit config as  64Kbytes (in /etc/security/limits.conf or  ulimit -l), so  it would fail when call  mmap function when  with MAP_LOCKED and more than 64Kbytes.

in https://github.com/intel/QAT_Engine/blob/99fd3fba2e9d54e5bd41dd2295c102e81917e401/qae_mem_utils.c#L383
the code  try to mmap the "qat_contig_memfd"  with MAP_LOCKED  and  the length  "qmcfg.length*QAT_CONTIG_MEM_MMAP_ADJUSTMENT "
qmcfg.length = SLAB_SIZE = 0x20000 = 128K bytes 

that's why the work user failed to load qat  with the log "mmap: 11 Resource temporarily unavailable" 

solution:
edit /etc/security/limits.conf
and add  "work - memlock 140" or "work - memlock unlimited"

And don't forget  to follow the steps of the documents  below.
3.14 Running Applications as Non-Root User
https://01.org/sites/default/files/downloads/intelr-quickassist-technology/336210qatswprogguiderev001review.pdf

**Comment by Yogaraj-Alamenda** [comment]
Thanks @lcmmhcc  @mythi  These details are added in the README troubleshooting section https://github.com/intel/QAT_Engine#troubleshooting
