### ISSUE TITLE
How to upgrade from sync openssl to asynchronous openssl

### ISSUE THREAD

**Issue by l-w-p** [intel/QAT_Engine#116]
Can you provide a simple demo for reference?
How to upgrade from sync openssl to asynchronous openssl

**Comment by paulturx** [comment]
Hi
I hope that I am understanding your question correctly.  To run asynchronously doesn't need an 'upgrade' as such.  An example of how to run the OpenSSL speed command with/without QAT offload and synchronously/asynchronously is given in the QAT Engine README.md file, the relevant section of which I have copied below:-

### Run speed with the Intel&reg; QuickAssist Technology OpenSSL\* Engine

```text
cd /path/to/openssl/apps

* RSA 2K
  * Asynchronous
  ./openssl speed -engine qat -elapsed -async_jobs 72 rsa2048
  * Synchronous
  ./openssl speed -engine qat -elapsed rsa2048
  * Software
  ./openssl speed -elapsed rsa2048
* ECDH Compute Key
  * Asynchronous
  ./openssl speed -engine qat -elapsed -async_jobs 36 ecdh
  * Synchronous
  ./openssl speed -engine qat -elapsed ecdh
  * Software
  ./openssl speed -elapsed ecdh
* Chained Cipher: aes-128-cbc-hmac-sha1
  * Asynchronous
  ./openssl speed -engine qat -elapsed -async_jobs 128 -multi 2 -evp aes-128-cbc-hmac-sha1
  * Synchronous
  ./openssl speed -engine qat -elapsed -multi 2 -evp aes-128-cbc-hmac-sha1
  * Software
  ./openssl speed -elapsed -multi 2 -evp aes-128-cbc-hmac-sha1
```
An example of how to run asynchronously with the QAT engine within the OpenSSL s_server command would be 

 ./openssl s_server $SERVER_VER_OPTION -cert server.crt -key server.key -engine qat -WWW -accept 4411 -cipher ECDHE-RSA-AES256-SHA384 -asynch -nbio -tls1_2  2>&1|tee -a  $curPath/s_server_async_ECDHE_SHA384_4.txt > /dev/null &


Is this the sort of information you required?

**Comment by l-w-p** [comment]
thanks
