### ISSUE TITLE
cannot open /dev/qat_dev_processes file

### ISSUE THREAD

**Issue by manjeetbhatia** [intel/QAT_Engine#127]
After I installed openssl_1_1_1c
and QATEngine

below is trace of error

./openssl engine -t -c -vvvv qat
(qat) Reference implementation of QAT crypto engine
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF]
     ADF_UIO_PROXY err: icp_adf_userProcessToStart: Cannot open /dev/qat_dev_processes file
[ unavailable ]
     ENABLE_EXTERNAL_POLLING: Enables the external polling interface to the engine.
          (input flags): NO_INPUT
     POLL: Polls the engine for any completed requests

what are the files that I am missing?

**Comment by Yogaraj-Alamenda** [comment]
@manjeetbhatia  I suspect you are running QAT as non root user . If yes, could you please follow the steps as suggested in the section 3.14 (Running Applications as Non-Root User) from Programmer's guide doc in  the 01.org link below and see if it solves the issue.
https://01.org/sites/default/files/downloads//336210011qatswprogrammersguide.pdf

If not, then could you please see if the resolution suggested in the issue #108 solves the problem you are seeing.

**Comment by manjeetbhatia** [comment]
root@minion01:/home/vagrant/openssl/apps# ./openssl engine -t -c -vvvv qat 

ran as root user
will try blacklisting other modules, as suggested in issue #108

**Comment by manjeetbhatia** [comment]
I've rebuilt the qat driver

cd $ICP_ROOT
make clean

added these to blacklist
blacklist qat_c62x
blacklist qat_c62xvf
blacklist qat_c6xx
blacklist qat_c6xxvf
blacklist qat_c3xxx
blacklist qat_c3xxxvf
blacklist qat_d15xx
blacklist qat_d15xxvf
blacklist qat_c4xxx
blacklist qat_c4xxxvf
blacklist intel_qat

reboot

cd $ICP_ROOT
./configure
make install

cp QAT/build/c6xx_dev*.conf /etc/
service qat_service restart

same result

./openssl engine -t -c -vvvv qat
(qat) Reference implementation of QAT crypto engine
[RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF]
ADF_UIO_PROXY err: icp_adf_userProcessToStart: Cannot open /dev/qat_dev_processes file
[ unavailable ]

**Comment by Yogaraj-Alamenda** [comment]
@manjeetbhatia  Its difficult to pin point the exact problem here. Could you please check manually if the file  qat_dev_processes exists and has required permission after driver installation. And check demsg command if it shows any error message and share the driver installation log along with dmesg output to check further.

**Comment by manjeetbhatia** [comment]
ls -l /dev/qat_dev_processes
crw-rw---- 1 root root 245, 0 Dec 23 10:19 /dev/qat_dev_processes

file exists but I can't see the contents.

here's dmesg log

[  235.377051] intel_qat: loading out-of-tree module taints kernel.
[  235.377386] intel_qat: module verification failed: signature and/or required key missing - tainting kernel
[  235.386148] usdm_drv: Loading USDM Module Version 0.7.1 ...
[  235.386151] usdm_drv: IOCTLs: c0507100, c0507101, c0507102, c0047104
[  235.405211] QAT: Stopping all acceleration devices.
[  415.805784] QAT: Stopping all acceleration devices.
[  415.981057] QAT: Stopping all acceleration devices.
[  455.664894] QAT: Device not yet ready.
[325851.281208] QAT: Device not yet ready.
[326093.834335] QAT: Device not yet ready.


so is that happening because I loaded out of kernel tree driver ? I guess i just need to allow kernel to execute tainted.

**Comment by Yogaraj-Alamenda** [comment]
@manjeetbhatia  Could you please let us know what is the config file you are using ? I hope you are using the one that is supplied in the QAT Engine directory qat/config. Also could you please share the driver installation logs and also the configure command used for the QAT Engine compilation. 
I am suspecting something went wrong in the driver installation or Path provided in the engine configure is not same as where driver is installed.

**Comment by manjeetbhatia** [comment]
@Yogaraj-Alamenda 

It works now if I don't restart qat service, when I installed QAT_engine and QAT_zip and restarted qat service openssl show qat device unavailable but if I don't restart qat service openssl works fine, no idea if this is expected behavior or a perhaps an issue?

**Comment by TyKeeling** [comment]
Hi @manjeetbhatia, did you find a resolution for this problem? Thank you.
