### ISSUE TITLE
SSL directive style in Nginx patch

### ISSUE THREAD

**Issue by agrandi** [intel/QAT_Engine#13]
Originally reported here #10 by @InfoHunter 

For nginx-patch of async use of QAT, the problem is the patch does not support the following style of nginx configuration file: 

    listen 443 ssl;

it only supports the directive.

     ssl on; 

And no document mentions this situation, and this really caused me lots of time to resolve the problem.

**Comment by InfoHunter** [comment]
I provide a fix as following:

```
diff --git a/src/http/ngx_http_request.c b/src/http/ngx_http_request.c
index 51a5261..16a56bd 100644
--- a/src/http/ngx_http_request.c
+++ b/src/http/ngx_http_request.c
@@ -338,6 +338,10 @@ ngx_http_init_connection(ngx_connection_t *c)

         hc->ssl = 1;

+#if (NGX_SSL_ASYNC)
+        sscf->ssl.asynch = sscf->enable_asynch;
+#endif
+
         rev->handler = ngx_http_ssl_handshake;
     }
     }
```

**Comment by agrandi** [comment]
I have reported the bug to the team that maintains the Nginx patch.

At the moment I don't have an estimated date for the new release, but I will update this ticket if I have more information.

**Comment by InfoHunter** [comment]
Hi @agrandi , so is there any progress on this topic?

**Comment by agrandi** [comment]
Hi @InfoHunter, the fix has been implemented and we are looking at creating a new release in the coming weeks

**Comment by InfoHunter** [comment]
Got it. Thanks man.

**Comment by stevelinsell** [comment]
Closing this as the latest QAT nginx patch on 01.org (v0.3.1) supports both styles of ssl directive.
