### ISSUE TITLE
HAProxy and qat openssl engine

### ISSUE THREAD

**Issue by beluc** [intel/QAT_Engine#135]
Hi,
I had problem when making ssl connection againt haproxy launched with qat configured as non-root user.

here is the debug output :
[DEBUG][qat_rsa.c:911:qat_rsa_priv_enc()] - Started.
[DEBUG][qat_rsa.c:403:build_decrypt_op_buf()] - Started
[DEBUG][qat_rsa.c:415:build_decrypt_op_buf()] flen = 256, padding = 3
[WARNING][qat_asym_common.c:112:qat_BN_to_FB()] Failed to allocate fb->pData
[WARNING][qat_rsa.c:460:build_decrypt_op_buf()] Failed to convert privateKeyRep2 elements to flatbuffer
[WARNING][qat_rsa.c:944:qat_rsa_priv_enc()] Failure in build_decrypt_op_buf
[DEBUG][qat_rsa.c:210:rsa_decrypt_op_buf_free()] - Started
[DEBUG][qat_rsa.c:233:rsa_decrypt_op_buf_free()] - Finished

kernel modules seems well loaded :
usdm_drv               94208  2
qat_c62x               20480  3
intel_qat             286720  9 qat_c62x,usdm_drv
uio                    20480  7 intel_qat
authenc                16384  1 intel_qat

qat devices seems well too :
Checking status of all devices.
There is 3 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 0,  bsf: 0000:05:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 0,  bsf: 0000:07:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 0,  bsf: 0000:09:00.0,  #accel: 5 #engines: 10 state: up

any ideas plz ?

Regards.

**Comment by paulturx** [comment]
Hi
Please could you give more details of your set-up:-
QAT driver version 
QAT Engine version and configure command used in the build
OpenSSL version and build commands
haproxy version and build commands 

maybe a dump of the command history of your board will provide this info.

In the meantime have you consulted the following document which you may find useful:-
https://01.org/sites/default/files/downloads//337430-002ushaproxyqat.pdf ?

**Comment by beluc** [comment]
Hi,

qat driver : qat1.7.l.4.8.0-00005.tar.gz

qat engine : v0.5.43 
> ./configure --with-qat_dir=/root/qat --with-openssl_install_dir=/usr/lib/x86_64-linux-gnu --enable-openssl_install_build_arch_path

> # openssl  version -a
> OpenSSL 1.1.1d  10 Sep 2019
> built on: Sat Oct 12 19:56:43 2019 UTC
> platform: debian-amd64
> options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr)
> compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-YwazYa/openssl-1.1.1d=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
> OPENSSLDIR: "/usr/lib/ssl"
> ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
> Seeding source: os-specific

> # haproxy -vv
> HA-Proxy version 1.8.19-1+deb10u1 2019/11/27
> Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>
> 
> Build options :
>   TARGET  = linux2628
>   CPU     = generic
>   CC      = gcc
>   CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-gZgucB/haproxy-1.8.19=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-null-dereference -Wno-unused-label
>   OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_NS=1
> 
> Default settings :
>   maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
> 
> Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
> Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
> OpenSSL library supports TLS extensions : yes
> OpenSSL library supports SNI : yes
> OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
> Built with Lua version : Lua 5.3.3
> Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
> Encrypted password support via crypt(3): yes
> Built with multi-threading support.
> Built with PCRE2 version : 10.32 2018-09-10
> PCRE2 library supports JIT : yes
> Built with zlib version : 1.2.11
> Running on zlib version : 1.2.11
> Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
> Built with network namespace support.
> 
> Available polling systems :
>       epoll : pref=300,  test result OK
>        poll : pref=200,  test result OK
>      select : pref=150,  test result OK
> Total: 3 (3 usable), will use epoll.
> 
> Available filters :
> 	[SPOE] spoe
> 	[COMP] compression
> 	[TRACE] trace

**Comment by mythi** [comment]
> launched with qat configured as non-root user.

QAT Engine/libqat uses `usdm_drv` and `mmap()`'s physical memory regions it gets from the memory driver. On some distro's with systemd, non-root users have `memlock`  limit set by default to too low value and that triggers `mmap()`' error with `-EAGAIN`.

To see if this is the case, run 1) strace to see the error, and 2) see the `memlock` limit for your HAproxy process.

If `memlock` is your problem, set a bigger value, e.g., for your `haproxy.service` by adding and override .conf to it:

```
[Service]
LimitMEMLOCK=<some value, e.g, 16M>
```

**Comment by beluc** [comment]
Hi,
you are right, LimitMEMLOCK fixed the problem !
Ty
