### ISSUE TITLE
Two QAT drivers are present with latest kernels and qat service fails to start.

### ISSUE THREAD

**Issue by stevelinsell** [intel/QAT_Engine#14]
This issue was originally reported as part of #8 by @tsenghu as follows:

> We have decided to upgrade to Ubuntu 16.04/linux kernel 4.4.0-57-generic.
> After linux is up, I see two drivers that is related to QAT.
> One is qat_dh895xcc and another one is intel_qat.
> After I inserted two drivers (icp_qa_al.ko and qat_contig_mem.ko) and try to run “service qat_service start”.
> It failed to start.

**Comment by stevelinsell** [comment]
The reason you see extra QAT Drivers present is because the latest kernels come a QAT kernel driver as part  of the Linux distribution. You may see this referred to as the in tree 'Upstream' QAT Driver. This driver is a kernel space driver only and is not compatible with the usual package that you have been using up to now. This is part of a longer term project to make support for QAT included in kernel distributions. The plan is to release a matching out of tree 'Upstream' package that provides the user space functionality that is not included with the kernel space driver. You will then be able to utilize it from user space the same way as the existing package. This is referred to as the 'Upstream Driver' in the README.md documentation. I do not have a date when the out of tree 'Upstream' package will be available.
 
For the moment until that package is released, then if you want to use a new kernel then you need to blacklist the in tree 'Upstream' QAT Driver and continue to use the existing package as you did previously.
I don't use Ubuntu myself but I think in order to blacklist the driver you will need to edit a file called:

 `/etc/modprobe.d/blacklist.conf`

and add the following for each driver you want to blacklist:

 `blacklist <modulename>`

so in your case you would add two lines one for qat_dh895xcc and one for intel_qat. You may also add a line for usdm_drv which is the related memory driver but this may not be necessary. 
Then I think you need to do the following:
 ```
depmod -a
 update-initramfs -u
```
As I said I don't have a Ubuntu distribution at hand so just use the above for guidance and check for sure how you blacklist in the man pages for your distribution/online.

Hope this information is useful. Let me know if this does not sole your problem.

**Comment by tsenghu** [comment]
Thanks,

I figured out yesterday.  Wish Intel publish something so I don’t have to spend time on it.

 

Thanks

 

Tseng
