### ISSUE TITLE
ERROR: could not insert 'usdm_drv' 

### ISSUE THREAD

**Issue by liuzh-sa** [intel/QAT_Engine#140]
Hi,
When it comes to loading of the driver and qat_service it gives this message:

[Wed Mar  4 11:23:22 2020] QAT: Invalid ioctl
[Wed Mar  4 11:23:26 2020] QAT: Invalid header 0x6f6d
[Wed Mar  4 11:23:26 2020] dh895xcc 0000:1c:00.0: Failed to map FW
[Wed Mar  4 11:23:26 2020] dh895xcc 0000:1c:00.0: Failed to load acceleration FW
[Wed Mar  4 11:23:26 2020] dh895xcc 0000:1c:00.0: Resetting device qat_dev0
[Wed Mar  4 11:23:26 2020] dh895xcc 0000:1c:00.0: Secondary bus reset
[Wed Mar  4 11:23:26 2020] pciehp 0000:1b:00.0:pcie204: Slot(0-1): Link Down
[Wed Mar  4 11:23:26 2020] pciehp 0000:1b:00.0:pcie204: Slot(0-1): Already disabled
[Wed Mar  4 11:23:26 2020] pciehp 0000:1b:00.0:pcie204: Slot(0-1): Link Up
[Wed Mar  4 11:23:26 2020] pciehp 0000:1b:00.0:pcie204: Slot(0-1): Latch open
[Wed Mar  4 11:23:26 2020] dh895xcc: probe of 0000:1c:00.0 failed with error -14
[Wed Mar  4 11:23:26 2020] usdm_drv: Unknown symbol qdm_iommu_unmap (err 0)
[Wed Mar  4 11:23:26 2020] usdm_drv: Unknown symbol qdm_iommu_map (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol qdm_iommu_unmap (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_service_unregister (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: disagrees about version of symbol adf_dev_put
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_dev_put (err -22)
[Wed Mar  4 11:23:26 2020] qat_api: disagrees about version of symbol adf_dev_get
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_dev_get (err -22)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_cfg_get_param_value (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_poll_all_banks (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_remove_ring (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_handle_response (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_cfg_sec_find (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_poll_bank (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_create_ring (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_service_register (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol adf_send_message (err 0)
[Wed Mar  4 11:23:26 2020] qat_api: Unknown symbol qdm_iommu_map (err 0)
[Wed Mar  4 11:23:26 2020] QAT: Invalid ioctl

And start service qat_service start it gives this message:
modprobe: ERROR: could not insert 'usdm_drv': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'qat_api': Unknown symbol in module, or unknown parameter (see dmesg)
Restarting all devices.
Failed to stop device 
Checking status of all devices.
There is 0 QAT acceleration device(s) in the system:

any pointers much appreciated.

**Comment by jdschuet** [comment]
Hello,

The first error messages likely come from the QAT kernel modules that are included in the kernel.
Which QAT Driver version is being used?
Which Distro/kernel version?

Thanks,
Joel

**Comment by liuzh-sa** [comment]
> Hello,
> 
> The first error messages likely come from the QAT kernel modules that are included in the kernel.
> Which QAT Driver version is being used?
> Which Distro/kernel version?
> 
> Thanks,
> Joel

**Comment by liuzh-sa** [comment]
@jdschuet Thanks for your reply. I have solevd this problem.
 I had blacklisted intel_qat and all its dependencies. And reboot, it works.
cat /etc/modprobe.d/my-blacklist.conf 
blacklist intel_qat
blacklist qat_c3xxx
blacklist qat_c3xxxvf
blacklist dh_generic
blacklist rsa_generic
blacklist authenc
