### ISSUE TITLE
aes-128-hmac-sha1 encrypt-then-mac

### ISSUE THREAD

**Issue by benbro** [intel/QAT_Engine#144]
Is there support for accelerated aes-128-hmac-sha1 encrypt-then-mac?

**Comment by paulturx** [comment]
Hi benbro.  There is currently no support for accelerated aes-128-hmac-sha1 encrypt-then-mac, nor is any support planned in future releases.

Regards,
    paulturx

**Comment by benbro** [comment]
Thank you.
