### ISSUE TITLE
Alloc fail and segfault occor.

### ISSUE THREAD

**Issue by dhkim88** [intel/QAT_Engine#150]
HI
I was check the long-run test about QAT-Engine using IXIA in multi-thread env. (MATHOD_ALL, ASYNC MODE)
QAT had two problems. The first is a memory allocation failure problem, the second is a segfault caused by a memory allocation failure.

1)  alloc fail
	May 14 11:54:25 kernel: sslp_worker_3: page allocation failure: order:9, mode:0x14040c0(GFP_KERNEL|__GFP_COMP), nodemask=(null)
	May 14 11:54:25 kernel: sslp_worker_3 cpuset=VSI0 mems_allowed=0-1
	May 14 11:54:25 kernel: CPU: 47 PID: 46752 Comm: sslp_worker_3 Tainted: GF          O    4.14.169-2.0.48421
	May 14 11:54:25 kernel: Hardware name: Advantech FWA-6170/GSMB-6170MB, BIOS 6170V102 02/22/2018
	May 14 11:54:25 kernel: Call Trace:
	May 14 11:54:25 kernel: dump_stack+0x66/0x82
	May 14 11:54:25 kernel: warn_alloc+0x114/0x1b0
	May 14 11:54:25 kernel: ? __alloc_pages_direct_compact+0x4a/0xf0
	May 14 11:54:25 kernel: __alloc_pages_slowpath+0xd09/0xd40
	May 14 11:54:25 kernel: ? update_load_avg+0x401/0x4e0
	May 14 11:54:25 kernel: ? enqueue_task_fair+0x53/0x590
	May 14 11:54:25 kernel: __alloc_pages_nodemask+0x294/0x2b0
	May 14 11:54:25 kernel: kmalloc_large_node+0x37/0x70
	May 14 11:54:25 kernel: __kmalloc_node+0x1d4/0x270
	May 14 11:54:25 kernel: ? wake_up_q+0x3f/0x70
	May 14 11:54:25 kernel: mem_ioctl+0x526/0xa50 [usdm_drv]
	May 14 11:54:25 kernel: do_vfs_ioctl+0xa1/0x600
	May 14 11:54:25 kernel: ? __audit_syscall_entry+0xbc/0x110
	May 14 11:54:25 kernel: ? syscall_trace_enter+0x1df/0x2e0
	May 14 11:54:25 kernel: SyS_ioctl+0x74/0x80
	May 14 11:54:25 kernel: do_syscall_64+0x6e/0x1a0
	May 14 11:54:25 kernel: entry_SYSCALL_64_after_hwframe+0x3d/0xa2
	May 14 11:54:25 kernel: RIP: 0033:0x7f4abaa4c267
	May 14 11:54:25 kernel: RSP: 002b:00007f4a9814a658 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
	May 14 11:54:25 kernel: RAX: ffffffffffffffda RBX: 0000000000000080 RCX: 00007f4abaa4c267
	May 14 11:54:25 kernel: RDX: 00007f4a9814a680 RSI: 00000000c0507100 RDI: 0000000000000015
	May 14 11:54:25 kernel: RBP: 00007f4a9814a680 R08: 0000000000000001 R09: 0000000000000800
	May 14 11:54:25 kernel: R10: 00007f4aa45d8050 R11: 0000000000000246 R12: ffffffffffffffff
	May 14 11:54:25 kernel: R13: 0000000000000015 R14: 0000000000000000 R15: 0000000000000000
	May 14 11:54:25 kernel: Mem-Info:
	May 14 11:54:25 kernel: active_anon:4024509 inactive_anon:1866 isolated_anon:0#012 active_file:1339095 inactive_file:4492882 isolated_file:0#012 unevictable:5902 dirty:56728 writeback:0 unstable:0#012 slab_reclaimable:3311170 slab_unreclaimable:1199299#012 mapped:51614 shmem:10741 pagetables:25914 bounce:0#012 free:929425 free_pcp:4652 free_cma:0
	May 14 11:54:25 kernel: Node 0 active_anon:7013432kB inactive_anon:6764kB active_file:2385324kB inactive_file:8848164kB unevictable:16408kB isolated(anon):0kB isolated(file):0kB mapped:113300kB dirty:70652kB writeback:0kB shmem:10384kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 2502656kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
	May 14 11:54:25 kernel: Node 1 active_anon:9089804kB inactive_anon:1136kB active_file:2971068kB inactive_file:9123520kB unevictable:7200kB isolated(anon):0kB isolated(file):0kB mapped:93088kB dirty:156424kB writeback:0kB shmem:32948kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 1568768kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
	May 14 11:54:25 kernel: Node 0 DMA free:15884kB min:20kB low:32kB high:44kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15968kB managed:15884kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
	May 14 11:54:25 kernel: lowmem_reserve[]: 0 1456 31664 31664
	May 14 11:54:25 kernel: Node 0 DMA32 free:128908kB min:2052kB low:3540kB high:5028kB active_anon:1208960kB inactive_anon:0kB active_file:888kB inactive_file:4216kB unevictable:0kB writepending:80kB present:1734056kB managed:1515276kB mlocked:0kB kernel_stack:16kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
	May 14 11:54:25 kernel: lowmem_reserve[]: 0 0 30207 30207
	May 14 11:54:25 kernel: Node 0 Normal free:3440220kB min:42576kB low:73508kB high:104440kB active_anon:5804604kB inactive_anon:6752kB active_file:2384508kB inactive_file:8844332kB unevictable:16408kB writepending:71072kB present:31457280kB managed:30932920kB mlocked:16408kB kernel_stack:15832kB pagetables:50188kB bounce:0kB free_pcp:18872kB local_pcp:0kB free_cma:0kB
	May 14 11:54:25 kernel: lowmem_reserve[]: 0 0 0 0
	May 14 11:54:25 kernel: Node 1 Normal free:94328kB min:45456kB low:78480kB high:111504kB active_anon:9078728kB inactive_anon:1144kB active_file:2971060kB inactive_file:9123552kB unevictable:7200kB writepending:156452kB present:33554432kB managed:33025500kB mlocked:7200kB kernel_stack:12696kB pagetables:53068kB bounce:0kB free_pcp:8712kB local_pcp:0kB free_cma:0kB
	May 14 11:54:25 kernel: lowmem_reserve[]: 0 0 0 0
	May 14 11:54:25 kernel: Node 0 DMA: 1*4kB (U) 1*8kB (U) 0*16kB 0*32kB 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15884kB
	May 14 11:54:25 kernel: Node 0 DMA32: 137*4kB (UME) 165*8kB (UME) 294*16kB (UME) 469*32kB (UMEH) 173*64kB (UMEH) 98*128kB (UMEH) 71*256kB (UMEH) 56*512kB (UMEH) 36*1024kB (UMEH) 0*2048kB 0*4096kB = 128908kB
	May 14 11:54:25 kernel: Node 0 Normal: 360864*4kB (UMEH) 148137*8kB (UMEH) 26300*16kB (UMEH) 6208*32kB (UMEH) 1251*64kB (UMEH) 331*128kB (UMEH) 63*256kB (UMH) 13*512kB (UH) 0*1024kB 18*2048kB (H) 0*4096kB = 3430088kB
	May 14 11:54:25 kernel: Node 1 Normal: 5525*4kB (UME) 1500*8kB (ME) 2237*16kB (UMH) 262*32kB (UH) 1*64kB (H) 1*128kB (H) 1*256kB (H) 1*512kB (H) 1*1024kB (H) 0*2048kB 0*4096kB = 80260kB
	May 14 11:54:25 kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
	May 14 11:54:25 kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
	May 14 11:54:25 kernel: Node 1 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
	May 14 11:54:25 kernel: Node 1 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
	May 14 11:54:25 kernel: 5845257 total pagecache pages
	May 14 11:54:25 kernel: 0 pages in swap cache
	May 14 11:54:25 kernel: Swap cache stats: add 0, delete 0, find 0/0
	May 14 11:54:25 kernel: Free swap  = 0kB
	May 14 11:54:25 kernel: Total swap = 0kB
	May 14 11:54:25 kernel: 16690434 pages RAM
	May 14 11:54:25 kernel: 0 pages HighMem/MovableOnly
	May 14 11:54:25 kernel: 318039 pages reserved
	May 14 11:54:25 kernel: 0 pages cma reserved
	May 14 11:54:25 kernel: 0 pages hwpoisoned
	May 14 11:54:25 kernel: usdm_drv: userMemAlloc:395 Unable to allocate memory slab or wrong alignment:           (null)
	May 14 11:54:25 kernel: usdm_drv: dev_mem_alloc:600 userMemAlloc failed

2) segfault in openssl-1.1.1/crypto/ec/ec_kmeth.c

	int ECDH_compute_key(void *out, size_t outlen, const EC_POINT *pub_key,
						 const EC_KEY *eckey,
						 void *(*KDF) (const void *in, size_t inlen, void *out,
									   size_t *outlen))
	{
		unsigned char *sec = NULL;
		size_t seclen;
		....
		....
		if (!eckey->meth->compute_key(&sec, &seclen, pub_key, eckey)) // call qat_engine_ecdh_compute_key func and alloc fail, return -1
			return 0;
		if (KDF != NULL) {
			KDF(sec, seclen, out, &outlen);
		} else {
			if (outlen > seclen)
				outlen = seclen;
			memcpy(out, sec, outlen);   // segfault occor.
		}
		....
	}

	
The failure return value of the qat_engine_ecdh_compute_key function seems to be wrong. Please check this.
And I want to reduce alloc fail situation. If applying section 3.16 of the document have any effect? 
https://01.org/sites/default/files/downloads//336210-012-intel-qat-swpg.pdf
Please let me know if there is any another way.

Thank you.

**Comment by paulturx** [comment]
Hi dhkim88
Thanks for your comment.  Regarding the return value, you make a valid point and we are planning to fix the issue in a future release.

Regarding the hugepages issue, I shall refer this 'issue' to a colleague  who knows more about the use of hugepages.

Thanks & regards,
    paulturx

**Comment by dhkim88** [comment]
Hi paulturx.

If it's okay, please let me know what you modified.
And do you have any update about the page issue?

Thank you.

**Comment by jdschuet** [comment]
Hi dhkim88,

Can you share additional information?  Are you using hugepages?  If so how are they configured?  i.e. are you using kernel boot parameters to set aside hugepage memory?  When loading the usdm driver, are additional parameters being provided for hugepages?

Thanks,
Joel

**Comment by dhkim88** [comment]
Hi Joel.

ixia settings: TLS V1.3 / AES256-SHA384 300CPS, traffic with attached 4K size text file. 

Q. Are you using hugepages?
A. I don't use hugepages.

Q. When loading the usdm driver, are additional parameters being provided for hugepages?
A. No parameters added.

When a mem-alloc failure situation like #1 occurs, can you reduce the failure situation by changing the usdm setting or adding a parameter?
Please let me know if you have any questions.

Thank you.
