### ISSUE TITLE
How to check whether the network interface card has QAT function or not?

### ISSUE THREAD

**Issue by changchengx** [intel/QAT_Engine#152]

**Comment by Yogaraj-Alamenda** [comment]
@changchengx  Can you please elaborate your question ? Do you mean to check whether QAT card is present ?

**Comment by changchengx** [comment]
@Yogaraj-Alamenda 
Yes, through C code.

**Comment by Yogaraj-Alamenda** [comment]
Currently there is no API available from the driver that tells QAT card is present

**Comment by Yogaraj-Alamenda** [comment]
@changchengx  Just checked internally and there is standard way to check whether there is QAT acceleration present in the system and the driver running is to call icp_sal_userStartMultiProcess(), if it fails then you can’t use the accelerator. The function is designed to be safe if there is no QAT accelerator in the system and just to fail.
