### ISSUE TITLE
No /sys/kernel/debug/qat_* files for c6xx devices

### ISSUE THREAD

**Issue by nitishroy84** [intel/QAT_Engine#153]
QAT specific debug files are not present under /sys/kernel/debug/.

Following is the details:

Machine Info:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    20
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6210U CPU @ 2.50GHz
Stepping:              7
CPU MHz:               1110.948
CPU max MHz:           3900.0000
CPU min MHz:           1000.0000
BogoMIPS:              5000.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              28160K
NUMA node0 CPU(s):     0-39

QAT driver:
Version: 1.7.l.4.9.0-00008
./configure --enable-icp-debug

QAT Device:
There is 2 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 0,  bsf: 0000:19:00.0,  #accel: 4 #engines: 8 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 0,  bsf: 0000:1a:00.0,  #accel: 4 #engines: 8 state: up

**Comment by mythi** [comment]
> QAT specific debug files are not present under /sys/kernel/debug/.

did you reload the out-of-tree driver?

**Comment by nitishroy84** [comment]
I didn't explicitly reload the driver.

As part of 'make install' driver is loaded.

lsmod | grep qa
qat_c62x               20480  2
intel_qat             192512  13 qat_c62x,usdm_drv
uio                    20480  17 intel_qat

**Comment by nitishroy84** [comment]
> > QAT specific debug files are not present under /sys/kernel/debug/.
> 
> did you reload the out-of-tree driver?

@mythi 

I am stuck at this point. Please let me know if there is any way to fix this issue. I compiled QAT-1.7 without any additional configuration.

Just used, ./configure 

Thanks

**Comment by mythi** [comment]
@nitishroy84 do you have debugfs mounted in your distro? any errors in `dmesg` for QAT?

**Comment by nitishroy84** [comment]
> @nitishroy84 do you have debugfs mounted in your distro? any errors in `dmesg` for QAT?

Oops...no debugfs mounted on that machine. It is working now.

Thanks a lot !!!

**Comment by nitishroy84** [comment]
Debugfs should be mounted. If there is no debugfs mounted it should be logged in Syslog.Will file separate issue for the same.

Thanks @mythi

**Comment by mythi** [comment]
>  If there is no debugfs mounted it should be logged in Syslog

fw_counters is a service that the kernel driver/firmware provides and it has a dependency to debugfs.
