### ISSUE TITLE
Allow compiling with both QAT and RSA multi-buffer support and run-time selection of acceleration method

### ISSUE THREAD

**Issue by ipuustin** [intel/QAT_Engine#158]
Right now the engine needs to be compiled to either support QAT or RSA multi-buffer acceleration (https://github.com/intel/QAT_Engine/blob/master/.tools/configure.ac#L244-L255). However, for distribution purposes, it would be great if both acceleration modes could be compiled into the engine and the desired acceleration method chosen at run-time using QAT engine messages.

**Comment by Yogaraj-Alamenda** [comment]
At present the build doesn't have this capability but there is plan to bring in this support. Will keep you posted.
