### ISSUE TITLE
Using clang to compile the engine.

### ISSUE THREAD

**Issue by mkaniewski** [intel/QAT_Engine#161]
Hi,

we use QAT Engine in one of our products based on FreeBSD. In Makefile.am there is a line:

https://github.com/intel/QAT_Engine/blob/464221c87cf127261e89f7e8fad678d503457262/.tools/Makefile.am#L125

In FreeBSD clang is the default compiler and we would like to use it whenever it is possible (gcc is not a part of a base system and must be installed as an additional package). We made a test build with clang and it builds ok and works without any problems. Do you know if there were any reasons why gcc was hardcoded in Makefile.am? 

Thanks.

**Comment by Yogaraj-Alamenda** [comment]
Hi @mkaniewski 
                      
There isn't any specific reason to use gcc over clang in  FreeBSD except few security compiler flags eg:  -fno-strict-overflow option is not available in clang so we moved to use gcc instead to be consistent with Linux as we didn't find any difference between gcc and clang.  I will check and remove forcing to use gcc and use whatever OS provides by default

cc: warning: argument unused during compilation: '-fno-strict-overflow'

**Comment by Yogaraj-Alamenda** [comment]
Hi @mkaniewski  The corresponding changes are available in v0.6.1 release now.

**Comment by mkaniewski** [comment]
Thank you!
