### ISSUE TITLE
missing crypto_mb/cpu_features.h

### ISSUE THREAD

**Issue by mythi** [intel/QAT_Engine#166]
I have ipp-crypto and intel-ipsec-mb installed but the build fails with:

```
make[1]: Entering directory '/QAT_Engine'
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.tools  -I/usr/lib64/include   -I/usr/local/include -I/usr/include  -shared -fPIC -Wall -Wformat -Wformat-security -O2 -D_FORTIFY_SOURCE=2 -fno-delete-null-pointer-checks -fwrapv -fstack-protector-strong -fno-strict-overflow      -DOPENSSL_MULTIBUFF_OFFLOAD -DOPENSSL_IPSEC_OFFLOAD -DOPENSSL_DISABLE_QAT_RSA -DOPENSSL_DISABLE_QAT_CIPHERS -DOPENSSL_DISABLE_QAT_ECDH -DOPENSSL_DISABLE_QAT_ECDSA -DOPENSSL_DISABLE_QAT_DSA -DOPENSSL_DISABLE_QAT_DH -DOPENSSL_DISABLE_QAT_PRF -DOPENSSL_DISABLE_QAT_HKDF -DOPENSSL_DISABLE_QAT_ECX -DOPENSSL_ENABLE_VAES_GCM -DOPENSSL_ENABLE_MULTIBUFF_RSA -DOPENSSL_ENABLE_MULTIBUFF_ECX    -DQAT_ENGINE_ID=avx512engine        -g -O2 -MT e_qat.lo -MD -MP -MF .deps/e_qat.Tpo -c -o e_qat.lo e_qat.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.tools -I/usr/lib64/include -I/usr/local/include -I/usr/include -fPIC -Wall -Wformat -Wformat-security -O2 -D_FORTIFY_SOURCE=2 -fno-delete-null-pointer-checks -fwrapv -fstack-protector-strong -fno-strict-overflow -DOPENSSL_MULTIBUFF_OFFLOAD -DOPENSSL_IPSEC_OFFLOAD -DOPENSSL_DISABLE_QAT_RSA -DOPENSSL_DISABLE_QAT_CIPHERS -DOPENSSL_DISABLE_QAT_ECDH -DOPENSSL_DISABLE_QAT_ECDSA -DOPENSSL_DISABLE_QAT_DSA -DOPENSSL_DISABLE_QAT_DH -DOPENSSL_DISABLE_QAT_PRF -DOPENSSL_DISABLE_QAT_HKDF -DOPENSSL_DISABLE_QAT_ECX -DOPENSSL_ENABLE_VAES_GCM -DOPENSSL_ENABLE_MULTIBUFF_RSA -DOPENSSL_ENABLE_MULTIBUFF_ECX -DQAT_ENGINE_ID=avx512engine -g -O2 -MT e_qat.lo -MD -MP -MF .deps/e_qat.Tpo -c e_qat.c  -fPIC -DPIC -o .libs/e_qat.o
e_qat.c:112:11: fatal error: crypto_mb/cpu_features.h: No such file or directory
  112 | # include "crypto_mb/cpu_features.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:739: e_qat.lo] Error 1
make[1]: Leaving directory '/QAT_Engine'
make: *** [Makefile:589: all] Error 2
```

I'm not able to find what provides this (intel-ipsec-mb has `cpu_feature.h` but it's not part of the lib header install).

**Comment by Yogaraj-Alamenda** [comment]
Hi @mythi ,
 I think you are using crypto-mb that doesn't contain the latest changes needed for QAT Engine. Could you please use the crypto-mb  from the develop branch using the commit below mentioned in release notes ? 

Crypto Multi-buffer Library version 0.5.3 for Multi-buffer Software Optimizations for RSA and X25519 using the commit - (intel/ipp-crypto@87d413b)

**Comment by mythi** [comment]
I don't want to use unreleased versions because non-reproducible builds may break our CI builds (which is what happened last week: https://github.com/intel/intel-device-plugins-for-kubernetes/pull/439/commits/02fb1209d0550f8312f64d8cae4250bba7a26303)

**Comment by Yogaraj-Alamenda** [comment]
HI @mythi Sorry for that, Actually there is commit alignment issue between both the releases which is why it is not aligned with  the release tag "ippcp_2020u2".  If you replace with commit id "87d413bee937d837677bb0dee09e075bcb421358"  instead of release tag "ippcp_2020u2" then it should be fine. 
Please note the crypto-mb commit mentioned is on top of release ippcp_2020u2 with just API name changes and spec file changes and is of same quality as release branch.

From next release QAT Engine should be aligned with crypto-mb release tag.

**Comment by mythi** [comment]
I've successfully updated to `ippcp_2020u3` and `v0.6.1`.
