### ISSUE TITLE
QAT Digest is not Calculating

### ISSUE THREAD

**Issue by alptekinkarabacak** [intel/QAT_Engine#169]
Hi,
I am newbie in QAT crypto and I am using DPDK crypto APIs. I have a problem with digest calculation. When I try to execute example of DPDK l2fwd-crypto with debug flags are open. The Digest result are always 0 0 0 0. Here is an sample output:

`auth iv: at [0x17e317bd8], len=16
00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
digest: at [0x17e76c725], len=4
00000000: 00 00 00 00`

And here is my sample execution parameters:

`./l2fwd-crypto --log-level "pmd.qat_dp,8" l 5-6 -n 2 -- -p 0x3 --chain HASH_ONLY --cdev_type HW --auth_algo snow3g-uia2 --auth_op GENERATE --auth_key 00:01:02:03:04:05:06:07:08:09:0a:0b:0c:0d:0e:0f --auth_iv 10:0f:0e:0d:0e:0b:0a:09:08:07:06:05:04:03:02:01 --digest 4 --no-mac-updating`

**Comment by Yogaraj-Alamenda** [comment]
@alptekinkarabacak The issue seems not using QAT Engine and is related to QAT driver with DPDK . Let me check with driver internally and get back to you.  Also could you please provide some more information like how the application is setup etc.

**Comment by alptekinkarabacak** [comment]
@Yogaraj-Alamenda Thanks for reply first.
DPDK version of my application is 19.11.5. My device is version is C62x. Bind 2 phycial ethernet interfaces to DPDK and connect each other with CAT-6.
In my output, do not get any errors and the enqueued and dequeued package numbers are the same. And seems nothing wrong. But digest (or MAC) output and auth iv are seems zero.
I read a bug fixes about that issue which is released on DPDK 18.11 and named "crypto/qat: fix digest in wireless auth case", but I am already using newest version of that release.
