### ISSUE TITLE
There is 0 QAT acceleration device(s) in the system

### ISSUE THREAD

**Issue by davidka79** [intel/QAT_Engine#171]
Hello
I am trying to install QAT Engine on Ubuntu 20.04
Server SuperMicro X11DPU/Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz/C620 Series Chipset Family
I followed the instruction
Compile 

- QAT driver 
- QAT openssl 1.1.1h
- QAT engine
- QAT Zip

set environment:

- ICP_ROOT
- QZ_ROOT
- ICP_BUILD_OUTPUT
- OPENSSL_ROOT
- OPENSSL_LIB
- LD_LIBRARY_PATH
- OPENSSL_ENGINES

extra:

- NGINX_INSTALL_DIR

copy qat engine config to /etc    c6xx_dev0.conf
stop and start qat_service

after compiling I can not execute openssl test 
```
openssl engine -t -c -vvvv qatengine
(qatengine) Reference implementation of QAT crypto engine v0.6.1
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF, HKDF, X25519, X448]
     ADF_UIO_PROXY err: icp_adf_userProcessToStart: Cannot open /dev/qat_dev_processes file
[ unavailable ]
```

and at syslog I am getting error on qat_service start
```
Nov 03 17:33:10 ubuntu systemd[1]: Starting LSB: modprobe the QAT modules, which loads dependant modules, before calling the user space utility to pass configuration parameters...
Nov 03 17:33:10 ubuntu qat_service[217531]: Restarting all devices.
Nov 03 17:33:10 ubuntu qat_service[217532]: Checking status of all devices.
Nov 03 17:33:10 ubuntu qat_service[217532]: There is 0 QAT acceleration device(s) in the system:
Nov 03 17:33:10 ubuntu systemd[1]: Started LSB: modprobe the QAT modules, which loads dependant modules, before calling the user space utility to pass configuration parameters.
```

at kernel.log
```
Nov  3 17:14:54 ubuntu kernel: [18846.796803] QAT: Stopping all acceleration devices.
Nov  3 17:15:02 ubuntu kernel: [18854.717383] QAT: Stopping all acceleration devices.
Nov  3 17:17:38 ubuntu kernel: [19011.449323] QAT: Device not yet ready.
Nov  3 17:26:47 ubuntu kernel: [19560.367771] QAT: Stopping all acceleration devices.
Nov  3 17:26:51 ubuntu kernel: [19563.779430] QAT: Stopping all acceleration devices.
Nov  3 17:31:23 ubuntu kernel: [19836.357026] QAT: Device not yet ready.
Nov  3 17:31:41 ubuntu kernel: [19853.766910] QAT: Stopping all acceleration devices.
Nov  3 17:31:41 ubuntu kernel: [19854.093240] QAT: Stopping all acceleration devices.
Nov  3 17:33:10 ubuntu kernel: [19943.183459] QAT: Stopping all acceleration devices.
Nov  3 17:33:10 ubuntu kernel: [19943.495926] QAT: Stopping all acceleration devices.

```

at dmesg:
```
[   19.816010] kernel: usdm_drv: Loading USDM Module Version 0.7.1 ...
[   19.816011] kernel: usdm_drv: IOCTLs: c0507100, c0507101, 7102, c0047104
[   19.873774] kernel: QAT: Stopping all acceleration devices.

```

lsmod:
```
qat_c62xvf             16384  0
intel_qat             221184  2 usdm_drv,qat_c62xvf
uio                    20480  1 intel_qat
qat_contig_mem         16384  0
```

kernel: 5.4.0-47-generic

- kernel: 5.4.0-52-generic (I could not find usdm_drv at kernel available modules)

How can I enable or start QAT Acceleration Device(s)?
I am trying to compile QAT module for NGINX

**Comment by Yogaraj-Alamenda** [comment]
Hi @davidka79 
1. Are you trying to use QAT with virtualization ? If not please disable virtualization using "intel_iommu=off" in grub and install the driver.
2. Also There seems to issue loading drivers. Can you please have a look at this issue https://github.com/intel/QAT_Engine/issues/108 and blacklist the in-tree driver , reboot and reinstall the driver. If not done already.
3. If you still see the issue could you please share the build logs of QAT Driver. BTW what driver version you are using?

**Comment by davidka79** [comment]
Hello
Thank you for your response
I follow all steps, I have problem with kernel: 5.4.0-52-generic, while compiling QAT it gives me error  Compile Error usdm_drv.k incorrect format, So I switched back to kernel: 5.4.0-47-generic and compiled good.
But I still have There is 0 QAT acceleration device(s) in the system while drivers starts

I will share building log 

I have a question 
it is a supermicro server with C620 chipset, do I need to change anything in BIOS for QAT, probably switch off Hyperthreading or switch of Intel Virtualization Technology?

**Comment by Yogaraj-Alamenda** [comment]
Hi @davidka79 
There is no special settings needed in BIOS to enable QAT Devices. If you followed the steps 1 and 2 mentioned above correctly then you are good. Please share driver build logs along with dmesg logs  so that  we can check if there is any going wrong  with driver build

**Comment by davidka79** [comment]
[QAT_ENGINE.LOG](https://github.com/intel/QAT_Engine/files/5501428/QAT_ENGINE.LOG)

Hello
Thank you very much for response

I had deleted a ubuntu 20.04, install ubuntu 18.04 from the zero
did not install HWE kernel
and followed by instruction
and after make install of QAT Engine I got again  

```
This will take a few moments
Starting QAT service
Restarting all devices.
Checking status of all devices.
There is 0 QAT acceleration device(s) in the system:
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/QAT'
```
:( 
I add a compile log

**Comment by Yogaraj-Alamenda** [comment]
Hi @davidka79 Had a look on the QAT driver build log and there is no issue with build and hope there is no error message in the dmesg. Should be  Some environment issue,  Have you tried blackisting the intree driver as previously mentioned with the new OS?

**Comment by mythi** [comment]
@davidka79 

> it is a supermicro server with C620 chipset, do I need to change anything in BIOS for QAT

all c62x do not come with QAT. what's the output of `lspci -d 8086:37c8`

**Comment by davidka79** [comment]
> Hi @davidka79 Had a look on the QAT driver build log and there is no issue with build and hope there is no error message in the dmesg. Should be Some environment issue, Have you tried blackisting the intree driver as previously mentioned with the new OS?

I will try now, I tried with ubuntu 20.04 kernel: 5.4.0-47-generic but it did not help
As I downgraded to Ubuntu 18.04 with 4.15.0-122-generic I will try again blacklisting

**Comment by davidka79** [comment]
> @davidka79
> 
> > it is a supermicro server with C620 chipset, do I need to change anything in BIOS for QAT
> 
> all c62x do not come with QAT. what's the output of `lspci -d 8086:37c8`

Hello
I got empty response, does it means that I do not have QAT?

**Comment by mythi** [comment]
@davidka79 yes

here's my output:
```
 $ lspci -d 8086:37c8
4e:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
4f:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
50:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
```

**Comment by davidka79** [comment]
> @davidka79 yes
> 
> here's my output:
> 
> ```
>  $ lspci -d 8086:37c8
> 4e:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
> 4f:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
> 50:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
> ```

Thank you 
If we will order new servers, how could I recognize that c62x has a QAT? does it special name or revision of chipset?

**Comment by mythi** [comment]
> If we will order new servers, how could I recognize that c62x has a QAT? does it special name or revision of chipset?

I usually check: https://ark.intel.com/content/www/us/en/ark/products/series/98470/intel-c620-series-chipsets.html

I can see X11DPU is C621

**Comment by davidka79** [comment]
yes its written C621, but at lshw I got c620
according with your link we need to get from c625 and higher 
thank you very much
