### ISSUE TITLE
QAT function of 'Intel C627 chipset' only supports 'CPA_DC_CHAIN_HASH_THEN_COMPRESS'?

### ISSUE THREAD

**Issue by rekcah7** [intel/QAT_Engine#179]
Hello,
I am currently using Intel C627 chipset.

While testing with the CPA_BITMAP_BIT_TEST(bitmask, bit) function, it was confirmed that the values other than'CPA_DC_CHAIN_HASH_THEN_COMPRESS (5 )'are not supported by the Intel C627 chipset.

As a result of testing, the values not supported by Intel C627 chipset are as follows.
CPA_DC_CHAIN_COMPRESS_THEN_HASH ( 0 ),
CPA_DC_CHAIN_COMPRESS_THEN_ENCRYPT ( 1 ),
CPA_DC_CHAIN_COMPRESS_THEN_HASH_ENCRYPT ( 2 ),
CPA_DC_CHAIN_COMPRESS_THEN_ENCRYPT_HASH ( 3 ),
CPA_DC_CHAIN_COMPRESS_THEN_AEAD ( 4 ),
CPA_DC_CHAIN_HASH_VERIFY_THEN_DECOMPRESS ( 6 ),
CPA_DC_CHAIN_DECRYPT_THEN_DECOMPRESS ( 7 ),
CPA_DC_CHAIN_HASH_VERIFY_DECRYPT_THEN_DECOMPRESS ( 8 ),
CPA_DC_CHAIN_DECRYPT_HASH_VERIFY_THEN_DECOMPRESS ( 9 ),
CPA_DC_CHAIN_AEAD_THEN_DECOMPRESS ( 10 ),
CPA_DC_CHAIN_DECOMPRESS_THEN_HASH_VERIFY ( 11 ),
CPA_DC_CHAIN_COMPRESS_THEN_AEAD_THEN_HASH ( 12 )

The document'Intel® QuickAssist Technology Compression API Reference 2020' states that all CPA_DC_CHAIN modes are supported. But I don't know why it is not supported.

Also, unsupported values are set to'CPA_BITMAP_BIT_SET (bitmask, bit )'. 
However, the error message'[error] dcChainSession_CheckSessionData()-: Invalid API Param-Unsupported operation 0 or 1 or 2 or 3 or 4 or 5 or 6 or 7 or 8 or 9 or a or b or c' is displayed.

The QAT setting file for testing is as follows.
=====================================
[GENERAL]
ServicesEnabled = dc
ServicesProfile = COMPRESSION
ConfigVersion = 2

CyNumConcurrentSymRequests = 512
CyNumConcurrentAsymRequests = 64

statsGeneral = 1
statsDh = 1
statsDrbg = 1
statsDsa = 1
statsEcc = 1
statsKeyGen = 1
statsDc = 1
statsLn = 1
statsPrime = 1
statsRsa = 1
statsSym = 1
KptEnabled = 0

DcIntermediateBufferSizeInKB = 64
AutoResetOnError = 0

[SSL]
NumberCyInstances = 0
NumberDcInstances = 2
NumProcesses = 1
LimitDevAccess = 0

Cy0Name = "SSL0"
Cy0IsPolled = 1
Cy0CoreAffinity = 0

Cy1Name = "SSL1"
Cy1IsPolled = 1
Cy1CoreAffinity = 1

Cy2Name = "SSL2"
Cy2IsPolled = 1
Cy2CoreAffinity = 2

Cy3Name = "SSL3"
Cy3IsPolled = 1
Cy3CoreAffinity = 3

Cy4Name = "SSL4"
Cy4IsPolled = 1
Cy4CoreAffinity = 4

Cy5Name = "SSL5"
Cy5IsPolled = 1
Cy5CoreAffinity = 5

Dc0Name = "Dc0"
Dc0IsPolled = 1
Dc0CoreAffinity = 0

Dc1Name = "Dc1"
Dc1IsPolled = 1
Dc1CoreAffinity = 1
=====================================
[c6xx_dev0.zip](https://github.com/intel/QAT_Engine/files/6099389/c6xx_dev0.zip)

If you know how to fix it, please let me know. And is there any community site I can contact?

We are looking forward to your response.
Thank you.

**Comment by jdschuet** [comment]
Hello,

The current QAT driver  (as of 3/8/21 this is the 4.12.0) the only chaining combination that is supported is CPA_DC_CHAIN_HASH_THEN_COMPRESS,    The Data Compression API reference manual includes the current list of possible combinations.   We'd love to discuss your interest in chaining and which combinations are most interesting.
Thanks,
Joel
