### ISSUE TITLE
What is the ECDSA signature verification algorithm supported when only the QAT function is used?

### ISSUE THREAD

**Issue by rekcah7** [intel/QAT_Engine#180]
Hello
I have a QAT related question and I am posting.

I'm trying to use QAT's ECDSA signature verification feature. 
Does the QAT ECDS Signature Verification feature support all algorithms that meet SECG, ANSI and NIST standards?
(This is the case when using only the QAT function and not using other open platforms. ex. Openssl)

Or is it only supporting some features?
(This is the case when using only the QAT function and not using other open platforms. ex. Openssl)

**Comment by Yogaraj-Alamenda** [comment]
Not Sure I understand your query, QAT Engine using qat_hw supports all the curves that are in this [qat_hw Features](https://github.com/intel/QAT_Engine/blob/master/docs/features.md#qat_hw-features)
