### ISSUE TITLE
when I compile the QAT_Engine, I got the error: " /QAT/quickassist/lookaside/access_layer/include/icp_sal_user.h:51:10: fatal error: cpa_dc.h: No such file or directory"

### ISSUE THREAD

**Issue by gxkevin** [intel/QAT_Engine#186]
I have installed the QAT driver, and when I try to install the Engine, I got the error 
 
    ./autogen.sh 
    ./configure --with-qat_hw_dir=/QAT
    make
    
    In file included from e_qat.c:105:
    /QAT/quickassist/lookaside/access_layer/include/icp_sal_user.h:51:10: fatal error: cpa_dc.h: No such file or directory
    #include "cpa_dc.h"

**Comment by Yogaraj-Alamenda** [comment]
@gxkevin Could you please let us know what version of driver you are using?

**Comment by gxkevin** [comment]
> please
@Yogaraj-Alamenda 
the qat driver version is : QAT20.L.0.5.5-00033 ( I got the verstion from the intel support team), and the QAT_Engine version is 0.6.6

**Comment by Yogaraj-Alamenda** [comment]
@gxkevin There is some additional fix needed to support this version of driver which is to include 
`quickassist/include/dc` dir in configure.ac. Our support team can help you to get that fix.
