### ISSUE TITLE
Intel Gen 3 Platinum 8360Y

### ISSUE THREAD

**Issue by jimthedj65** [intel/QAT_Engine#188]
Hi All,

`

1. Operating system: Ubuntu 20.04.2 LTS
2. Kernel: 5.4.0-80-generic
3. Intel® Crypto Multi-buffer library from the ipp-crypto release version IPP Crypto 2021.3
4. Intel® Multi-Buffer crypto for IPsec Library release version v1.0
5. OpenSSL* 1.1.1k

`

My test platform is Intel 8360Y x 4 with AVX512 and cpuid all enabled.  I am using type 1 host passthrough for dedicated CPU and network cards.

I ran the step by step here [https://software.intel.com/content/www/us/en/develop/articles/building-software-acceleration-features-in-the-intel-qat-engine-for-openssl.html](url)

Adapting for newer versions, when I get to step 

`./autogen.sh LDFLAGS="-L/opt/ipsec-mb/v1.0/lib -L/opt/crypto_mb/2021.3/lib" CPPFLAGS="-I/opt/ipsec-mb/v1.0/include -I/opt/crypto_mb/2021.3/include" ./configure --prefix=/opt/openssl/1.1.1k --with-openssl_install_dir=/opt/openssl/1.1.1k --with-openssl_dir=$HOME/openssl-1.1.1k --enable-qat_sw`

I get an error on the compile in bold below

**autoreconf: running: automake --add-missing --copy --force-missing
**configure.ac:12: installing './compile'
configure.ac:9: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.**'**

I have searched across the forums and as this is compiling for the new Gen3 CPU, is there something else that requires to be installed?

any assistance is greatly appreciated.

**Comment by Yogaraj-Alamenda** [comment]
@jimthedj65  The Logs highlighted in bold are expected from autogen.sh which does autoreconf to generate autconf files like configure . Or did you see any errors from ./configure step ? Please share config.log and we should be able to figure out any issues with setup.

**Comment by jimthedj65** [comment]
@Yogaraj-Alamenda  thanks for the quick response,  ./configure steps seemed to go without any issues and error-free.  I have searched in my /var/log and various source directories and couldn't find a config.log where would this be normally located?

thanks

**Comment by Yogaraj-Alamenda** [comment]
If configure.ac runs fine then after make install the qatengine.so should be copied to /opt/openssl/1.1.1k/lib/engines-1.1/ .  Please check if the library is copied into that path. config.log is present in same directory where you run autogen.sh and configure.

If Libraries are copied you can run the tests mentioned [here](https://github.com/intel/QAT_Engine#test-the-intel-quickassist-technology-openssl-engine) to confirm build is fine

**Comment by jimthedj65** [comment]
Just to confirm the previous ./configure steps were for the other libraries.  

It does appear to be an issue with the QAT_Engine ./autogen.sh step? 
I looked in QAT_Engine dir where I run the ./autogen.sh step and there is no config.log, do I need to explicitly switch the log file?

I ran autogen separately and got the error and then ran configure as a second step and it appeared to complete ok but wouldn't complete the make step.

giving me the error 
`In file included from e_qat.c:86:
e_qat.h:61:12: fatal error: cpa.h: No such file or directory
   61 | #  include "cpa.h"
      |            ^~~~~~~
compilation terminated.`

hope it helps

**Comment by jimthedj65** [comment]
I refreshed my bash session and ran autogen.sh and ./configure.sh seperately and it foinally compiled and now I have a working QAT_Engine 

(qatengine) Reference implementation of QAT crypto engine(qat_sw) v0.6.7
 [RSA, id-aes128-GCM, id-aes192-GCM, id-aes256-GCM, X25519]
     [ available ]
     ENABLE_EXTERNAL_POLLING, POLL, ENABLE_HEURISTIC_POLLING,
     GET_NUM_REQUESTS_IN_FLIGHT, INIT_ENGINE
     
     
Weird error but seems ok now.
