### ISSUE TITLE
User Space DMA-able Memory (USDM) Component Missing in qat driver source code

### ISSUE THREAD

**Issue by wujingcqu** [intel/QAT_Engine#19]
Hi,
The QAT_Engine ReadMe says it is necessary to build a  contiguous pinned memory driver to get quickassist  working. The default qat_contig_mem kernel module is not stable enough.  

 The upstream driver is recommended according to ReadMe: "**The USDM component is located within the Upstream Intel® QuickAssist Technology Driver source code in the following subdirectory: quickassist/utilities/libusdm_drv**". 

But I cannot find the source code of this USDM component in the driver provided by 01.org.
I am not sure whether the software packages provided by 01.org is outdated.
Can anyone help with this issue?

King Regards.

William

**Comment by oldmikeyang** [comment]
The new code will be released soon.
