### ISSUE TITLE
Cannot find PCI device on Linux system

### ISSUE THREAD

**Issue by cody0704** [intel/QAT_Engine#190]
* OS: Redhat: 8.4
* Server: Dell R730
* Kernel: 4.18.0-305.12.1.el8_4.x86_64
* Device: Intel QAT 8970
  * Driver: Intel® QuickAssist Technology Driver for Linux* – HW Version 1.7 v4.14.0-00031

Ref: [https://01.org/sites/default/files/downloads/336211-015-qatsoftwareforlinux-rn-hwv1.7-final.pdf](https://01.org/sites/default/files/downloads/336211-015-qatsoftwareforlinux-rn-hwv1.7-final.pdf)

```bash
$ lspci | grep QAT
88:00.0 Co-processor: Intel Corporation DH895XCC Series QAT
```

Cannot find PCI device on my system

```bash
### 8970
$ lspci | grep QAT
```

After installing the driver

```
Checking status of all devices.
There is 3 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 0,  bsf: 0000:08:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 0,  bsf: 0000:09:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 0,  bsf: 0000:0a:00.0,  #accel: 5 #engines: 10 state: up
```

Still can't find

```bash
$ lspci | grep QAT
```

After unplugging the 8970, the following is empty
```
Checking status of all devices.
There is 0 QAT acceleration device(s) in the system:
```

The official documents are all about ntel QAT 8950, I don't know if I can provide some help here

Thanks

**Comment by mythi** [comment]
```
$ lspci | grep QAT
```

This command is not very good because it expects that `pci.ids` database has "QAT" for your device. It'd better to check it with your device's PCI ID directly:

```
$ lspci | grep QAT
$ lspci -d 8086:37c8
4e:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
4f:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
50:00.0 Co-processor: Intel Corporation C62x Chipset QuickAssist Technology (rev 04)
```
