### ISSUE TITLE
QAT Error: Failed to load config data to device

### ISSUE THREAD

**Issue by lulin2008** [intel/QAT_Engine#199]
nginx:

/etc/nginx/nginx.conf
worker_processes  16;

/etc/init.d/qat_service  restart
Restarting all devices.
Processing /etc/c6xx_dev0.conf
Processing /etc/c6xx_dev1.conf
Processing /etc/c6xx_dev2.conf

sed -i  '/NumProcesses/s/16/32/'   /etc/c6xx_dev*.conf
old :
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 16
LimitDevAccess = 1

new:
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 32
LimitDevAccess = 1

error:
/etc/init.d/qat_service  restart
Restarting all devices.
Processing /etc/c6xx_dev0.conf
Ioctl failed
QAT Error: Failed to load config data to device
Failed to configure qat_dev0
Processing /etc/c6xx_dev1.conf
Ioctl failed
QAT Error: Failed to load config data to device
Failed to configure qat_dev1
Processing /etc/c6xx_dev2.conf
Ioctl failed
QAT Error: Failed to load config data to device
Failed to configure qat_dev2

help me !

**Comment by Yogaraj-Alamenda** [comment]
Sorry for the delayed reply. It looks to me some configuration error. Can you please refer to the sample config files [here](https://github.com/intel/QAT_Engine/tree/master/qat/config/c6xx/multi_process_optimized) and see if there is anything incorrect or different. 

Able to bring up the config file with multiprocess 32 from the sample config file mentioned above.
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 32
LimitDevAccess = 1

**Comment by lulin2008** [comment]
> Sorry for the delayed reply. It looks to me some configuration error. Can you please refer to the sample config files [here](https://github.com/intel/QAT_Engine/tree/master/qat/config/c6xx/multi_process_optimized) and see if there is anything incorrect or different.
> 
> Able to bring up the config file with multiprocess 32 from the sample config file mentioned above. [SHIM] NumberCyInstances = 1 NumberDcInstances = 0 NumProcesses = 32 LimitDevAccess = 1

i used  [multi_process_event-driven_optimized](https://github.com/intel/QAT_Engine/blob/master/qat/config/c6xx/multi_process_event-driven_optimized/c6xx_dev0.conf),
when i change NumProcesses = 16 to NumProcesses = 32,  error!!

**Comment by lulin2008** [comment]
i used  this  [multi_process_optimized] (https://github.com/intel/QAT_Engine/tree/master/qat/config/c6xx/multi_process_optimized) conf, The problem was solved.
