### ISSUE TITLE
Enabling ciphers, PRF, and HKDF with openssl 3

### ISSUE THREAD

**Issue by nestorsamelo** [intel/QAT_Engine#208]
In configure.ac, cflags_openssl_3 is set to `-DQAT_OPENSSL_3 -DOPENSSL_SUPPRESS_DEPRECATED` when building against OpenSSL 3, but `-DENABLE_QAT_HW_CIPHERS`, `-DENABLE_QAT_HW_HKDF,` and `-DENABLE_QAT_HW_PRF` are not set if cflags_openssl_3 is not empty.

Is this the expected behavior?

In other words, how can I have a QAT engine that supports ciphers when building against OpenSSL 3?

**Comment by Yogaraj-Alamenda** [comment]
Yes. Ciphers, HKDF and PRF are disabled due to some issue with engine interface in OpenSSL3.0

**Comment by nestorsamelo** [comment]
@Yogaraj-Alamenda, understood.

Is this issue related to [openssl issue 17182](https://github.com/openssl/openssl/issues/17182)?

I assume the issue is also present with `--enable-qat_provider`.

**Comment by nestorsamelo** [comment]
This issue has been fixed in release 0.6.13.
