### ISSUE TITLE
There is 0 QAT acceleartion device(s) in the system

### ISSUE THREAD

**Issue by neuyilan** [intel/QAT_Engine#209]
Hi,
When I install the QAT driver, the following error occurred. 
![image](https://user-images.githubusercontent.com/6237070/180911684-b8493ea2-cbab-4276-a473-8cfc71a632fa.png)
I am sure the QAT card is installed, below figure may prove this.
![image](https://user-images.githubusercontent.com/6237070/180911798-c86db692-ab79-4e15-abce-9406cc5a9e45.png)
the `dmesg` command msg is as below:
![image](https://user-images.githubusercontent.com/6237070/180911858-5acae63b-7441-4290-9ba2-47f229be96bd.png)
I think maybe due to the QAT card is not compatibile with the QAT Driver.
I used the QAT.L.4.18.0-00008 driver download from this link[1].
The QAT card type version is 8970. （from the Intel Field Representative）

Thanks ahead.

[1] https://www.intel.com/content/www/us/en/download/19734/intel-quickassist-technology-driver-for-linux-hw-version-1-7.html

**Comment by neuyilan** [comment]
I found the same issue in https://github.com/intel/QAT_Engine/issues/173, and I have followed the steps in it, however, it can not solve my issue.

**Comment by neuyilan** [comment]
the cpu info as blow
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                80
On-line CPU(s) list:   0-79
Thread(s) per core:    2
Core(s) per socket:    20
座：                 2
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              85
型号名称：        Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
步进：              7
CPU MHz：             2500.000
BogoMIPS：            5000.00
虚拟化：           VT-x
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           1024K
L3 缓存：           28160K
NUMA 节点0 CPU：    0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78
NUMA 节点1 CPU：    1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch
_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe p
opcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexprio
rity ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_
llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
```

**Comment by neuyilan** [comment]
os version:
```
CentOS Linux release 7.8.2003 (Core)
```

**Comment by Yogaraj-Alamenda** [comment]
@neuyilan I will check internally with the driver team and comeback on this.

**Comment by neuyilan** [comment]
Hi, @Yogaraj-Alamenda thank you for your attention
I follow the https://github.com/intel/QAT_Engine/issues/76 issue, and after disabling the kernel driver, it worked.

Thanks a lot.
