### ISSUE TITLE
question about qat instance

### ISSUE THREAD

**Issue by limingllmm** [intel/QAT_Engine#21]
Hi
  I'm using openssl 1.1.0e + dh8920 to do https things.
  the application runs 1 process  4 threads + 4 logical instances, each thread use one specified logical instance, SSL connections are  dispatched to 4 threads evenly by clientHello packet
  ulimit -n 80000

  this week, I got one strange issue:
  To test the  application‘stability,  I use avalanche to generate 5300CPS https request，which almost reach the expected performance of dh8920 , the first 1 or 2 days, it works fine, the SSL connections on each threads is about 1500,  But 1 or 2 days later,  there's a peak(more than 80000) on one thread, which cause qat running out of its eventfd, and lead to failure.
   this happens 3 times this week.
   my question is: Is this normal when some instance/engine suddenly runs very slowly, OR anything may trigger this ?   I'm adding logic to push SSL connetions to other threads if some thread got too many handing.  I don't know if this will help,   and I still worried that if one instance/engine runs slow, the total performance may drop heavily some time.

**Comment by stevelinsell** [comment]
Hi @limingllmm this is not something I have encountered before.
When you say the instance/engine runs slowly do you mean it stops responding completely and quickly builds up a backlog on that instance or that it is slowly building up a backlog over time but is still processing requests on that instance?
Is there anything in the kernel log suggesting errors coming from the kernelspace driver?
What does the memory utilisation look like when the error appears? Is something leaking memory and eventually using all the system memory up for instance when the error occurs? Could memory be becoming fragmented over time and causing allocation issues?
Another thing to try is to configure the build with the --enable-qat_warnings option. This shouldn't result in loads of debug logging during normal running but you should get some output if things start to go wrong.

**Comment by limingllmm** [comment]
Hi, Steve
  Actually I don't know the engine stops completely or just work slowly， Because according to the unsuccessful transactions showed on avalanche， it seems that the one engine stopped almost one minute。
  after add logic to spread SSL connetions to other threads if some thread got too many handing. Since the application won't handle SSL connections more than max eventfds the system set,  it won't lead to unrecoverable failure  when the problem happens now.     I notice that the connections suddenly increase in about one day ，but a minute later，the connections goes down to normal status and the system works fine in next 2 days。 the engine recovers。。。
  the qat engine is built with warning option，but there's no log output ， also there's no kernel dmesg...

**Comment by limingllmm** [comment]
BTW， the application crashes after 3 days finally because of out-of-memory， it got 1.5GB memory free in the first 1 hour， but after 3 days， there's no page for openssl or qat engine to allocate(other module of my application  preallocate memory in the initial step)

**Comment by stevelinsell** [comment]
Hi @limingllmm,

Apologies for the slow response on this, I'm not quite sure where to go next with the slowness issue as it is not producing any errors in either the log output or the kernel dmesg. I will ask the team that works on the Intel Quickassist Driver if they have any ideas what could cause a particular engine to stop responding.

With regard to the memory error can you confirm whether after 3 days you are running out of general memory (i.e. standard mallocs are failing) or whether you are failing to allocate 128KB slabs of contiguous memory from qat_contig_mem? In otherwords I'm trying to ascertain whether you are suffering from a memory leak (the first case) or memory fragmentation (the second case).

Kind Regards,

Steve.

**Comment by limingllmm** [comment]
Hi， Steve
   Sorry for slow response, since I'm out for a long holiday :)  and then busy working on other things. 
   I've moved the application to a device with more memory.
  when run steady https connections (5000 CPS) with _avalanche_ , there's  a peak in 1 or 2 days, at that time , there's almost 100000 unsuccessful transactions and the memory use is increasing rapidly , after the connection peak goes down to normal, while the memory use seems not goes down . 
  when run https connections with _Apachebench_ like this "ab -c 1000 -n 9000000000 https://172.16.18.89/",  after 1 or 2 days, ab exit because of request timeout
  After switch openssl  engine from qat to default soft engine, it looks fine in 4 days

**Comment by stevelinsell** [comment]
Hi @limingllmm,

We will try and setup a test that it similar to your usage. Currently we do run stress tests but we only run them for 12 hours and are not seeing any issues. The problem you are seeing appears to take 1 or 2 days before it is seen. We'll try and setup a longer test perhaps for 4 or 5 days and see if we can recreate.

Kind Regards,

Steve.

**Comment by stevelinsell** [comment]
Closing issue as we were unable to recreate and do not have access to avalanche.
