### ISSUE TITLE
Software acceleration qustion

### ISSUE THREAD

**Issue by yfaker** [intel/QAT_Engine#226]
Hi, Does QAT_Engine support pure software-based acceleration of cryptographic operation when the host does not have the hardware of QAT card, and if so ,what are the software requirements?
thanks a lot

**Comment by Yogaraj-Alamenda** [comment]
@yfaker QAT Engine supports software based accceleration using AVX512 from [3rd Generation Intel® Xeon® Scalable Processors family](https://www.intel.com/content/www/us/en/products/docs/processors/xeon/3rd-gen-xeon-scalable-processors-brief.html). Please refer [qat_sw software requirements](https://github.com/intel/QAT_Engine/blob/master/docs/software_requirements.md#qat_sw-requirements) section for prerequesites and  Example 4  in [example builds ](https://github.com/intel/QAT_Engine#example-builds) for qatengine build

**Comment by yfaker** [comment]
Thanks a lot~
