### ISSUE TITLE
QAT_Engine Install 

### ISSUE THREAD

**Issue by jimthedj65** [intel/QAT_Engine#242]
Hi All,

I have installed QAT Engine successfully, followed the instructions here https://www.intel.com/content/www/us/en/developer/articles/guide/building-software-acceleration-features-in-the-intel-qat-engine-for-openssl.html

`cpuid -1 | egrep 'VAES|VPCLM|GFNI|AVX512F|AVX512IFMA'
      AVX512F: AVX-512 foundation instructions = true
      AVX512IFMA: fused multiply add           = true
      GFNI: Galois Field New Instructions      = true
      VAES instructions                        = true
      VPCLMULQDQ instruction                   = true`

running latest ipp_crypto and Multi-Buffer Crypto as of this post.

All running ok apart from one small issue when running 

**openssl engine -v qatengine**

my output is ok but with a bind error

`(qatengine) Reference implementation of QAT crypto engine(qat_sw) v1.0.0
     ENABLE_EXTERNAL_POLLING, POLL, ENABLE_HEURISTIC_POLLING,
     GET_NUM_REQUESTS_IN_FLIGHT, INIT_ENGINE, SW_ALGO_BITMAP
140594498721088:error:2506406A:DSO support routines:dlfcn_bind_func:could not bind to the requested symbol name:../crypto/dso/dso_dlfcn.c:188:symname(EVP_PKEY_get_base_id): /usr/lib/x86_64-linux-gnu/engines-1.1/qatengine.so: undefined symbol: EVP_PKEY_get_base_id
140594498721088:error:2506C06A:DSO support routines:DSO_bind_func:could not bind to the requested symbol name:../crypto/dso/dso_lib.c:186:`

Tried searching for a few hours to see if this was common, running latest software. Any pointers or suggestion warmly received.

**Comment by jimthedj65** [comment]
Additional debug info shows 

`openssl engine -c -t -vvv qat-hw
139779604305216:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/qat-hw.so): /usr/lib/x86_64-linux-gnu/engines-1.1/qat-hw.so: cannot open shared object file: No such file or directory
139779604305216:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:162:
139779604305216:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139779604305216:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:421:id=qat-hw`

**Comment by mythi** [comment]
> my output is ok but with a bind error

I believe it's this https://github.com/openssl/openssl/issues/17962

> Additional debug info shows

This is different: you are using `qat-hw` engine name which does not exist. How did you get `qat-hw`? qatengine` is the recommended build output because all SW do not support custom engine names (https://github.com/intel/asynch_mode_nginx/issues/55).

**Comment by jimthedj65** [comment]
### thanks for your response, I think the qat-hw maybe from old documentation. I picked it up from the testapp OpenSSL* Engine using testapp utility
