### ISSUE TITLE
QAT 2.0 on RHEL9.1 failing to start devices with "ioctl failed Get real id failed"

### ISSUE THREAD

**Issue by jlcassio** [intel/QAT_Engine#249]
I have downloaded and attempted to install QAT 2.0 driver on a Fox Creek Pass and there are 8 QAT devices enabled on my system.  When I install qat2020.1.1.0.20-00008.tar file and configure it with --enable-qat-lkcf, then use "make -j install"  it does not complete successfully, but I see errors and it reboots.  It will not start successfully but states an ioctle error "Invalid ioctl xxxxxx..." and fails.

**Comment by jlcassio** [comment]
realized I should not use the "-j" switch. used "make" then "make install" and it works now

**Comment by mythi** [comment]
On RHEL the driver is available part of the kernel so no need to install it separately
