### ISSUE TITLE
Which configuration file in directory qat_hw_config should I choose

### ISSUE THREAD

**Issue by ruishawn** [intel/QAT_Engine#288]
Dear maintainer，my hardware information：Intel(R) Xeon(R) Platinum 8480+.  Which profile should I choose.
I read the documentation（[Copy the Intel® QuickAssist Technology Driver config files for qat_hw
](https://github.com/intel/QAT_Engine#copy-the-intel-quickassist-technology-driver-config-files-for-qat_hw) ).The documentation is unclear and cannot help make a determination.Thanks!

**Comment by bjayanax** [comment]
Hi ruishawn,
For Intel(R) Xeon(R) Platinum 8480+ processor, use Qat2.0 driver with "[4xxx_dev0.conf](https://github.com/intel/QAT_Engine/blob/master/qat_hw_config/4xxx/multi_process/4xxx_dev0.conf)" config file.

**Comment by ruishawn** [comment]
> Hi ruishawn, For Intel(R) Xeon(R) Platinum 8480+ processor, use Qat2.0 driver with "[4xxx_dev0.conf](https://github.com/intel/QAT_Engine/blob/master/qat_hw_config/4xxx/multi_process/4xxx_dev0.conf)" config file.

Hi bjayanax, thank you.
Close issue.
