### ISSUE TITLE
nginx can not reload gracefully

### ISSUE THREAD

**Issue by Xuexiang825** [intel/QAT_Engine#29]
I modified  the nginx config , but can not reload gracefully .
I tried :nginx -s reload  /kill -HUP $(cat pid) ,nginx will report following errors : 
```
2017/07/18 15:25:21 [crit] 92260#0: *15 SSL_do_handshake() failed (SSL: error:8007F094:lib(128):qat_engine_init:icp sal userstart fail error:8008D044:lib(128):qat_prf_tls_derive:internal error) while SSL handshaking, client: 172.30.2.103, server: 0.0.0.0:443
[error] icp_sal_userStartMultiProcess() - : icp_adf_userProcessToStart failed

2017/07/18 15:25:22 [crit] 92260#0: *16 SSL_do_handshake() failed (SSL: error:8007F094:lib(128):qat_engine_init:icp sal userstart fail error:8008D044:lib(128):qat_prf_tls_derive:internal error) while SSL handshaking, client: 172.30.2.103, server: 0.0.0.0:443
[error] SalCtrl_ServiceEventInit() - : Failed to initialise all crypto instances
[error] SalCtrl_ServiceEventStart() - : Private data is NULL
[error] SalCtrl_ServiceEventInit() - : Failed to initialise all crypto instances
[error] SalCtrl_ServiceEventStart() - : Private data is NULL
[error] SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time

[error] do_userStart() - : Failed to start services

[error] SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time

[error] do_userStart() - : Failed to start services
```

**Comment by stevelinsell** [comment]
Hi @Xuexiang825,

I need a few more details to try and help you, please can you send on details of the following:

1) How many nginx worker processes are you starting?
2) The [SHIM] section of the driver config file you are using?
3) Which acceleration product you are using?

Kind Regards,

Steve.

**Comment by Xuexiang825** [comment]
@stevelinsell 
1.nginx work :3 ,version:nginx/1.10.3
2. SHIM section is : 
```
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 32
LimitDevAccess = 0
# Crypto - User space
Cy0Name = "UserCY0"
Cy0BankNumber = 2
Cy0IsPolled = 1
Cy0CoreAffinity = 1
Cy0NumConcurrentSymRequests = 512
Cy0NumConcurrentAsymRequests = 64
Cy0RingAsymTx = 0
Cy0RingAsymRx = 8
Cy0RingSymTx = 2
Cy0RingSymRx = 10
Cy0RingNrbgTx = 4
Cy0RingNrbgRx = 12
```
3.my device is : 
```
[root@test-ssl-10-231 servers]# /etc/init.d/qat_service status
There is 1 acceleration device(s) in the system:
 icp_dev0 - type=dh895xcc, inst_id=0, node_id=1,  bdf=85:00:0, #accel=6, #engines=12, state=up
```

**Comment by stevelinsell** [comment]
Hi @Xuexiang825,

That is very strange behaviour, if you are only using 3 nginx processes and have 32 processes defined in your config file, you should not be having any issues with the nginx -s reload.
Is everything working as expected before you attempt the nginx -s reload? i.e. no errors at normal startup?
Are there any errors in the dmesg output?

Can you also check there are not any other processes left running on the system that could be holding on to QAT instances, I have seen that cause this issue in the past.

Also does the issue persist across a reboot? It is worth checking in case something has left the QAT Driver in a funny state.
 
I notice you are using the old style QAT Driver configuration file format. This shouldn't be causing you an issue but I wonder if it would be beneficial to try the newer file format to rule that out. Is there a reason for using the old style, did you need more control of one particular aspect of the configuration?

Let me know the answers to the above,

Steve.

**Comment by InfoHunter** [comment]
I have also experienced this before. Some clues might be help for you to solve this problem. A 'nginx -s reload' will launch a new nginx process to send the 'reload' signal to the running nginx master process. And this new launched nginx process is not exiting as normal, but it still initialized QAT driver at startup. I don't dig into this deep but I this is the cause of the problem.  Another evidence is if you use something like 'kill -HUP <nginx master pid>' to kick nginx to reload, there is no such issue. The difference between '-s reload ' and 'kill -HUP' is if a new process of nginx has been launched or not. So I guess the new launched process (and then exits after sending a signal) is the guy who causes the problem.

Hope this helps.

发自我的 iPhone

**Comment by Xuexiang825** [comment]
@stevelinsell I am going to reinstall the QAT_driver ,you said my SHIM section is older ,which I download with nginx async patch package. Where can I find newer file ?

**Comment by stevelinsell** [comment]
Hi @Xuexiang825,

We supply example newer style driver config files within the QAT Engine github repo.
The one you would be looking to use with nginx which scales by creating multiple processes is located here:
https://github.com/01org/QAT_Engine/tree/master/qat/config/dh895xcc/multi_process_optimized
I wouldn't expect you to have to reinstall the QAT Driver as part of fixing this issue.

What @InfoHunter states is also relevant and correct. Do you also see the issue when you do kill -HUP or just when you do nginx -s reload? As he stated if you only see it with nginx -s reload then the process launched to send the signal is the one causing the issue.

A couple of other questions:
1) What version of QAT Driver package are you running with?
2) Are you using the openssl.cnf file to initialise the QAT Engine or are you using the 'engine qat' parameter in your nginx.conf file? 

Kind Regards,

Steve.

**Comment by Xuexiang825** [comment]
@stevelinsell 

1.QAT Driver is qatmux.l.2.6.0-60.tgz ,download from : https://01.org/sites/default/files/page/qatmux.l.2.6.0-60.tgz
2.my openssl.cnf 
```
openssl_conf = openssl_def
[openssl_def]
engines = engine_section
[engine_section]
qat = qat_section
[qat_section]
engine_id = qat
dynamic_path = /opt/xyz/ssl/lib/engines-1.1/qat.so
default_algorithms = RSA, EC, DH
SET_INTERNAL_POLL_INTERVAL = 1000000

```
and I added engine qat parameter in my nginx files

**Comment by Xuexiang825** [comment]
I  reinstall qat driver ,openssl and nginx with parameter rpath .
But I still have two issues:
1. I have to add : ssl_engine "qat"; in nginx.conf ,if not nginx can not unload ssl with qat engine
2.After I reboot server ,qat_config_mem mod missing ,I have to 
```
cd /QAT_Engine/qat_contig_mem
make
make load
make test
```

**Comment by Jayce** [comment]
Hi guys!

I have the same question.

* my **dh895xcc_qa_dev0.conf** is using https://github.com/01org/QAT_Engine/tree/master/qat/config/dh895xcc/multi_process_optimized
* nginx.conf and openssl.cnf are the same as @Xuexiang825

**Comment by Xuexiang825** [comment]
@Jayce I have use cavium ssl card

**Comment by Jayce** [comment]
@Xuexiang825 ,
I used that card too, it's good more than qat.

Can you tell me what is the version for kernel in your test for qat? My kernel version is **2.6.32-220**.

That could be a reason?

**Comment by Xuexiang825** [comment]
My kernel version is 3.10.0-514.21.1.el7.x86_64

**Comment by jdschuet** [comment]
Hi @Xuexiang825 
But I still have two issues:
1.I have to add : ssl_engine "qat"; in nginx.conf ,if not nginx can not unload ssl with qat engine

If ssl_engine  "qat" is not specified which issue do you observe when unloading ssl with qat engine?

2.After I reboot server ,qat_config_mem mod missing ,I have to
cd /QAT_Engine/qat_contig_mem
make
make load
make test

I agree that the qat_contig_mem driver is not installed persistently.  This is something you can do on your system so rebuilding the memory driver is not required on each reboot.  Based on your kernel version, you are running CentOS 7.. correct?  Here is link that describes process to make modules persistent.  https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Persistent_Module_Loading.html

**Comment by Xuexiang825** [comment]
@jdschuet If I don't specify the ssl_engine "qat" in nginx.conf ,nginx can unload ssl with qat engine

**Comment by jdschuet** [comment]
@Xuexiang825 - Which command are you using to unload ssl with qat_engine?

I have my openssl.cnf setup similar to what you described above.  In my nginx configuration file I do not have ssl_engine "qat" specified.  Through openssl s_time I can verify QAT is utilized by checking QAT firmware statistics before and after the openssl s_time request (/proc/icp_dh895xcc_dev0/qat).  When the tests were complete I was able to close nginx using this command:  kill -QUIT $(cat /usr/local/nginx/logs/nginx.pid)

Thanks,
Joel

**Comment by paulturx** [comment]
@Xuexiang825
Hi
As @stevelinsell suggested above (2.Are you using the openssl.cnf file to initialise the QAT Engine or are you using the 'engine qat' parameter in your nginx.conf file?), I would suggest either use openssl.cnf OR use the nginx.conf but not both at the same time.  Please let me know if that resolves your issue.  Also, to close nginx, have you tried './nginx -s stop' from the directory containing the nginx binary?
Regards,
Paul
