### ISSUE TITLE
qat-hw install failed

### ISSUE THREAD

**Issue by dream110fly** [intel/QAT_Engine#296]
hello，we use qat engine which verison is 0.6.18,  openssl 1.1.1s， qatzip 1.1.1， qat driver  QAT.L.4.15.0-00011.tar.gz， QAT card is Intel Corporation C62x Chipset QuickAssist Technology。 
use command /usr/local/openssl/bin/openssl engine -t -c -v qatengine， get error message as follows：

(qatengine) Reference implementation of QAT crypto engine(qat_hw) v0.6.18
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF, X25519, X448]
qaeOpenFd:818 Unable to update page properties
     ADF_UIO_PROXY err: adf_init_ring: unable to get ringbuf(v:(nil),p:(nil)) for rings in bank(1)
ADF_UIO_PROXY err: icp_adf_transCreateHandle: adf_init_ring failed
[error] SalCtrl_ServiceInit() - : Failed to initialise all service instances
ADF_UIO_PROXY err: adf_user_subsystemInit: Failed to initialise Subservice SAL
[error] SalCtrl_ServiceEventStart() - : Private data is NULL
ADF_UIO_PROXY err: adf_user_subsystemStart: Failed to start Subservice SAL
qaeOpenFd:818 Unable to update page properties
ADF_UIO_PROXY err: adf_init_ring: unable to get ringbuf(v:(nil),p:(nil)) for rings in bank(1)
ADF_UIO_PROXY err: icp_adf_transCreateHandle: adf_init_ring failed
[error] SalCtrl_ServiceInit() - : Failed to initialise all service instances
ADF_UIO_PROXY err: adf_user_subsystemInit: Failed to initialise Subservice SAL
[error] SalCtrl_ServiceEventStart() - : Private data is NULL
ADF_UIO_PROXY err: adf_user_subsystemStart: Failed to start Subservice SAL
qaeOpenFd:818 Unable to update page properties
ADF_UIO_PROXY err: adf_init_ring: unable to get ringbuf(v:(nil),p:(nil)) for rings in bank(1)
ADF_UIO_PROXY err: icp_adf_transCreateHandle: adf_init_ring failed
[error] SalCtrl_ServiceInit() - : Failed to initialise all service instances
ADF_UIO_PROXY err: adf_user_subsystemInit: Failed to initialise Subservice SAL
[error] SalCtrl_ServiceEventStart() - : Private data is NULL
ADF_UIO_PROXY err: adf_user_subsystemStart: Failed to start Subservice SAL
[error] SalCtrl_AdfServicesStartedCheck() - : Sal Ctrl failed to start in given time

[error] do_userStart() - : Failed to start services

ADF_UIO_PROXY err: icp_adf_subsystemUnregister: Failed to shutdown subservice SAL.
ADF_UIO_PROXY err: icp_adf_subsystemUnregister: Failed to shutdown subservice SAL.
ADF_UIO_PROXY err: icp_adf_subsystemUnregister: Failed to shutdown subservice SAL.
[ unavailable ]
     ENABLE_EXTERNAL_POLLING, POLL, SET_INSTANCE_FOR_THREAD, 
     GET_NUM_OP_RETRIES, SET_MAX_RETRY_COUNT, SET_INTERNAL_POLL_INTERVAL, 
     GET_EXTERNAL_POLLING_FD, ENABLE_EVENT_DRIVEN_POLLING_MODE, 
     GET_NUM_CRYPTO_INSTANCES, DISABLE_EVENT_DRIVEN_POLLING_MODE, 
     SET_EPOLL_TIMEOUT, SET_CRYPTO_SMALL_PACKET_OFFLOAD_THRESHOLD, 
     ENABLE_INLINE_POLLING, ENABLE_HEURISTIC_POLLING, 
     GET_NUM_REQUESTS_IN_FLIGHT, INIT_ENGINE, SET_CONFIGURATION_SECTION_NAME, 
     ENABLE_SW_FALLBACK, HEARTBEAT_POLL, DISABLE_QAT_OFFLOAD

how can we solve this problem？

**Comment by bjayanax** [comment]
Hi [dream110fly](https://github.com/dream110fly) Could you please go through the [troubleshooting section](https://github.com/intel/QAT_Engine#troubleshooting) in the README and see if the steps mentioned there helps. I think driver config section is not updated to SHIM.

Also, are you running with non-root user? If yes, please check the steps mentioned in programming guide section 3.14.
https://www.intel.com/content/www/us/en/content-details/710060/intel-quickassist-technology-software-for-linux-programmer-s-guide-customer-enabling-release.html

**Comment by dream110fly** [comment]
thank you, I willl try
