### ISSUE TITLE
Unable to disable sm2/sm3 while configuring QAT

### ISSUE THREAD

**Issue by pkoushik0** [intel/QAT_Engine#297]
We are trying to use QAT with openssl shared libs compiled without sm2/sm3 support and facing the following issues.

Command used to configure -   $ ./configure --with-qat_hw_dir="path-to-dir" --with-openssl_install_dir="path-to-dir" --with-cc-opt="-DQAT_HW_DISABLE_NONZERO_MEMFREE" --with-cc-opt="-DOPENSSL_NO_FIPS_SECURITYCHECKS" --enable-multi_thread --disable-qat_sw_sm2 --disable-qat_sw_sm3 --enable-qat_provider

The disable-qat_sw_sm2/sm3 flag specifies "This flag is valid only when QAT SW acceleration is enabled using the flag", we are not using -enable-qat_sw but still want to disable sm2/sm3.

Facing the below mentioned runtime issue when trying to load QAT provider.

$ ./openssl speed -provider libqat -elapsed -async_jobs 72 rsa2048
speed: unable to load provider libqat
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
40647BDA077F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/lib/qat/x86_64-linux-gnu/libqat.so): /lib/qat/x86_64-linux-gnu/libqat.so: undefined symbol: EVP_sm3
40647BDA077F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:152:
40647BDA077F0000:error:07880025:common libcrypto routines:provider_init:reason(524325):crypto/provider_core.c:904:name=libqat

We are using the following specified versions and components.
QAT driver version - qat1.7.l.4.14.0-000031
QAT Engine version - 0.6.14
Openssl version - 3.1.4

Can you please help us solve this issue ?

**Comment by bjayanax** [comment]
Hi [pkoushik0](https://github.com/pkoushik0)

Mentioned speed command is wrong. Need to provide qatprovider in place of libqat.
example command:
 ./openssl speed -provider qatprovider -elapsed -async_jobs 72 rsa2048

By default sm3 disabled, no need to provide "--disable-qat_sw_sm3" flag during configuration time.

**Comment by nitishroy84** [comment]
@bjayanax We are getting below run time error while loading QAT provider.

40647BDA077F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/lib/qat/x86_64-linux-gnu/libqat.so): **/lib/qat/x86_64-linux-gnu/libqat.so: undefined symbol: EVP_sm3**

**Comment by pkoushik0** [comment]
Hi @bjayanax , the provider is compiled with libqat as its name and hence we are using the speed command mentioned above. Using qatprovider by default also has the same issue.
sm3 does not seem to be disabled by default since we are getting undefined symbol for EVP_sm3 as mentioned above.


$. /openssl speed -provider qatprovider -elapsed -async_jobs 100 rsa2048
speed: unable to load provider qatprovider
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
801242E6F37F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/lib/qat/x86_64-linux-gnu/qatprovider.so): /lib/qat/x86_64-linux-gnu/qatprovider.so: undefined symbol: EVP_sm3
801242E6F37F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:152:
801242E6F37F0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto/provider_core.c:920:name=qatprovider

**Comment by nitishroy84** [comment]
@Yogaraj-Alamenda @bjayanax  Can you please confirm whether this is an issue with QAT_Enigne-0.6.14?

**Comment by bjayanax** [comment]
[nitishroy84](https://github.com/nitishroy84), [pkoushik0](https://github.com/pkoushik0) We checked from our end and not seeing any issue with Qatengine v0.6.14. 

Configuration used:
./configure --with-qat_hw_dir=/root/QAT.L.4.22.0-00001 --with-openssl_install_dir=/root/jaya/openssl_install --with-cc-opt=-DQAT_HW_DISABLE_NONZERO_MEMFREE --with-cc-opt=-DOPENSSL_NO_FIPS_SECURITYCHECKS --disable-qat_sw_sm2 --disable-qat_sw_sm3 --enable-qat_provider

Result output:
![image](https://github.com/intel/QAT_Engine/assets/96256276/c7f0a46b-1bc1-4f5f-bb21-f24c90b659fd)

This flag **--enable-qat_hw_multi_thread** needs to be enabled only when qat_contig_mem_driver is use. May I know the purpose of using this flag? 

**speed: unable to load provider qatprovider** indicates that OPENSSL_ENGINE path is not set properly. could you check environment path once?

**Comment by nitishroy84** [comment]
@bjayanax You have not gotten the error since OpenSSL-3.1.4 might be compiled with the "sm3" feature by default. In our use case, we don't have OpenSSL libs with the sm3 feature. The above error will pop up only if OpenSSL shared libs are compiled without "SM3/SM2".

**Comment by nitishroy84** [comment]
@bjayanax Regarding the below comment,
"speed: unable to load provider qatprovider indicates that OPENSSL_ENGINE path is not set properly. could you check environment path once?"

==> There is no issue with the environment. It is just a hint. QAT lib loading failed due to runtime symbol resolution error.OpenSSL speed executable gives a hint to check the environment variable unware of runtime load issue. Look at the below error while loading qat lib.

"801242E6F37F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/lib/qat/x86_64-linux-gnu/qatprovider.so): /lib/qat/x86_64-linux-gnu/qatprovider.so: undefined symbol: EVP_sm3"

**Comment by bjayanax** [comment]
[nitishroy84]( https://github.com/nitishroy84) After disabling SM2 and SM3 in the OpenSSL configuration able to reproduce the error.
 
Qategnine won't support OpenSSL libraries with algorithms disabled due to OpenSSL fallback mechanism(if any HW fails, it will fall back to OpenSSL).

May I know why you want to disable SM2 and SM3 on the OpenSSL side? Instead of disabling the OpenSSL side, you can restrict calling those functions from your application.

**Comment by pkoushik0** [comment]
Hi @bjayanax , Thanks for confirming.
Our first try was to see if it can be disabled from QAT since our shared libraries are available without sm2/sm3 as of now. 
We will try to see if enabling it there can be an option.
