### ISSUE TITLE
SHA3-512 not running in hardware?

### ISSUE THREAD

**Issue by alexjch** [intel/QAT_Engine#298]
My QAT_Engine build uses openssl 3.2 and hw support only. I was testing with following command:

`echo "Hello QAT" | openssl dgst -provider qatprovider -sha3-512
QAT_HW RSA for Provider Enabled
QAT_HW ECDSA for Provider Enabled
QAT_HW ECDH for Provider Enabled
QAT_HW DSA for Provider Enabled
QAT_HW DH for Provider Enabled
QAT_HW ECX25519 for Provider Enabled
QAT_HW ECX448 for Provider Enabled
QAT_HW PRF for Provider Enabled
SHA3-512(stdin)= 976993476d5b570d3fcd0300b9fa3d2b6bc7b1dc551ecfe96c8b20d0be7dcf663c4011990408a9db4536ab0983de2ee2b1e7b0139f2d4d4b7467e9ecd81063ab`

But the QAT `fw_counters` do not change, which leads me to believe that this operation is not running in QAT hardware. Is this correct? Is this running in software?

On the other hand the following command:

`openssl speed -provider qatprovider rsa2048`

Increases `fw_counters` quite a bit

**Comment by bjayanax** [comment]
[alexjch](https://github.com/alexjch) SHA3 disabled by default in Qategnine/Qatprovider. To enable SHA3 in qatengine need to enable flag "--enable-qat_hw_sha3" at configuration time.
Qatengine support for OpenSSL3.2 is in pipeline. We checked same with OpenSSL3.0.12 and not seeing any issues after enabling SHA3 flag.

**Comment by alexjch** [comment]
Thanks for que quick response
