### ISSUE TITLE
build as an OpenSSL built in

### ISSUE THREAD

**Issue by alexjch** [intel/QAT_Engine#300]
Is it possible to build QAT_Engine as part of OpenSSL? is there testing about how to do this? I would prefer to build it as part of OpenSSL instead of a loadable library.

**Comment by venkatesh6911** [comment]
Hi @alexjch ,  it is not possible to build QAT Engine as part of OpenSSL. QAT Engine needs to be build separately.

**Comment by bjayanax** [comment]
Hi [alexjch](https://github.com/alexjch)
As [venkatesh6911](https://github.com/venkatesh6911) said, Building QAT Engine as a part of OpenSSL is not possible.
