### ISSUE TITLE
QAT_Engine-1.5.0 with QAT.L.4.23.0-00001  fw_counter can not work？

### ISSUE THREAD

**Issue by lastpepole** [intel/QAT_Engine#307]
**openssl version**
/usr/local/openssl/bin/openssl version
OpenSSL 1.1.1w  11 Sep 2023

**openssl.cnf**
cat /usr/local/openssl/ssl/openssl.cnf
openssl_conf = openssl_def
[openssl_def]
engines = engine_section

[engine_section]
qatengine = qatengine_section

[qatengine_section]
engine_id = qatengine
dynamic_path = /usr/local/openssl/lib/engines-1.1/qatengine.so
default_algorithms = ALL

but,

 cat /sys/kernel/debug/qat_dh895xcc_0000\:60\:00.0/fw_counters is zero, not work.

**Comment by venkatesh6911** [comment]
Hi @lastpepole ,
Can you share the configure command you used to configure the QAT Engine.
Also would like to know what algorithm you are trying to offload via QAT ?

**Comment by lastpepole** [comment]
> Hi @lastpepole , Can you share the configure command you used to configure the QAT Engine. Also would like to know what algorithm you are trying to offload via QAT ?

Hi @venkatesh6911 ,
openssl.conf as below:

cat /usr/local/openssl/ssl/openssl.cnf
openssl_conf = openssl_def
[openssl_def]
engines = engine_section

[engine_section]
qatengine = qatengine_section

[qatengine_section]
engine_id = qatengine
dynamic_path = /usr/local/openssl/lib/engines-1.1/qatengine.so
default_algorithms = ALL

**Comment by venkatesh6911** [comment]
> > Hi @lastpepole , Can you share the configure command you used to configure the QAT Engine. Also would like to know what algorithm you are trying to offload via QAT ?
> 
> Hi @venkatesh6911 , openssl.conf as below:
> 
> cat /usr/local/openssl/ssl/openssl.cnf openssl_conf = openssl_def [openssl_def] engines = engine_section
> 
> [engine_section] qatengine = qatengine_section
> 
> [qatengine_section] engine_id = qatengine dynamic_path = /usr/local/openssl/lib/engines-1.1/qatengine.so default_algorithms = ALL

I meant the ./configure command in the QAT Engine.
./configure --with-qat_hw_dir=<path> --with-openssl_install_dir=<path>
