### ISSUE TITLE
Currently, does this support quic ssl offload? 

### ISSUE THREAD

**Issue by lastpepole** [intel/QAT_Engine#309]

**Comment by venkatesh6911** [comment]
Hi @lastpepole , experimental QUIC support is present via BoringSSL with Nginx-QUIC.
Refer https://github.com/intel/QAT_Engine/blob/master/docs/bssl_support.md for setting up BoringSSL with QATEngine.
You can download [Nginx-QUIC](https://cdrdv2.intel.com/v1/dl/getContent/737522) and follow README instructions to enable and offload via QUIC protocol.

**Comment by lastpepole** [comment]
@venkatesh6911 tested, don't offload ssl of quic protocol.
