### ISSUE TITLE
question about call QAT engine

### ISSUE THREAD

**Issue by skomen** [intel/QAT_Engine#31]
hi,
I have installed QAT driver & QAT engine，and  I can call QAT engine when I use openssl app.
Now , I want to call  QAT engine to speed encryption and decryption when  I call ssl in my program.
I have read some source code in openssl ,but didn‘t  find a  generic method.
I did not figure out whether to call the engine when use ssl.
I want to know how can I use QAT engine when I call ssl in my program?

Looking forward to your reply!
thanks!

**Comment by stevelinsell** [comment]
Hi,

Generally speaking you configure OpenSSL at library startup with any engines you want to use. You would would do this by configuring OpenSSL to use the engine as default for those operations. For instance you could set OpenSSL to use the QAT Engine just for all RSA operations, or you could set OpenSSL to use the QAT Engine as default for all the algorithms it supports. In both cases any other operations would be performed by the OpenSSL software implementation. 

There are two ways to configure OpenSSL at library startup:

1) Firstly you could edit the openssl.cnf file that is part of the OpenSSL install and add a section that configures the engine you want to use (QAT Engine). If you go down this route then every application that links to that version of OpenSSL will use the QAT Engine by default for the operations that have been configured in the openssl.cnf file. For more details on how to setup the openssl.cnf file please see the following section of the QAT Engine README.md: 
https://github.com/01org/QAT_Engine#using-the-openssl-configuration-file-to-loadinitialize-engines

2) The other way of setting up an application to use the QAT Engine is to do it programmatically from your application on an app by app basis. You would use the following functions to achieve this:
ENGINE_load_dynamic()
ENGINE_init()
ENGINE_set_default_*
An example of these functions in use is in the following example on the OpenSSL wiki:
https://wiki.openssl.org/index.php/File:EngineTester.c
It is also worth reading the relevent OpenSSL Manpages located at:
https://www.openssl.org/docs/man1.1.0/crypto/ENGINE_init.html
 
You should avoid using method 1 if you are going to use method 2 as there are issue with trying to use both methods at the same time within an application.
Please let me know if you have further queries,

Steve.

**Comment by skomen** [comment]
ok!Thank you
