### ISSUE TITLE
compile qat driver(QAT.L.4.24.0-00005.tar.gz) not successfully, error: invalid combination of opcode and operands

### ISSUE THREAD

**Issue by lastpepole** [intel/QAT_Engine#311]
qat driver download: https://www.intel.com/content/www/us/en/download/19734/intel-quickassist-technology-driver-for-linux-hw-version-1-x.html

failed to compile qat driver, error info:

make[4]: Entering directory `/tmp/qatdriver/quickassist/lookaside/access_layer/src/common/qat_comms'
Creating output directory
Creating output directory
crc32_gzip_refl_by8.S:318: error: invalid combination of opcode and operands
Creating output directory
ASM compilation failed, check nasm availability
ar: creating compression.a

@venkatesh6911 can you help me to solve this problem?

**Comment by venkatesh6911** [comment]
Hi @lastpepole , can you check nasm and other required packages are installed ? 
https://downloadmirror.intel.com/795697/README_QAT.L.4.24.0-00005.txt

**Comment by lastpepole** [comment]
> Hi @lastpepole , can you check nasm and other required packages are installed ? https://downloadmirror.intel.com/795697/README_QAT.L.4.24.0-00005.txt

@venkatesh6911 have installed. running ./configure command is right.

error info:
crc32_gzip_refl_by8.S:318: error: invalid combination of opcode and operands
ASM compilation failed, check nasm availability
ar: ar: creating device_info.acreating qat_comms.a

**Comment by venkatesh6911** [comment]
Can you share the OS and kernel version ?

**Comment by lastpepole** [comment]
os: centos7u5
kernel: 5.10
@venkatesh6911

**Comment by venkatesh6911** [comment]
Can you check with the latest release QAT.L.4.25.0-00001 ?
https://www.intel.com/content/www/us/en/download/19734/intel-quickassist-technology-driver-for-linux-hw-version-1-x.html

**Comment by lastpepole** [comment]
QAT.L.4.25.0-00001  is ok.
