### ISSUE TITLE
(qat) low performance in multi-thread  app

### ISSUE THREAD

**Issue by 13530654732** [intel/QAT_Engine#32]
i developed a multi-thread demo app which is almost the same with nginx 
app: 32 worker  threads   VS  nginx 32 worker process
app: worker handle accept4 and IO events  VS  nginx worker process handle accept4 and IO events (with accept_mutex off)

server information:
Xeon 2670(v2?)  X2
with dh8950 device

test deployment mode:
sprient testcenter ------https--------nginx/app

nginx with qat can run over 15000+ connections per second HTTPS(RSA2048+AES256-SHA1) requests  ( the whole cpu usage is less than 30%)

but when i switch to my app(with qat support),  my app can run only 7800 connections perf second HTTPS(RSA2048+AES256-SHA1) requests( the whole cpu usage is almost 100%)

I can find some offical metric statistics that looks pretty , but i guess those statistics are tests in multi-process enviroment.

i am wondering if my app's result is normal? or there is some metric data to compare with ?

or there is multi-thread demo like nginx(qat)  to follow ?

thanks

**Comment by stevelinsell** [comment]
Hi,

I don't have much experience of running multi-threaded applications asynchronously with Quickassist but I'll give you some suggestions on what I think could be causing your issue.

I'm assuming you are running with 1 thread per cpu core or something similar?
I also need to know how you have your Quickassist Driver config file setup in the [SHIM] section.
Are you declaring 1 crypto instance or multiple crypto instances?

I think the bottleneck you are experiencing might come down either to the polling for responses or to the send and receive buffers when offloading to the Quickassist accelerator.
Lets look at the differences between nginx and your application:
* When using a multi process application like nginx, each nginx process will have it's own crypto instance which includes it own set of ring buffers for sending and receiving data from the acceleration device, it also has it's own polling thread which will be checking for messages coming back from the accelerator.
* When running your multi threaded application there will be only as many crypto instances as you have declared in the driver config file. If this is 1 then there will only be 1 crypto instance to service all 32 threads that are pushing traffic. This will put pressure on the crypto instances ring buffers which will fill up much more quickly and limit your throughput. You'll also only have one polling thread which is servicing a very busy crypto instance.

My recommendation if you have not already is to increase the amount of crypto instances in the driver config file, probably to 4 to start with, possibly more if it is helping. Also as there will only be 1 polling thread (even when you increase the amount of crypto instances) I would try and keep a cpu core free for the polling thread to run on if possible. 

Currently we do not have an example multi threaded application demo or any metrics for that use case. It maybe something we look at in the future depending on demand for that configuration.

Let me know how you get on,

Steve.

**Comment by 13530654732** [comment]
@stevelinsell thanks for your reply.
my multi-threads app is developed to test QAT.  So i try to simpify all the other moduals except HTTPS basic operation。

0) threads? Yes, 1 worker per logical cpu. But no core affinity is set. I guest even if core affinity is set, there is not much benifit.

1) for https traffic。 my app got no decoding procedure, whenever my app receives a https request, it reply a HTTP 200 OK response and close the connection.

2) for recv/send buffer。 In my test case, recv/send buffer is fit for storing the coming https request and outgoing https response.  But there exists two native malloc/free operations when the https handshake is done. I think it should not be the bottleneck, so i ignore it

3) for QAT configration.
[SHIM]
NumberCyInstances = 64
NumberDcInstances = 0 
NumProcesses = 1 
LimitDevAccess = 0

# Crypto - User space
Cy0Name = "UserCY0"
Cy0IsPolled = 1
Cy0CoreAffinity = 0


# Crypto - User space
Cy1Name = "UserCY1"
Cy1IsPolled = 1
Cy1CoreAffinity = 0


# Crypto - User space
Cy2Name = "UserCY2"
Cy2IsPolled = 1
Cy2CoreAffinity = 0

# Crypto - User space
Cy3Name = "UserCY3"
Cy3IsPolled = 1
Cy3CoreAffinity = 0

# Crypto - User space
Cy4Name = "UserCY4"
Cy4IsPolled = 1
Cy4CoreAffinity = 0

# Crypto - User space
Cy5Name = "UserCY5"
Cy5IsPolled = 1
Cy5CoreAffinity = 0

# Crypto - User space
Cy6Name = "UserCY6"
Cy6IsPolled = 1
Cy6CoreAffinity = 0

# Crypto - User space
Cy7Name = "UserCY7"
Cy7IsPolled = 1
Cy7CoreAffinity = 0

...UserCY8~ UserCY63 configurations are not pasted here, they are almost the same.

4) the real bottleneck
i've got a perf top report when my multi-threads app is handling 7800 https cps while the whole system cpu usage stays at 100%.
It seems that the real bottleneck is mainly due to QAT kernel-space lock contentions and user-space  openssl lock contention
after i simplify the app modual, the result seems different. there is the my multi-thread app's result ( 7800 https cps)
here is my perf top report
             samples  pcnt function                        DSO
             _______ _____ _______________________________ _________________________

           314098.00 65.1% bn_sqr4x_mont                   /opt/data/fc/server      
            83468.00 17.3% bn_mul4x_mont_gather5           /opt/data/fc/server      
             6662.00  1.4% sha1_block_data_order_avx       /opt/data/fc/server      
             4133.00  0.9% md5_block_asm_data_order        /opt/data/fc/server      
             3154.00  0.7% _int_malloc                     /lib64/libc-2.15.so      
             3027.00  0.6% bn_sub_words                    /opt/data/fc/server      
             2704.00  0.6% _int_free                       /lib64/libc-2.15.so      
             2411.00  0.5% __malloc                        /lib64/libc-2.15.so      
             2274.00  0.5% BN_div                          /opt/data/fc/server      
             2061.00  0.4% bn_mul4x_mont                   /opt/data/fc/server      
             1967.00  0.4% bn_mul_words                    /opt/data/fc/server      
             1684.00  0.3% __GI_memset                     /lib64/libc-2.15.so      
             1448.00  0.3% do_raw_spin_lock                [kernel.kallsyms]        
             1284.00  0.3% BN_mod_exp_mont_consttime       /opt/data/fc/server      
             1233.00  0.3% BN_is_bit_set                   /opt/data/fc/server      
             1218.00  0.3% __memcpy_ssse3_back             /lib64/libc-2.15.so      
             1077.00  0.2% bn_mul_add_words                /opt/data/fc/server      
             1005.00  0.2% BN_lshift                       /opt/data/fc/server      
              890.00  0.2% __memmove_ssse3                 /lib64/libc-2.15.so      
              873.00  0.2% EVP_MD_CTX_cleanup              /opt/data/fc/server      
              810.00  0.2% bn_add_words                    /opt/data/fc/server      
              642.00  0.1% EVP_MD_CTX_copy_ex              /opt/data/fc/server      
              599.00  0.1% EVP_DigestUpdate                /opt/data/fc/server     

while nginx perf top report
            samples  pcnt function                           DSO
             _______ _____ __________________________________ ___________________________

             2182.00 25.0% do_raw_spin_lock                   [kernel.kallsyms]          
             1174.00 13.4% vfsmount_lock_global_lock_online   [kernel.kallsyms]          
              455.00  5.2% sha1_block_data_order_avx          /opt/data/fc/sbin/nginx_qat
              308.00  3.5% md5_block_asm_data_order           /opt/data/fc/sbin/nginx_qat
              288.00  3.3% _int_malloc                        /lib64/libc-2.15.so        
              137.00  1.6% _int_free                          /lib64/libc-2.15.so        
              135.00  1.5% __GI_memset                        /lib64/libc-2.15.so        
              122.00  1.4% __malloc                           /lib64/libc-2.15.so        
              119.00  1.4% __memcpy_ssse3_back                /lib64/libc-2.15.so        
              117.00  1.3% vfsmount_lock_local_lock           [kernel.kallsyms]          
              116.00  1.3% lh_retrieve                        /opt/data/fc/sbin/nginx_qat
               80.00  0.9% malloc_consolidate                 /lib64/libc-2.15.so        
               79.00  0.9% __memmove_ssse3                    /lib64/libc-2.15.so        
               77.00  0.9% OPENSSL_cleanse                    /opt/data/fc/sbin/nginx_qat
               76.00  0.9% CRYPTO_THREADID_cmp                /opt/data/fc/sbin/nginx_qat
               61.00  0.7% BN_bn2bin                          /opt/data/fc/sbin/nginx_qat
               59.00  0.7% tcp_recvmsg                        [kernel.kallsyms]          
               58.00  0.7% ssl3_accept                        /opt/data/fc/sbin/nginx_qat
               55.00  0.6% __pthread_mutex_unlock_usercnt     /lib64/libpthread-2.15.so  
               54.00  0.6% _raw_spin_lock_irqsave             [kernel.kallsyms]          
               53.00  0.6% CRYPTO_lock                        /opt/data/fc/sbin/nginx_qat
               49.00  0.6% mnt_get_count                      [kernel.kallsyms]          
               49.00  0.6% igb_free_rx_resources              [igb]                      
               47.00  0.5% osalAtomicSet                      /opt/data/fc/sbin/nginx_qat
               44.00  0.5% __pthread_mutex_lock_internal      /lib64/libpthread-2.15.so  
               43.00  0.5% ERR_clear_error                    /opt/data/fc/sbin/nginx_qat
               41.00  0.5% ssl3_read_bytes                    /opt/data/fc/sbin/nginx_qat
               41.00  0.5% qaeCryptoMemV2P                    /opt/data/fc/sbin/nginx_qat
               40.00  0.5% tcp_poll                           [kernel.kallsyms]            
              

5) Other tests
my multi-threads app also runs on i7-2600( 8 logical cores) server (3.4GHZ)
It seems that i7-2600 server can get a higher result

6) the multi-threads app is developed and  built against openssl-async(OpenSSL 1.0.1t  3 May 2016 - QAT package 0.4.11-054)
because the lower layer openssl and qat engine code are very different from the latest QAT release(v0.5.28, openssl1.1.0f). So i am trying to mirgrate my multi-threads app to latest release.
So far, my multi-threads app-v2 is suffering from random crash issue when the front presure comes to 6800 cps(https traffic). 
Although i can't upload a precise statistic, but the result seems almost the same level with openssl-async(OpenSSL 1.0.1t  3 May 2016 - QAT package 0.4.11-054)


thanks again

**Comment by stevelinsell** [comment]
Hi tk,

Interesting....
I didn't expect you to be declaring 64 logical crypto instances.
You most certainly are not running out of send and receive buffers!
In fact, although I don't think this is your biggest issue, you are probably declaring too many logical crypto instances. The polling thread is set to run every 10,000 nanoseconds by default and with your setup on each invocation it is going to have to call icp_sal_CyPollInstance() 64 times, once for each crypto instance. Most of the time those crypto instances will not have had any messages come back since the last poll.
I would recommend scaling back the crypto instances to around 8-16 at the most and seeing how that affects performance, you don't need a crypto instance for every thread.

Looking at your perf report for your multi threaded application I'm concerned that you seem to be doing an awfully large amount of Big Number Montgomery calculations that don't appear to be present in the nginx profile. This could be normal due to the Lenstra Vulnerability Workaround that involves doing an RSA Verify (in software) after every (Chinese Remainder Theorem based) RSA Sign to ensure it's integrity. I would suggest temporarily compiling with the --disable-qat_lenstra_protection (on the v0.5.28 QAT Engine) and see how that affects performance and the profile. This will then show whether those operations are coming from the RSA Verify or not. Note: if the profile was taken with 0.4.11-054 package rather than v0.5.28 then Lenstra protection was not present so the cause of the Big Number operations would be mysterious.

The flip side of that is that if the multi threaded app is doing Big Number operations because of the Lenstra protection then I don't really understand why the nginx profile is not also showing more Big Number calculations. In fact the profile fragment doesn't show any evidence of any RSA operations happening at all, SW or accelerated, perhaps they are just further down in the perf trace?
Can you also confirm that requests are definitely being offloaded to the accelerator by monitoring /proc/icp_dh895xcc_dev0/qat when running the nginx test. You should see the counters increasing if the offload is taking place. 
Is your nginx setup also using package 0.4.11-054? If so that could explain it as Lenstra protection was not present in that package.

Let me know if the crash you are seeing with v0.5.28 is due to anything in the QAT Engine, your use case is different to most, so you may uncover something we've missed.

Kind Regards,

Steve.

**Comment by 13530654732** [comment]
@stevelinsell 
1 thread vs 1 qat instance ? 
Because i couldn't find a multi-threads demo to guide my development, and i have tried shareing QAT instance between threads, but it crashes , so i setup 1 qat instance for each thread. it works fine
maybe the latest QAT release have solved this problem,  i will check it again. 
Now my multi-threads app is suffering from random crash, and it should be my coding problem, when i solve it ,i will let you know.

perf report ?
yes. both nginx and multi-threads app is build against QAT package 0.4.11-054 with static link mode.
Thanks for your help, i checked /proc/icp_dh895xcc_dev0/qat while my app was running, the counters didn't change at all.  It seem my app did not attach to QAT engine, need more debuging!
When nginx is running, the counters are increasing.

Thanks again.
I will check my app again with  QAT package 0.4.11-054. when i solve it, i will keep migrating my app with the latest QAT release.

**Comment by 13530654732** [comment]
Because our product is complex， so i simplify it to a multi-threads app to diagnose ssl performance problem.

**Comment by 13530654732** [comment]
i fixed that problem that my app doing ssl encryption/decryption totally in software mode , now it can attach to QAT engine, and the monitor data in /proc/icp_dh895xcc_dev0/qat keeps increasing while the app handling https requests.
and it shows that QAT engine exist low performance issue in multi-thread environment.

1) 
when cps is 7800. system cpu usage is about 50%
Tasks: 333 total,   2 running, 331 sleeping,   0 stopped,   0 zombie
Cpu(s): 12.9%us, 36.7%sy,  0.0%ni, 47.2%id,  0.0%wa,  0.0%hi,  3.1%si,  0.0%st
Mem:  132005760k total,  2398184k used, 129607576k free,    21768k buffers
Swap:        0k total,        0k used,        0k free,   523472k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                         
21761 root      20   0 2837m  55m 1960 S 1393  0.0 435:14.24 server3 

perf report

             samples  pcnt function                           DSO
             _______ _____ __________________________________ _________________________

            18206.00 45.7% do_raw_spin_lock                   [kernel.kallsyms]        
             2586.00  6.5% vfsmount_lock_global_lock_online   [kernel.kallsyms]        
              733.00  1.8% __pthread_mutex_lock_internal      /lib64/libpthread-2.15.so
              419.00  1.1% __pthread_mutex_unlock_usercnt     /lib64/libpthread-2.15.so
              410.00  1.0% _int_malloc                        /lib64/libc-2.15.so      
              353.00  0.9% sha1_block_data_order_avx          /opt/data/fc/server3     
              338.00  0.8% vfsmount_lock_local_lock           [kernel.kallsyms]        
              275.00  0.7% __GI_memset                        /lib64/libc-2.15.so      
              246.00  0.6% _int_free                          /lib64/libc-2.15.so      
              212.00  0.5% __malloc                           /lib64/libc-2.15.so      
              209.00  0.5% _raw_spin_lock_irqsave             [kernel.kallsyms]        
              205.00  0.5% qaeCryptoMemV2P                    /opt/data/fc/server3     
              202.00  0.5% update_curr                        [kernel.kallsyms]        
              198.00  0.5% __memcpy_ssse3_back                /lib64/libc-2.15.so      
              183.00  0.5% effective_load                     [kernel.kallsyms]        
              180.00  0.5% __lll_lock_wait                    /lib64/libpthread-2.15.so
              169.00  0.4% schedule                           [kernel.kallsyms]        
              160.00  0.4% mnt_get_count                      [kernel.kallsyms]        
              157.00  0.4% copy_user_generic_string           [kernel.kallsyms]        
              148.00  0.4% update_cfs_shares                  [kernel.kallsyms]        
              146.00  0.4% getrn                              /opt/data/fc/server3     
              142.00  0.4% userMemLookupByVirtAddr            /opt/data/fc/server3     
              127.00  0.3% lock_callback                      /opt/data/fc/server3     
              127.00  0.3% task_rq_lock                       [kernel.kallsyms]        
              127.00  0.3% vfsmount_lock_global_unlock_online [kernel.kallsyms]        
              125.00  0.3% futex_wake                         [kernel.kallsyms]        
              124.00  0.3% malloc_consolidate                 /lib64/libc-2.15.so      
              123.00  0.3% find_next_bit                      [kernel.kallsyms]        
              123.00  0.3% CRYPTO_lock                        /opt/data/fc/server3     
              121.00  0.3% BN_bn2bin                          /opt/data/fc/server3     
              116.00  0.3% __memmove_ssse3                    /lib64/libc-2.15.so      
              115.00  0.3% md5_block_asm_data_order           /opt/data/fc/server3     
              110.00  0.3% native_write_msr_safe              [kernel.kallsyms]        
              108.00  0.3% ssleay_rand_add                    /opt/data/fc/server3     
              104.00  0.3% kmem_cache_alloc                   [kernel.kallsyms]        
               97.00  0.2% resched_task                       [kernel.kallsyms]        
               97.00  0.2% ep_poll                            [kernel.kallsyms]        
               93.00  0.2% crypto_alloc_from_slab             /opt/data/fc/server3     
               88.00  0.2% ep_send_events_proc                [kernel.kallsyms]        
               85.00  0.2% ssl3_accept                        /opt/data/fc/server3     
               84.00  0.2% __cfree                            /lib64/libc-2.15.so      
               84.00  0.2% update_rq_clock                    [kernel.kallsyms]        
               83.00  0.2% select_task_rq_fair                [kernel.kallsyms]        
               81.00  0.2% cpumask_next                       [kernel.kallsyms]        
               80.00  0.2% ssl3_get_record_inner              /opt/data/fc/server3     
               77.00  0.2% ERR_clear_error                    /opt/data/fc/server3     
               76.00  0.2% igb_vlvf_set                       [igb]                    
               74.00  0.2% EVP_DigestInit_ex                  /opt/data/fc/server3     
               72.00  0.2% do_ssl3_write_inner                /opt/data/fc/server3     
               66.00  0.2% igb_free_rx_resources              [igb]                    
               65.00  0.2% futex_wait                         [kernel.kallsyms]        
               65.00  0.2% system_call                        [kernel.kallsyms]        
               60.00  0.2% atomic_dec_and_test                [kernel.kallsyms]        
               60.00  0.2% ngx_rbtree_insert_timer_value      /opt/data/fc/server3     
               59.00  0.1% source_load                        [kernel.kallsyms]        
               59.00  0.1% hash_futex                         [kernel.kallsyms]        
               59.00  0.1% futex_wait_setup                   [kernel.kallsyms]        
               59.00  0.1% set_tsk_need_resched               [kernel.kallsyms]        
               58.00  0.1% SHA1_Update                        /opt/data/fc/server3 
               
>>it seems that my server3 can handle more https request.  so i slowly increase front presure to 8000 and 8400 cps
8000 cps seems normal, but when cps comes to 8400, the system load jumps to 100% rapidly

2) 
top - 11:38:26 up 5 days, 18:51,  3 users,  load average: 22.15, 25.33, 21.91
Tasks: 340 total,   3 running, 337 sleeping,   0 stopped,   0 zombie
Cpu(s): 13.5%us, 77.2%sy,  0.0%ni,  6.9%id,  0.0%wa,  0.0%hi,  2.3%si,  0.0%st
Mem:  132005760k total,  2395988k used, 129609772k free,    22884k buffers
Swap:        0k total,        0k used,        0k free,   524612k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                         
21761 root      20   0 2837m  62m 1960 S 2970  0.0 483:24.36 server3  

perf report

             samples  pcnt function                       DSO
             _______ _____ ______________________________ _________________________

           120249.00 74.6% do_raw_spin_lock               [kernel.kallsyms]        
             1772.00  1.1% __pthread_mutex_lock_internal  /lib64/libpthread-2.15.so
             1037.00  0.6% __pthread_mutex_unlock_usercnt /lib64/libpthread-2.15.so
              909.00  0.6% _int_malloc                    /lib64/libc-2.15.so      
              822.00  0.5% sha1_block_data_order_avx      /opt/data/fc/server3     
              626.00  0.4% __GI_memset                    /lib64/libc-2.15.so      
              569.00  0.4% __lll_lock_wait                /lib64/libpthread-2.15.so
              542.00  0.3% sock_alloc_file                [kernel.kallsyms]        
              481.00  0.3% copy_user_generic_string       [kernel.kallsyms]        
              479.00  0.3% _int_free                      /lib64/libc-2.15.so      
              450.00  0.3% userMemLookupByVirtAddr        /opt/data/fc/server3     
              436.00  0.3% __memcpy_ssse3_back            /lib64/libc-2.15.so      
              428.00  0.3% qaeCryptoMemV2P                /opt/data/fc/server3     
              398.00  0.2% __malloc                       /lib64/libc-2.15.so      
              390.00  0.2% getrn                          /opt/data/fc/server3     
              373.00  0.2% CRYPTO_lock                    /opt/data/fc/server3     
              350.00  0.2% inode_init_always              [kernel.kallsyms]        
              341.00  0.2% futex_wake                     [kernel.kallsyms]        
              327.00  0.2% evict                          [kernel.kallsyms]        
              320.00  0.2% inode_sb_list_add              [kernel.kallsyms]        
              319.00  0.2% fget_light                     [kernel.kallsyms]        
              301.00  0.2% atomic_long_dec_and_test       [kernel.kallsyms]        
              284.00  0.2% ssleay_rand_add                /opt/data/fc/server3     
              284.00  0.2% ep_send_events_proc            [kernel.kallsyms]        
              283.00  0.2% __memmove_ssse3                /lib64/libc-2.15.so      
              278.00  0.2% lock_callback                  /opt/data/fc/server3     
              275.00  0.2% update_curr                    [kernel.kallsyms]        
              274.00  0.2% malloc_consolidate             /lib64/libc-2.15.so      
              272.00  0.2% effective_load                 [kernel.kallsyms]        
              247.00  0.2% kmem_cache_alloc               [kernel.kallsyms]        
              243.00  0.2% BN_bn2bin                      /opt/data/fc/server3     
              238.00  0.1% task_rq_lock                   [kernel.kallsyms]        
              228.00  0.1% igb_vlvf_set                   [igb]                    
              216.00  0.1% system_call                    [kernel.kallsyms]        
              209.00  0.1% crypto_alloc_from_slab         /opt/data/fc/server3     
              208.00  0.1% futex_wait                     [kernel.kallsyms]        
              203.00  0.1% schedule                       [kernel.kallsyms]        
              203.00  0.1% atomic64_add_unless.clone.12   [kernel.kallsyms]        
              201.00  0.1% md5_block_asm_data_order       /opt/data/fc/server3     
              193.00  0.1% futex_wait_setup               [kernel.kallsyms]        
              185.00  0.1% hash_futex                     [kernel.kallsyms]        
              185.00  0.1% ssl3_accept                    /opt/data/fc/server3     
              183.00  0.1% _raw_spin_lock_irqsave         [kernel.kallsyms]        
              182.00  0.1% ERR_clear_error                /opt/data/fc/server3     
              179.00  0.1% igb_free_rx_resources          [igb]                    
              172.00  0.1% update_cfs_shares              [kernel.kallsyms]        
              171.00  0.1% __cfree                        /lib64/libc-2.15.so      
              168.00  0.1% system_call_after_swapgs       [kernel.kallsyms]        
              167.00  0.1% ssl3_get_record_inner          /opt/data/fc/server3     
              166.00  0.1% sys_futex                      [kernel.kallsyms]        
              166.00  0.1% do_ssl3_write_inner            /opt/data/fc/server3     
              162.00  0.1% __call_rcu                     [kernel.kallsyms]        
              160.00  0.1% EVP_DigestInit_ex              /opt/data/fc/server3     
              159.00  0.1% ipt_do_table                   [kernel.kallsyms]        
              155.00  0.1% ngx_rbtree_insert_timer_value  /opt/data/fc/server3     
              154.00  0.1% get_futex_key                  [kernel.kallsyms]        
              142.00  0.1% _raw_spin_lock                 [kernel.kallsyms]        
              138.00  0.1% _atomic_dec_and_lock           [kernel.kallsyms]        
              136.00  0.1% SHA1_Update                    /opt/data/fc/server3

**Comment by stevelinsell** [comment]
Hi,

I can see from your profiles that you're getting hit very hard by locking. I assume as they are pthread_mutex_lock/unlock they are probably related to locks in qae_mem_utils.c when performing operations related to pinned contiguous memory allocations?
If so have you looked at the multi_thread_qaememutils.c file included with the engine? This file tries to reduce the locking by using thread local storage for slab lists so there is no need to lock between threads. There are some restrictions on using it, it would depend how your app deals with crypto as you cannot allocate and free memory from different threads. You may also see an increase in overall memory usage due to the fact that each thread does not share slabs.
To use the multi_thread_qaememutils.c instead of qae_mem_utils.c you should export an environment variable before compiling as follows:

  `export MULTI_THREAD_MEMUTILS=1`

Let me know if this has any effect,

Steve.

**Comment by 13530654732** [comment]
@stevelinsell 
thanks for your reply.

you metioned that i should use multi-thread-qaememutils instead of qae_mem_utils, yes i did.
If i use qae_mem_utils.c , the multi-threads app crashs. So i have to use multi_thread_qaememutils.c

i both export a global var  export MULTI_THREAD_MEMUTILS=/home/fc/openssl-asynch//engines/qat_engine
and add a global MACRO declaration -DMULTI_THREAD_MEMUTILS when compiling openssl-asynch, it compile qae_mem_utils.c into openssl-async

and i have compiled a -g3 debug version of my app, including libcrypto/libssl/server3. 
i did debugging server3 and checking the thread local memory pool allocation, it works.

from the perf report, i can see top 3 hotspot
1) kernel space lock/unlock---------i guess it should be due to QAT engine driver
2) user space mutex lock/unlock-----i guess it should be on openssl and qat engine user code
3) openssl malloc/free
i cann't find a way to optimize all these 3 hotspot

thanks again!

**Comment by stevelinsell** [comment]
Hi @13530654732,

Any chance you can capture some perf profiles with the -g (call-graph) option to shed some light on what is calling the locking functions?
The kernel space locking maybe from contention between threads when accessing the driver for things like submission or polling perhaps but I can't explain why it increases so much when you stress it more. Perhaps it is down to retries, the call-graphs should give more insight.

Kind Regards,

Steve.

**Comment by 13530654732** [comment]
[1.zip.txt](https://github.com/01org/QAT_Engine/files/1323203/1.zip.txt)

please rename 1.zip.txt to 1.zip, and unzip it
It is a txt output from binary perf report data file.

**Comment by stevelinsell** [comment]
Thankyou @13530654732, 

I've had a look at the profile containing the call graphs. It appears to show that the majority of the contention is happening from two areas of code:
1) The OpenSSL Error Stack. All accesses to the Error Stack use CRYPTO_lock.
2) The ENGINE subsystem uses a lot of locking when determining whether there is an engine that supports the operation that is about to be performed.

The QAT Engine itself and the asynchronous code within OpenSSL appear to only be responsible for a small percentage of the contention. 

I'm not sure that helps you a lot.
Something to check is whether you are certain all your crypto operations are succeeding. You are likely to see much more contention with the OpenSSL error stack for instance if you have crypto operations that are failing causing errors to be pushed to the stack and then later errors will need pulling off.

Kind Regards,

Steve.

**Comment by 13530654732** [comment]
@stevelinsell 

> Something to check is whether you are certain all your crypto operations are succeeding. You are likely to see much more contention with the OpenSSL error stack for instance if you have crypto operations that are failing causing errors to be pushed to the stack and then later errors will need pulling off.

actually i checked the transactions, the Sprient testcenter reported that all transactions were normal ( when it gives a presure of 7800/8000/8200)

**Comment by 13530654732** [comment]
i modified my multi-thread app to multi-process, and this t ime , the CPS goes very high,  almost the same with nginx.

1 thread per process, 4 processes can handle 12000 cps ( the system load is low, cpu usage is about 10%)

thus 1 thread can handle 3000 cps

**Comment by stevelinsell** [comment]
Closing this for now as we do not have a test environment where we have been able to reproduce this issue.
If it can be reproduced without the need for a sprient testcenter then we can revisit.
