### ISSUE TITLE
my cpu support the QuickAssist Software Acceleration,what can i do to use it.

### ISSUE THREAD

**Issue by yangni2017** [intel/QAT_Engine#324]
my cpu is "INTEL(R) XEON(R) GOLD 6530", i see it can support "QuickAssist Software Acceleration" in intel official site.
![image](https://github.com/user-attachments/assets/7a9aa9d4-927a-4d74-9721-0010656d2080)

but i can't see the qat device when i exec lspci，Do I need to insert another pci accelerator card? Or i need to do other things to enable it?
![image](https://github.com/user-attachments/assets/685d60d5-eec4-4245-8fca-6f4bc4ffd49e)

my cpu info as fllow:
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  128
  On-line CPU(s) list:   0-127
Vendor ID:               GenuineIntel
  BIOS Vendor ID:        Intel(R) Corporation
  Model name:            INTEL(R) XEON(R) GOLD 6530
    BIOS Model name:     INTEL(R) XEON(R) GOLD 6530
    CPU family:          6
    Model:               207
    Thread(s) per core:  2
    Core(s) per socket:  32
    Socket(s):           2
    Stepping:            2
    CPU max MHz:         4000.0000
    CPU min MHz:         800.0000
    BogoMIPS:            4200.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch
                         _perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca s
                         se4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mb
                         a ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx sm
                         ap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 wbno
                         invd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx5
                         12_vpopcntdq la57 rdpid cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr flush_l1d arch_capabilities
Virtualization features:
  Virtualization:        VT-x
Caches (sum of all):
  L1d:                   3 MiB (64 instances)
  L1i:                   2 MiB (64 instances)
  L2:                    128 MiB (64 instances)
  L3:                    320 MiB (2 instances)
NUMA:
  NUMA node(s):          2
  NUMA node0 CPU(s):     0-31,64-95
  NUMA node1 CPU(s):     32-63,96-127
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Vulnerable: eIBRS with unprivileged eBPF
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by yangni2017** [comment]
Does the cpu chipset also need to plug in the accelerator card related chips？

**Comment by yangni2017** [comment]
Now i exec "dmesg | grep Intel",i get the card
![image](https://github.com/user-attachments/assets/391d45e3-1c18-41e2-846e-06ae4c322ec1)

but when i install driver, i get the error:
```
modprobe: ERROR: could not insert 'usdm_drv': Exec format error
Restarting all devices.
Can not open /dev/qat_adf_ctl
Checking status of all devices.
Can not open /dev/qat_adf_ctl

        *** Error:usdm_drv module not installed ***

```

/var/log/messages export:
```
 kernel: [ 4377.429491] intel_qat: disagrees about version of symbol module_layout
```

**Comment by Kewei-Lu** [comment]
> 6530

while waiting for the repo owner to answer officially. After taking a glance, I guess 6530 does not support QAT hardware. In your screenshot of 6530 spec, it is "Software Acceleration" which I guess is related to "qat_engine sw_mode", but not `hw_mode`.

You can use `lspci -d :4940` or `lspci -d :4942` to check whether you have hardware embedded in your CPU.

Again this is not an official answer.

**Comment by yangni2017** [comment]
> QuickAssist Software Acceleration

sorry, i didn't notice it was software acceleration. So does software acceleration need to install drivers?
lspci -d :4940 or lspci -d :4942 both print empty.

**Comment by Kewei-Lu** [comment]
> > QuickAssist Software Acceleration
> 
> sorry, i didn't notice it was software acceleration. So does software acceleration need to install drivers? lspci -d :4940 or lspci -d :4942 both print empty.

I do not think you need driver installed for SW acceleration.

empty means no QAT hardware is available

**Comment by venkatesh6911** [comment]
Hi @yangni2017 ,for QAT Software acceleration, you can look at  https://github.com/intel/QAT_Engine/blob/master/docs/qat_sw.md 
If the system pre-requisites are met, you can follow instructions from https://github.com/intel/QAT_Engine/blob/master/docs/software_requirements.md#qat_sw-libraries to setup QAT Software acceleration libraries.

**Comment by yangni2017** [comment]
> Hi @yangni2017 ,for QAT Software acceleration, you can look at https://github.com/intel/QAT_Engine/blob/master/docs/qat_sw.md If the system pre-requisites are met, you can follow instructions from https://github.com/intel/QAT_Engine/blob/master/docs/software_requirements.md#qat_sw-libraries to setup QAT Software acceleration libraries.

ok.thanks a lot.
