### ISSUE TITLE
Can not start up QuickAssist adapter on CentOS 7

### ISSUE THREAD

**Issue by jiavictor** [intel/QAT_Engine#41]
Dear Team,
I apologize I am not sure I should send the issue here.
But I tried to sent on https://communities.intel.com/community/tech/wired/content and I can not find a catalog on 01.org. So I sent the issue https://01.org/forum/general-discussion/can-not-start-quickassist-adapter-centos-7 and here.

I am testing QuickAssist for SSL usage.
I have a QuickAssist 8950 adapter and installed on Dell R630.
I followed this document for installation:
https://01.org/sites/default/files/page/330750-005_qat_gsg.pdf
I added intel_iommu=off on GRUB2 and restart the server and the QAT driver installed without error.
But when comes to systemctl start qat_service, it reported can not start up the adapter and reported the error messages.
(For my network issue, I can not upload the images.)

So could you help me? Many thanks.

**Comment by stevelinsell** [comment]
Hi @jiavictor,

Can I ask you for a few more details to get a better idea of your configuration:

1) Can I assume you are running CentOS 7.1? If so which kernel version are you running with?
2) From your screenshots on 01.org I think you are running as a non-root user and using sudo to run commands with root privileges. Can you confirm that the QAT driver was installed when running with root privileges? I would also advise that you take a look at the following section of the programmers guide if you intend to run applications as non-root users:
Document Number 330751, chapter 4.16 - Running Applications as Non-Root User - https://01.org/sites/default/files/page/330751-006_clc_pg.pdf
3) From your link to documents I assume you are trying to use QAT Driver L.2.6.0-60, can you confirm that is the case?
4) Is there a file called InstallerLog.txt in the directory where you started the QAT Driver install from? If so does it show any errors?
5) When you run 'systemctl start qat_service' is there anything that appears in the kernel log (dmesg)?
6) I'm assuming that if you are running with CentOS 7.1 you are running with quite an old kernel. Do you have a business need to run with on older Linux Kernel? The QAT Driver L.2.6.0-60 does not function on newer kernel versions. If you need to or can run a more recent kernel then I would advise looking at the newer 1.7 version of the QAT Driver which is compatible with the QuickAssist 8950 adapter. The current software release is L.1.0.3-42 and is available in the QuickAssist section on the 01.org site. 

Let me know your answers and I'll try and help,

Steve.

**Comment by jiavictor** [comment]
Hi @stevelinsell 
Thanks for your help.

1. I am using CentOS 7 1708 (7.4) and the kernel is 3.10.0-693.el7.x86_64
2. I used root user to compile and install the driver
3. Yes, I am using L.2.6.0-60
4. I attached the file
5. I also attached the output of dmesg
6. No, we can use the newer kernel. But when I using L.1.0.3-42, the qat_service even says there is 0 acceleration device with the same configuration

If you need more information, please let me know.

Thanks.
[dmesg.log](https://github.com/intel/QAT_Engine/files/1469822/dmesg.log)
[InstallerLog.txt](https://github.com/intel/QAT_Engine/files/1469823/InstallerLog.txt)

**Comment by stevelinsell** [comment]
Hi @jiavictor,

I think you seem to be having an issue with the kernel QAT Driver that comes included with your CentOS distribution. When you install the QAT Driver 1.6 L.2.6.0-60 (userspace library and kernel driver) it will try and disable the kernel QAT Driver that is part of your distribution and insert it's own. Unfortunately your kernel QAT Driver seems to be giving errors during OS startup and then doesn't respond when it is attempted to be unloaded by the installer. My recommendation in the first instance is to try blacklisting the kernel QAT driver, reboot, and try the QAT Driver install again.
The commands I think you need to do the blacklisting on CentOS are as follows but it does vary by Linux distribution:

```
echo "blacklist intel_qat" > /etc/modprobe.d/blacklist-intel_qat.conf
echo "blacklist qat_dh895xcc" > /etc/modprobe.d/blacklist-qat_dh895xcc.conf
```
Let me know how you get on trying that. If it still doesn't work it would be useful to send the InstallerLog.txt of the revised attempt (or the last part of it) to see if it got any further.

Kind Regards,

Steve.

**Comment by jiavictor** [comment]
Hi @stevelinsell 
I had blacklisted intel_qat and qat_dh895xcc and re-installed the QAT driver, but without luck.
The device still can not startup.
Here are the installation log and dmesg.

Many thanks~
[InstallerLog.txt](https://github.com/intel/QAT_Engine/files/1473843/InstallerLog.txt)
[dmesg.log](https://github.com/intel/QAT_Engine/files/1473847/dmesg.log)

**Comment by stevelinsell** [comment]
Hi @jiavictor ,

Okay it looks like by blacklisting you have stopped the original driver from being loaded so you get a bit further but the new L.2.6.0-60 driver is still exhibiting the same issue when loaded.
Can you take a look at the Release Notes for the L.2.6.0-60 driver:
https://01.org/sites/default/files/downloads/intelr-quickassist-technology/330683qatmuxrelnotesr011us1.pdf
If you read section 5.13 (the last item in the document) it seems to be the same issue you are experiencing:

> When trying to start the Intel® QuickAssist Technology
> driver, I see errors similar to one or more of the following:
> • "QatCtrl_SendSyncMsg() - : AE response received to admin cmd 1, Fail status: 1”
> • “SalCtrl_QatStart_dh895x() - : Sending TRNG_ENABLE msg Failed”
> • "QAT: Could not find a device on node X”

The issue appears to only affect Broadwell based systems and is because ECRC is turned on in the BIOS by default on that platform but the QuickAssist adapter does not support ECRC. The workaround is to turn off the setting in the BIOS which should resolve the issue.
Please can you try this and see how you get on.

One other point, I also see an error that looks like section 5.12 in the dmesg trace:

> When trying to start the qat_service, it fails, and I see the
> following error message: "icp_qa_al: module verification
> failed: signature and/or required key missing - tainting
> kernel". What is the issue?

You may want to also check while you're in the BIOS anyway whether Secure Boot is enabled and disable it if it is.

Let me know if these suggestions help resolve your issue,

Steve.

**Comment by jiavictor** [comment]
Hi @stevelinsell 

Thank you for the important information.
I am now working with Dell to investigate if it is the server's issue. This will take some time.
If there comes to the result, I will feedback.

Thanks.
Victor Jia

**Comment by jiavictor** [comment]
Hi @stevelinsell 

We had re-configurated with the same adapter on Dell R610 which is an old server generation of Dell.
It can be startup.
But when we come with Dell R630 which is Broadwell based, the adapter can not be startup.
We contacted with Dell and they said there is no option in BIOS to turn off ECRC and DH895XCC is not in their compatible list.
We tried to add ecrc=off from GRUB2 but still without luck.

Is intel has some walk-around with this issue?

**Comment by stevelinsell** [comment]
Hi @jiavictor,

Just to confirm.
The kernel boot parameter you set in the GRUB2 was:
`pci=ecrc=off`
and not just 
`ecrc=off` 
correct?

That should have had the desired effect as it will overide the bios configuration.

Steve.

**Comment by jiavictor** [comment]
Hi @stevelinsell 

I tried the configuration, but still can not startup the adapter.
It seems have no effect to BIOS.

I think it is not make sence for Dell that new server do not support the QAT adapter.

**Comment by stevelinsell** [comment]
Hi @jiavictor,

I have been talking to other people here to see if they had any suggestions.
They have told me there are some other reasons why you could be getting that error that relates to a mismatch in size of payloads on the PCIe bus. Here is a selection of other possible workarounds they suggested you could try:

1.	Use setpci to set the payload size of the QAT and upstream bridge
Before the QAT module is inserted and before the driver is brought up:
`setpci -s 00:03.2 160.w=0 # (change 00:03.2 to be the bus:device.function of your root port)`
2.	Use boot line `pci=pcie_bus_peer2peer`
This sets all PCI devices to 128 byte payload size. 
3.	Use boot line `pci=pcie_bus_safe`
Sets the payload size for every device to the largest value supported by all devices below the root complex.

I can't guarantee they will help, but maybe worth a try.

Kind Regards,

Steve.

**Comment by jiavictor** [comment]
Hi @stevelinsell 

Sorry for the late reply.
The good news is that we updated the current version of FW and BIOS of R630 server and the QAT adapter can startup.

The process as the following, for others reference:
1. Update the current FW and BIOS of server
2. Install CentOS 7 (minimal)
3. sudo yum install pciutils libudev-devel boost-devel gcc-c++ openssl-devel zlib-devel kernel-devel
4. sudo vi /etc/modprobe.d/blacklist-intel.conf
blacklist intel_qat
blacklist qat_dh895xcc
5. sudo vi /etc/default/grub
GRUB_CMDLINE_LINUX="intel_iommu=off"
6. reboot
7. Install upstream 1.7 driver

I appreciate your great help, case close.
