### ISSUE TITLE
Under what circumstance would QAT do 'write(efd)'

### ISSUE THREAD

**Issue by mrpre** [intel/QAT_Engine#48]
In OpenSSL, the "e_dasync.so" using the cheat way by writing fd before it switch to dispatcher.So the dispatcher could use epoll_wait/select to detect the POLL_OUT signal.

I view the QAT_engine code, for example, in function 'qat_rsa_encrypt', when cpaCyRsaEncrypt returns CPA_STATUS_RETRY, then qat_wake_job calls 'write' and qat_pause_job calls ASYNC_pause_job to switch to dispatcher. Don't the QAT calls 'write' after it really have done the encryption/decryption ?

My Questions:
1: Under what circumstance would cpaCyRsaEncrypt return CPA_STATUS_RETRY ? I view the quickassist code:
`
if (flight > ring->max_requests_inflight)  
status = CPA_STATUS_RETRY;
`
Does that means the ring is full ?

2: Don't the QAT calls 'write' after it really have done the encryption/decryption ?

**Comment by stevelinsell** [comment]
> 1: Under what circumstance would cpaCyRsaEncrypt return CPA_STATUS_RETRY ? I view the quickassist code:
if (flight > ring->max_requests_inflight) status = CPA_STATUS_RETRY;
Does that means the ring is full ?

Yes exactly correct, you would only get a CPA_STATUS_RETRY if the ring you are submitting to is full. So this would only happen under heavy load.

> 2: Don't the QAT calls 'write' after it really have done the encryption/decryption ?

There are two situations that can occur when you submit a request:
1) **You submit a request successfully to the ring. (This is the normal case)**
a) You exit the submission do..while loop and enter the waiting for response do..while loop.
b) Then qat_pause_job() is called and you switch out of the fibre.
c) In your application you add the fd to the epoll and wait for a response.
d) The polling thread detects a response on the ring and calls the callback associated with the response (qat_rsaCallbackFn() in the case of RSA requests).
e) The callback writes to the fd signalling that a response has returned (calls qat_wake_job()).
f) The epoll detects the event resulting in the OpenSSL function getting called again.
g) The fibre is resumed and execution continues after the qat_pause_job().
h) The response do..while loop detects that the response has come back and exits the loop continuing execution. 
2) **You could not submit the request to the ring as the ring is full and it returned CPA_STATUS_RETRY (This is the retry case)**
a) You do not exit the submission do.while loop. 
b) You write to the fd signalling it is ready (cheating a bit like the dasync engine does as you are simulating that an event has occured).
c) Then qat_pause_job() is called and you switch out of the fibre.
d) In your application you add the fd to the epoll and wait for a response (which is there already in this case).
e) The epoll detects the event resulting in the OpenSSL function getting called again.
f) The fibre is resumed and execution continues after the qat_pause_job
g) The loop detects that the request was not submitted resulting in another attempt to submit the request to the ring. You will loop round (a-g) until the request is successfully submitted to the ring.
h) At this point you will continue with the steps in 1) above which will result in another switch out of the fibre as you wait for the successfully submitted request to come back.

I think your confusion was that you are missing the qat_wake_job() that happens in the callback function after the request has come back from being processed. Hopefully the description above better describes the execution path.
As you can see the retry mechanism in 2) is fairly rudimentary, it just keeps switching in and out of the fibre retrying until it succeeds. Unfortunately there is no notification mechanism from the QAT Driver for when there is room on the rings so we are forced to just keep retrying until we succeed.

Hope that helps,

Steve.
