### ISSUE TITLE
SSL_write() fails and SSL_get_error returns SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by vgmahajanshetty** [intel/QAT_Engine#49]
Hi,

We are using Intel QAT engine. Openssl version: 1.0.1u, QAT package 0.4.11-056.

We are using QAT engine in event driven mode by calling:
ENGINE_ctrl_cmd( peng, "ENABLE_EVENT_DRIVEN_MODE", 0, NULL, NULL, 0 );
ENGINE_ctrl_cmd( peng, "ENABLE_POLLING", 0, NULL, NULL, 0 ) );

Application is multi threaded where each worker thread uses one instance of the QAT engine. We were comparing the performance of the application with and without QAT engine and found that the bandwidth achieved when using QAT engine is less than that achieved without QAT engine.

Currently, in case when QAT engine is enabled we are calling SSL_write() with third parameter as 2048 (i.e, 2KB) to write 2KB data at a time, where as this is 8KB when QAT is turned off.
When I change this length to 4KB or 8KB when QAT is enabled, then SSL_write() writes successfully few time (around 20 times) then it starts giving SSL_ERROR_SYSCALL. But there is absolutely no problem when we write only 2KB at a time, it will not return SSL_ERROR_SYSCALL anytime.

We poll the instance by calling
ENGINE_ctrl_cmd( gsQATEng.eng, "POLL", 0, &poll_status, NULL, 0 );
after every call to SSL_read and SSL_write to check if any pending request has response and handle it accordingly.

I am not getting why is SSL_write () failing when I use buffer > 2KB with error as SSL_ERROR_SYSCALL.

Please let me know if I am missing anything.

Thank you.

**Comment by stevelinsell** [comment]
This repo is for the QAT Engine that works with OpenSSL 1.1.0.
It is a different architecture than the QAT Engine for OpenSSL 1.0.1.

Are you in a position to move over to use OpenSSL 1.1.0?
If not you should contact your assigned Intel Platform Application Engineer for support options for the OpenSSL 1.0.1 QAT Engine.

**Comment by stevelinsell** [comment]
Closing issue as it is not related the QAT Engine contained in this repo.
