### ISSUE TITLE
About deleting OPENSSL_cleanse（）

### ISSUE THREAD

**Issue by konishi-av** [intel/QAT_Engine#5]
Hello,

It is described in a [nginx-1.6.2-async.l.0.1.0-008 document](https://01.org/sites/default/files/downloads/packet-processing/nginx-1.6.2-async.l.0.1.0-008.tar.gz) as follows:

> 5) Performance Optimization to OpenSSL (this is optional step)
> This step is optional. During our testing, we've found OPENSSL_cleanse() to be the bottleneck limiting performance. OPENSSL_cleanse() is a type of memory scrubbing functionality that clears the memory that used to hold the keys. Customers that already use HW accelerators might have already come across this as a bottleneck and might already have it optimized in their systems. For customers that do not use HW accelerators they might not have this optimized already. We are currently evaluating different options to optimize the functionality.

I understood that I can delete `OPENSSL_cleanse()` because it is optional and unnecessary.
Is this same in `OpenSSL1.1.0-pre5`, too?
If it is a problem to delete, please advise a reason.

If a performance improves, I want to implement it like that.
I think that a performance improves around 2%.

Kind regards,

Tom.

**Comment by agrandi** [comment]
Hi Tom,

The purpose of `OPENSSL_cleanse()` is to overwrite an area of memory containing sensitive data (e.g. a private key) before an `OPENSSL_free()`
This is done to avoid security issues when the area of memory is returned to the OS and potentially reassigned to another process in the system.

This operation has a cost and, as you said, it can impact the performance of the application.

From a coding point of view there isn't anything stopping the user to remove the `OPENSSL_cleanse()`, but this should be done only after carefully considering all the security implications.

Hope this helps!

Andrea

**Comment by konishi-av** [comment]
Hi Andrea,

Thank you for your reply!
I understand.
Do you not recommend deleting `OPENSSL_cleanse()`?
Let me see ... I'll think about it.

Regards,

Tom.
