### ISSUE TITLE
undefined symbol: qat_hex_dump

### ISSUE THREAD

**Issue by leesimmons** [intel/QAT_Engine#56]
I have followed the configuration instructions in the README and can get a working version going but I would like to run debug logging. 

Openssl version: 1.1.1-pre3-dev
QAT driver for linux HW version 1.7
dh8950 expansion card

When I make the shared library using both the --enable-qat_debug --with-qat_debug_file=/var/log/qat.log flags and test using openssl engine -t -c -vvvv qat I get thew following trace:

140413308069696:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/usr/local/openssl/lib/engines-1.1/qat.so): /usr/local/openssl/lib/engines-1.1/qat.so: undefined symbol: qat_hex_dump
140413308069696:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
140413308069696:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
140413308069696:error:260BC066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:141:section=qat_section, name=dynamic_path, value=/usr/local/openssl/lib/engines-1.1/qat.so
140413308069696:error:0E07606D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:174:module=engines, value=engine_section, retcode=-1      

I am currently trying to see whether haproxy is utilising the engine or not, I don't know if this will output the information I am after and if it doesn't, it is an issue that I have come up against.

Configure command used:

Problem:
./configure --with-qat_dir=/QAT --with-qat_install_dir=/usr/local/intelQAT --with-openssl_dir=/openssl --with-openssl_install_dir=/usr/local/openssl --enable-qat_for_openssl_master --enable-upstream_driver --enable-usdm --enable-qat_debug --with-qat_debug_file=/var/log/qat.log

Fine:
./configure --with-qat_dir=/QAT --with-qat_install_dir=/usr/local/intelQAT --with-openssl_dir=/openssl --with-openssl_install_dir=/usr/local/openssl --enable-qat_for_openssl_master --enable-upstream_driver --enable-usdm 

Please note, in both instances the shared library is created and copied without error.

**Comment by stevelinsell** [comment]
Hi @leesimmons 

I've tried to recreate this locally using the same parameters as you have used but I'm not seeing the issue. There must be something different in your environment to mine.

Lets start by checking your library and object files:

Can you run the following on the `qat.so` engine library and post the output:

 `nm -l qat.so | grep "qat_hex_dump"`

I see the following:

`000000000000dbd0 T qat_hex_dump /root/QAT_Engine/qat_utils.c:135`

If you could then go to your `QAT_Engine` directory and then `cd` into `.libs` you should see the object files that make up `qat.so`. Then if you can run the following and post the output:

`nm qat_utils.o`

We should then be able to see which functions are getting compiled into the object file. You should see both qat_hex_dump and the functions related to writing to the debug log file. I see the following:

```
00000000000000b0 T crypto_qat_debug_close_log
0000000000000000 T crypto_qat_debug_init_log
0000000000000020 B debug_file_mutex
0000000000000000 B debug_file_ref_count
                 U fclose
                 U fflush
                 U fopen
                 U fprintf
                 U fputc
0000000000000000 r __func__.18384
                 U fwrite
                 U _GLOBAL_OFFSET_TABLE_
0000000000000000 r .LC0
0000000000000002 r .LC1
0000000000000013 r .LC2
0000000000000000 r .LC3
000000000000001f r .LC6
000000000000003d r .LC7
0000000000000040 r .LC8
                 U pthread_mutex_lock
                 U pthread_mutex_unlock
0000000000000048 B qatDebugLogFile
0000000000000110 T qat_hex_dump
                 U stderr

```

Kind Regards,

Steve.

**Comment by leesimmons** [comment]
Thanks for the response @stevelinsell, the output from nm on the qat.so is:

                  U qat_hex_dump

and against the qat_utils:

0000000000000000 B qatDebugLogFile

That is the complete output, not a snippet.

**Comment by leesimmons** [comment]
Ok, I was running the build from master but running from the latest tag the build has worked and I am getting debug logs now. Thanks for the help.

**Comment by stevelinsell** [comment]
Great news, Thanks for your feedback, I'm glad you resolved the issue.

Steve.
