### ISSUE TITLE
HAProxy and qat openssl engine

### ISSUE THREAD

**Issue by leesimmons** [intel/QAT_Engine#57]
Hi,

I have got the qat engine created and tests all pass using openssl commands however I have a problem using haproxy.

I have built the engine using QAT 1.7 upstream driver and OpenSSL 1.1.1-pre3-dev and enabled debug logging. When I start haproxy everything is fine and QAT reports no warnings but as soon as a request is made I get the following:

[DEBUG][qat_rsa.c:845:qat_rsa_priv_enc()] - Started.
[DEBUG][qat_rsa.c:369:build_decrypt_op_buf()] - Started
[DEBUG][qat_rsa.c:381:build_decrypt_op_buf()] flen = 256, padding = 3 
[MEM_DEBUG][cmn_mem_drv_inf.c:87:qaeCryptoMemAlloc()] pthread_mutex_lock
[DEBUG][cmn_mem_drv_inf.c:95:qaeCryptoMemAlloc()] Address: (nil) Size: 128 File: qat_asym_common.c:104
[MEM_DEBUG][cmn_mem_drv_inf.c:99:qaeCryptoMemAlloc()] pthread_mutex_unlock
[WARNING][qat_asym_common.c:107:qat_BN_to_FB()] Failed to allocate fb->pData
[WARNING][qat_rsa.c:426:build_decrypt_op_buf()] Failed to convert privateKeyRep2 elements to flatbuffer
[WARNING][qat_rsa.c:872:qat_rsa_priv_enc()] Failure in build_decrypt_op_buf
[DEBUG][qat_rsa.c:209:rsa_decrypt_op_buf_free()] - Started
[DEBUG][qat_rsa.c:232:rsa_decrypt_op_buf_free()] - Finished

and haproxy logs an SSL handshake error. My configuration options are as follows:

--with-qat_dir=/QAT --with-qat_install_dir=/usr/local/intelQAT --with-openssl_dir=/openssl --with-openssl_install_dir=/usr/local/openssl --enable-qat_for_openssl_master --enable-upstream_driver --enable-usdm

**Comment by stevelinsell** [comment]
Hi @leesimmons 

It looks like the USDM Memory Driver is not present/not functioning/not accessible.
Can you do an `lsmod` and check you can see something like the following modules loaded:

```
usdm_drv               90112  0
qat_dh895xcc           20480  0
intel_qat             217088  2 qat_dh895xcc,usdm_drv
```

If you go to where the QAT Driver is installed can you also run:

`./adf_ctl status`

Which should give you something like:

```
There is 1 acceleration device(s) in the system:
 icp_dev0 - type=dh895xcc, inst_id=0, node_id=0,  bdf=02:00:0, #accel=6, #engines=12, state=up
```

Can you confirm to me that everything is present and up as expected.
Can you also confirm that you have replaced the /etc/dh895xcc_qa_dev0.conf file with the appropriate file from the QAT Engine repo and restarted the QAT Driver.

When you said you had things running with the openssl commands did that include running openssl speed tests that would have offloaded requests?

Also one other question, are you running HAProxy as root user or a a different user? You may need to take special steps to get everything running as a non-root user.

Kind Regards,

Steve.

**Comment by leesimmons** [comment]
Hi @stevelinsell,

The output is as follows:

#  lsmod | grep "usdm\|qat"
usdm_drv               88665  0 
qat_dh895xcc           13688  0 
intel_qat             147433  2 usdm_drv,qat_dh895xcc
authenc                17776  1 intel_qat
uio                    19259  1 intel_qat

# /usr/local/intelQAT/bin/adf_ctl status
Checking status of all devices.
There is 1 QAT acceleration device(s) in the system:
 qat_dev0 - type: dh895xcc,  inst_id: 0,  bsf: 09:00.0,  #accel: 6 #engines: 12 state: up

Thanks for the quick response.

**Comment by stevelinsell** [comment]
Hi @leesimmons 

That all looks good, 
Are you running HAProxy as a non-root user by setting the user/group parameters in the haproxy.cfg file?

Steve.

**Comment by leesimmons** [comment]
It was due to haproxy running as non-root user. I know the problem and will need to find a way around it when moving to production. Thanks.
