### ISSUE TITLE
Can deploy QAT_Engine on only few servers

### ISSUE THREAD

**Issue by crasyangel** [intel/QAT_Engine#58]
And other servers can send handshake data to the QAT_Engine, and get the decrypt data

How?

**Comment by stevelinsell** [comment]
Hi @crasyangel,

I'm not sure I completely understand your question.
Are you hitting a limit on how many servers you can enable for Quickassist?
If that is your issue I will need details of the following:

1) Which QuickAssist product are you using?
2) How many servers (processes) are you running and after how many processes do you hit the limits?
3) How are your QAT Driver config files configured in the [SHIM] section?

Kind Regards,

Steve.

**Comment by crasyangel** [comment]
Hi @stevelinsell

**Comment by crasyangel** [comment]
Hi @stevelinsell 

1. Which QuickAssist product are you using?
icp_dh895xcc_dev0

2. What is the question?
We have hundreds of nodes, and hundreds of machines within each node. So plug acc card in every machine is not possible, quite expensive, and not necessary. We want plug some machine with one node, and all machines can use those ability which have acceleration card, and offload ssl key exchange calculation by acceleration card

**Comment by joelaue** [comment]
This sounds like an SSL termination use case. It is possible to do that via something like the HAProxy "engine" (and "async") feature:

https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#ssl-engine
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#ssl-mode-async

**Comment by stevelinsell** [comment]
Hi @crasyangel,
 
So are you effectively trying to use one machine fitted with QuickAssist as an HSM that you offload the handshake processing to from your other machines?
Something functionally similar to Amazon's AWS CloudHSM:
https://docs.aws.amazon.com/cloudhsm/latest/userguide/introduction.html
but something you completely own all the infrastructure to?

Kind Regards,

Steve.

**Comment by stevelinsell** [comment]
Closing through inactivity.
