### ISSUE TITLE
can't make in centos7(Can't locate configdata.pm)

### ISSUE THREAD

**Issue by felix94536** [intel/QAT_Engine#59]
Hi, I downloaded latest openssl and QAT_Engine code to a centos7 VM. I can make and install openssl, but the make for QAT_Engine failed. Below is the command I did and the failure for the make. What "configdata.pm" is it looking for? I see there is one in openssl source tree in /openssl dir.

./configure --with-qat_dir=/QAT --with-openssl_dir=/openssl --with-openssl_install_dir=/usr/local/ssl --enable-usdm
make
perl /openssl/util/mkerr.pl -conf e_qat.ec -rebuild -reindex -nostatic -write e_qat.c qat_fork.c qat_events.c qat_callback.c qat_polling.c qat_asym_common.c qat_utils.c qat_rsa.c qat_rsa_crt.c qat_ciphers.c qat_dh.c qat_dsa.c qat_ec.c qat_prf.c qat_parseconf.c cmn_mem_drv_inf.c e_qat_err.c && make  all-am
Can't locate configdata.pm in @INC (@INC contains: . /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /openssl/util/mkerr.pl line 13.
BEGIN failed--compilation aborted at /openssl/util/mkerr.pl line 13.
make: *** [all] Error 2

**Comment by stevelinsell** [comment]
Hi @felix94536,

Firstly if you want to build against the OpenSSL master branch rather than the recommended stable release tag `OpenSSL_1_1_0g` then you should configure the build with the `--enable-qat_for_openssl_master` configure option. This will ensure it is looking in the correct place for some of scripts.

The issue you are seeing is new and has appeared recently in the OpenSSL master branch and requires a simple additional workaround:

You need to add the path to the OpenSSL source to your `PERL5LIB` environment variable. So for instance if your OpenSSL source directory is at `/openssl` then you would do:

`export PERL5LIB=$PERL5LIB:/openssl
`

This should give `perl` the path to find the `configdata.pm` file and solve your issue.

We plan to add this information to the `README.md` file in the next QAT Engine release.

Hope this solves your issue,

Steve.

**Comment by felix94536** [comment]
Hi, Steve, Thanks for the correction and pointers! I just downloaded 1.1.0g tarball, put it in /openssl-1.1.0g, made and installed it. Now, I hit another error in making QAT_Engine. Where is this icp_qa_al_s supposed to come from? QAT driver package?

./configure --with-qat_dir=/QAT --with-openssl_dir=/openssl-1.1.0g --with-openssl_install_dir=/usr/local/ssl --enable-usdm
make
...

/bin/sh ./libtool --tag=CC   --mode=link cc -shared -fPIC -Wall     -DUSE_QAE_MEM  -DOPENSSL_ENABLE_QAT_RSA -DOPENSSL_ENABLE_QAT_CIPHERS -DOPENSSL_ENABLE_QAT_ECDH -DOPENSSL_ENABLE_QAT_ECDSA -DOPENSSL_ENABLE_QAT_DSA -DOPENSSL_ENABLE_QAT_DH -DOPENSSL_ENABLE_QAT_PRF        -g -O2   -Wl,-rpath,/QAT/build -L/QAT/build -licp_qa_al_s -Wl,-rpath,/QAT/quickassist/utilities/libusdm_drv -L/QAT/quickassist/utilities/libusdm_drv -lusdm_drv_s  -o libqat.la -rpath /usr/local/ssl/lib e_qat.lo qat_fork.lo qat_events.lo qat_callback.lo qat_polling.lo qat_asym_common.lo qat_utils.lo qat_rsa.lo qat_rsa_crt.lo qat_ciphers.lo qat_dh.lo qat_dsa.lo qat_ec.lo qat_prf.lo qat_parseconf.lo cmn_mem_drv_inf.lo e_qat_err.lo  
libtool: link: gcc -shared  -fPIC -DPIC  .libs/e_qat.o .libs/qat_fork.o .libs/qat_events.o .libs/qat_callback.o .libs/qat_polling.o .libs/qat_asym_common.o .libs/qat_utils.o .libs/qat_rsa.o .libs/qat_rsa_crt.o .libs/qat_ciphers.o .libs/qat_dh.o .libs/qat_dsa.o .libs/qat_ec.o .libs/qat_prf.o .libs/qat_parseconf.o .libs/cmn_mem_drv_inf.o .libs/e_qat_err.o   -L/QAT/build -licp_qa_al_s -L/QAT/quickassist/utilities/libusdm_drv -lusdm_drv_s  -O2 -Wl,-rpath -Wl,/QAT/build -Wl,-rpath -Wl,/QAT/quickassist/utilities/libusdm_drv   -Wl,-soname -Wl,libqat.so.0 -o .libs/libqat.so.0.0.0
/usr/bin/ld: cannot find -licp_qa_al_s
collect2: error: ld returned 1 exit status
make[1]: *** [libqat.la] Error 1
make[1]: Leaving directory `/QAT_Engine'
make: *** [all] Error 2

**Comment by felix94536** [comment]
Looks like libicp_qa_al_s.so is from QAT1.5 or 1.6. I am using 1.7 in qat1.7.upstream.l.1.0.3-42.tar.gz from 01.org. Any config option I need to specify this? Thanks.

**Comment by stevelinsell** [comment]
Hi @felix94536, 

The `libicp_qa_al_s.so` is the QAT Driver shared userspace library for the older QAT Driver package.
The fact you are building with the USDM Memory Driver suggests you are using the newer 1.7 QAT Driver, probably package L.1.0.3-42. This is sometimes referred to as the Upstream QAT Driver.
When building against the Upstream QAT Driver package you should configure the QAT Engine build with the following configure flag:

`--enable-upstream_driver
`

This is needed because the QAT Driver shared userspace library changed name in the Upstream QAT Driver and is now called l`ibqat.so`. With the additional flag you should see the build trying to link to the correct library name.

Just saw your second post as I typed so yes just add the option above :-)

Kind Regards,

Steve.

**Comment by felix94536** [comment]
Thanks. Now, I can make and install it. However, openssl cannot use the engine. Anything missing?

# env | grep OPENSSL
OPENSSL_ENGINES=/usr/local/ssl/lib/engines-1.1
# ll /usr/local/ssl/lib/engines-1.1
total 424
-rwxr-xr-x. 1 root root   7896 Mar 15 10:58 capi.so
-rwxr-xr-x. 1 root root  29000 Mar 15 10:58 padlock.so
-rwxr-xr-x. 1 root root 392544 Mar 15 12:58 qat.so
# cp /QAT_Engine/qat/config/c6xx/multi_process_event-driven_optimized/c6xx_dev* /etc/
# cd /usr/local/ssl/bin/
# ./openssl version
OpenSSL 1.1.0g  2 Nov 2017
# ./openssl engine -t -c -vvvv qat
(qat) Reference implementation of QAT crypto engine
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF]
     [ unavailable ]
     ENABLE_EXTERNAL_POLLING: Enables the external polling interface to the engine.
          (input flags): NO_INPUT
     POLL: Polls the engine for any completed requests
          (input flags): NO_INPUT
     SET_INSTANCE_FOR_THREAD: Set instance to be used by this thread
          (input flags): NUMERIC
     GET_NUM_OP_RETRIES: Get number of retries
          (input flags): NO_INPUT
     SET_MAX_RETRY_COUNT: Set maximum retry count
          (input flags): NUMERIC
     SET_INTERNAL_POLL_INTERVAL: Set internal polling interval
          (input flags): NUMERIC
     GET_EXTERNAL_POLLING_FD: Returns non blocking fd for crypto engine
          (input flags): NO_INPUT
     ENABLE_EVENT_DRIVEN_POLLING_MODE: Set event driven polling mode
          (input flags): NO_INPUT
     GET_NUM_CRYPTO_INSTANCES: Get the number of crypto instances
          (input flags): NO_INPUT
     DISABLE_EVENT_DRIVEN_POLLING_MODE: Unset event driven polling mode
          (input flags): NO_INPUT
     SET_EPOLL_TIMEOUT: Set epoll_wait timeout
          (input flags): NUMERIC
     SET_CRYPTO_SMALL_PACKET_OFFLOAD_THRESHOLD: Set QAT small packet threshold
          (input flags): STRING
     ENABLE_INLINE_POLLING: Enables the inline polling mode.
          (input flags): NO_INPUT
     ENABLE_HEURISTIC_POLLING: Enable the heuristic polling mode
          (input flags): NO_INPUT
     GET_NUM_REQUESTS_IN_FLIGHT: Get the number of in-flight requests
          (input flags): NUMERIC
# ./openssl speed -engine qat -elapsed -async_jobs 72 rsa2048
can't use that engine
140477976930112:error:8007B09F:lib(128):qat_engine_init:instance unavailable:e_qat.c:363:
140477976930112:error:260B806D:engine routines:engine_table_register:init failed:crypto/engine/eng_table.c:125:
You have chosen to measure elapsed time instead of user CPU time.
Doing 2048 bit private rsa's for 10s: 13371 2048 bit private RSA's in 10.01s
Doing 2048 bit public rsa's for 10s: 465403 2048 bit public RSA's in 10.00s
OpenSSL 1.1.0g  2 Nov 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl/ssl\"" -DENGINESDIR="\"/usr/local/ssl/lib/engines-1.1\""  -Wa,--noexecstack
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000749s 0.000021s   1335.8  46540.3

**Comment by stevelinsell** [comment]
Hi @felix94536,

You need to restart the QAT Driver in order for it to pick up the new config files you copied to /etc.
After that there should be instances available.
See the following section of the README.md for further details:
https://github.com/intel/QAT_Engine#copy-the-correct-intel-quickassist-technology-driver-config-files

Kind Regards,

Steve.

**Comment by stevelinsell** [comment]
Great, I'll close this issue for now.
If anything related crops up you can reopen it, or else create a new issue.

Kind Regards,

Steve.
