### ISSUE TITLE
 fail to Build and load the example contiguous memory driver - qat_contig_mem  

### ISSUE THREAD

**Issue by martin-m-wang** [intel/QAT_Engine#63]
Hi,
I've been able to make and install the **User Space DMA-able Memory (USDM) Component** and running the engine  but to make **contiguous memory driver  - qat_contig_mem** fails.

Although I could run this tool successful using USDM Component, I encountered another make fail in make QATzip(and just opened an issue there) and I begin to wonder if there is any relation between the two.

root@ubuntu:/opt/openssl/QAT_Engine/qat_contig_mem# make
make -C /lib/modules/4.16.1-041601-generic/build SUBDIRS=/opt/openssl/QAT_Engine/qat_contig_mem modules
make[1]: Entering directory '/usr/src/linux-headers-4.16.1-041601-generic'
  CC [M]  /opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.o
In file included from /opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.c:72:0:
./arch/x86/include/asm/uaccess.h: In function ‘set_fs’:
./arch/x86/include/asm/uaccess.h:32:9: error: dereferencing pointer to incomplete type ‘struct task_struct’
  current->thread.addr_limit = fs;
         ^
/opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.c: In function ‘do_ioctl’:
/opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.c:216:13: error: implicit declaration of function ‘copy_to_user’ [-Werror=implicit-function-declaration]
         if (copy_to_user((void *)arg, mem, sizeof(*mem))) {
             ^
/opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.c: In function ‘qat_contig_mem_ioctl’:
/opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.c:267:9: error: implicit declaration of function ‘copy_from_user’ [-Werror=implicit-function-declaration]
     if (copy_from_user(&mem, (unsigned char *)arg, sizeof(mem))) {
         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:330: recipe for target '/opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.o' failed
make[2]: *** [/opt/openssl/QAT_Engine/qat_contig_mem/qat_contig_mem.o] Error 1
Makefile:1567: recipe for target '_module_/opt/openssl/QAT_Engine/qat_contig_mem' failed
make[1]: *** [_module_/opt/openssl/QAT_Engine/qat_contig_mem] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.16.1-041601-generic'
Makefile:29: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by paulturx** [comment]
Hi Martin
Linux version 4.16.1 is a very recent version on which we have not carried out qat_contig_mem build tests.  You say that the USDM memory driver builds & installs successfully with this version of Linux.  Since the USDM driver is newer & now the standard/recommended memory driver to use, do you have a particular requirement to use the qat_contig_mem_driver instead of USDM?  We would suggest that the qat_contig_mem driver is better suited for applications using earlier Linux kernel versions than the one you are currently using.
Regards,
    Paul Turner

**Comment by martin-m-wang** [comment]
Hi Paul,
Thank you for your reply. I used the newer kernel to better support NVMe drives on the system backend and we'll stick to that for some time. There is no particular requirement to use the "qat_contig_mem_driver". As for the QATzip issue on kernel 4.16.1, I'll update and post there.
Thank you for your support.

Best Regards,
Martin Wang
