### ISSUE TITLE
Problem after compile with QAT1.5

### ISSUE THREAD

**Issue by rokoman** [intel/QAT_Engine#66]
Hardware: Lanner FW-7525
OS: Debian 9.4 (Stretch)
Kernel: linux-image-4.9.0-6-amd64 (4.9.88-1)
CPU: Intel Atom C2558
Memory: 8G
Policy: MultiProcess (c2xxx_qa_dev0_single_ae.conf)

QAT Driver: 1.5 (Revision: L.1.13.0-19)
Openssl Version: 1.1.0h

Compile and Install : QAT Driver , QAT Engine no error

When testing
cd /usr/local/ssl/bin
./openssl engine -t -c -vvvv qat

Result: Error

> 140487335650432:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/usr/local/ssl/lib/engines-1.1/qat.so): /QAT/QAT1.5/build/libicp_qa_al_s.so: undefined symbol: icp_adf_getQueueNext
> 140487335650432:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
> 140487335650432:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
> 140487335650432:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=qat
>

**Comment by Yogaraj-Alamenda** [comment]
Hi @rokoman Sorry for the delayed response, Couple of questions to help you with the issue.

1. icp_adf_getQueueNext is defined in @quickassist/adf/user/user_proxy/src/adf_user_ETring_mgr_dp.c and exported in the libadf_proxy.a library. Could you please send the nm output of 
libadf_proxy.a and libicp_qa_al_s.so which will actually show all the symbols present in the library 
Ideal output will be something like below :
>> nm quickassist/lookaside/access_layer/src/build/linux_2.6/user_space/libicp_qa_al_s.so | grep icp_adf_getQueueNext
_000000000062560 T icp_adf_getQueueNext_
>> nm quickassist/adf/user/user_proxy/src/build/linux_2.6/user_space/libadf_proxy.a | grep icp_adf_getQueueNext 
_0000000000000120 T icp_adf_getQueueNext_
2. Are you using installer.sh script from the package to install the driver or just building it without installing? Using option 2 in the installer.sh script will build and install all the necessary libraries and
take care of installation of the driver.
I do not see any circumstance where that symbol will not get exported as its not in any #define flags

**Comment by rokoman** [comment]
Sorry late reply

1. icp_adf_getQueueNext is defined in /user/user_proxy/src/adf_user_ETring_mgr_dp.c and exported in the libadf_proxy.a library. Could you please send the nm output of
libadf_proxy.a and libicp_qa_al_s.so which will actually show all the symbols present in the library
Ideal output will be something like below :

> nm build/libicp_qa_al_s.so| grep icp_adf_getQueueNext
>        U icp_adf_getQueueNext

> nm build/libadf_proxy.a| grep icp_adf_getQueueNext
>        

no output

2. Are you using installer.sh script from the package to install the driver or just building it without installing? Using option 2 in the installer.sh script will build and install all the necessary libraries and
take care of installation of the driver.

> Yes, i install select option 2

but i modify support systemd

>     install -D -m 0644 quickassist.service /lib/systemd/system
>     install -D -m 0755 adf_ctl /sbin
> 
>     libDir="/usr/lib"
> 
>     echo "Copying libicp_qa_al_s.so to $libDir"
>     cp libicp_qa_al_s.so $libDir
>     echo "Copying libicp_qa_al.a to $libDir"
>     cp libicp_qa_al.a $libDir
>     echo "Copying libosal.a to $libDir"
>     cp libosal.a $libDir
>     echo "Copying libadf_proxy.a to $libDir"
>     cp libadf_proxy.a $libDir
> 
>     if [ $numC2xxxDevice != "0" ]; then
>         echo "sha256" > /etc/modules-load.d/quickassist.conf
>         echo "sha512" >> /etc/modules-load.d/quickassist.conf
>         echo "icp_qa_al" >> /etc/modules-load.d/quickassist.conf
> 
>         echo 'KERNEL=="icp_adf_ctl" MODE="0600"' > /lib/udev/rules.d/80-c2xxx_qa.rules
>         echo 'KERNEL=="icp_dev[0-9]*" MODE="0600"' >> /lib/udev/rules.d/80-c2xxx_qa.rules
>         echo 'KERNEL=="icp_dev_mem?" MODE="0600"' >> /lib/udev/rules.d/80-c2xxx_qa.rules
> 
>         udevadm control --reload-rules
>         udevadm trigger
>     fi
> 
>     echo "Starting QAT service"
>     systemctl daemon-reload
>     modprobe icp_qa_al
>     sleep 2
> 
>     systemctl enable quickassist
>     systemctl start quickassist
>     systemctl status quickassist
>

**Comment by stevelinsell** [comment]
Hi @rokoman,

We've not managed to recreate this issue locally.
If you would like us to try and debug further we would require that you post the InstallerLog.txt file that is created in the QAT Driver directory when you run the QAT Driver Install. Hopefully that will give us more detail on the compilation and linking steps you are going through and might give us a clue what is going wrong.

Kind Regards,

Steve.

**Comment by rokoman** [comment]
Hi @stevelinsell 

Thank you so much.
InstallerLog.txt.  [(link)](https://ufile.io/yzb5g)

installer.sh (Modify support systemd) [(link)](https://ufile.io/75qdp)

and modify file (quickassist/adf/drivers/common/linux/src/adf_proc_debug.c) for support kernel 4.9

```
#if (LINUX_VERSION_CODE < KERNEL_VERSION(3,19,0))
                int ret = 0, old_offset = file_info->offset;
#else
                int old_offset = file_info->offset;
#endif
```

```
#if (LINUX_VERSION_CODE < KERNEL_VERSION(3,19,0))
                ret = seq_puts(sfile, (char*)file_info->page);
                if (ret) {
#else
                seq_puts(sfile, (char*)file_info->page);
                if (seq_has_overflowed(sfile)) {
#endif
```

Kind Regards,
RoKoMaN

**Comment by rokoman** [comment]
Hi @stevelinsell

Thank you so much.
Sorry late reply. other problem after compile 

> undefined symbol: SHA_Init
> 139692719335168:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:159:

but i modify  OsalCryptoInterface.c
```
-    if(!SHA_Init(&ctx))
+    if(!SHA1_Init(&ctx))
     {
         return OSAL_FAIL;
     }

```

when compile finish no error but when run test

> segmentation fault  ./openssl engine -t -c -vvv qat

file config  /etc/c2xxx_qa_dev0.conf
```
##############################################
# Kernel Instances Section
##############################################
[KERNEL]
NumberCyInstances = 1

# Crypto - Kernel instance #0
Cy0Name = "IPSec0"
Cy0AcceleratorNumber = 0
Cy0IsPolled = 0
Cy0CoreAffinity = 0

##############################################
# User Process Instance Section
##############################################
[SSL]
NumberCyInstances = 1
NumProcesses = 1
LimitDevAccess = 0

# Crypto - User instance #0
Cy0Name = "SSL0"
Cy0IsPolled = 1
Cy0AcceleratorNumber = 0
# List of core affinities
Cy0CoreAffinity = 0

##############################################
# Wireless Process Instance Section
##############################################
[WIRELESS]
NumberCyInstances = 1
NumProcesses = 0

# Crypto - User instance #0
Cy0Name = "WIRELESS0"
Cy0IsPolled = 1
Cy0AcceleratorNumber = 0
# List of core affinities
Cy0CoreAffinity = 0

```

strace ./openssl engine -t -c -vvv qa
strace output

> execve("./openssl", ["./openssl", "engine", "-t", "-c", "-vvv", "qat"], [/* 18 vars */]) = 0
> brk(NULL)                               = 0x55cd277b4000
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb2e44e6000
> access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
> open("/usr/local/ssl/lib/tls/x86_64/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> stat("/usr/local/ssl/lib/tls/x86_64", 0x7ffd24bcf590) = -1 ENOENT (No such file or directory)
> open("/usr/local/ssl/lib/tls/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> stat("/usr/local/ssl/lib/tls", 0x7ffd24bcf590) = -1 ENOENT (No such file or directory)
> open("/usr/local/ssl/lib/x86_64/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> stat("/usr/local/ssl/lib/x86_64", 0x7ffd24bcf590) = -1 ENOENT (No such file or directory)
> open("/usr/local/ssl/lib/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0pw\1\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0755, st_size=529808, ...}) = 0
> mmap(NULL, 2554008, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb2e4056000
> mprotect(0x7fb2e40bd000, 2093056, PROT_NONE) = 0
> mmap(0x7fb2e42bc000, 40960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x66000) = 0x7fb2e42bc000
> close(3)                                = 0
> open("/usr/local/ssl/lib/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\200\6\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0755, st_size=2952080, ...}) = 0
> mmap(NULL, 4754880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb2e3bcd000
> mprotect(0x7fb2e3e2c000, 2093056, PROT_NONE) = 0
> mmap(0x7fb2e402b000, 163840, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x25e000) = 0x7fb2e402b000
> mmap(0x7fb2e4053000, 11712, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb2e4053000
> close(3)                                = 0
> open("/usr/local/ssl/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
> fstat(3, {st_mode=S_IFREG|0644, st_size=48769, ...}) = 0
> mmap(NULL, 48769, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb2e44da000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200\r\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0644, st_size=14640, ...}) = 0
> mmap(NULL, 2109680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb2e39c9000
> mprotect(0x7fb2e39cc000, 2093056, PROT_NONE) = 0
> mmap(0x7fb2e3bcb000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fb2e3bcb000
> close(3)                                = 0
> open("/usr/local/ssl/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0Pa\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0755, st_size=135440, ...}) = 0
> mmap(NULL, 2212936, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb2e37ac000
> mprotect(0x7fb2e37c4000, 2093056, PROT_NONE) = 0
> mmap(0x7fb2e39c3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7fb2e39c3000
> mmap(0x7fb2e39c5000, 13384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb2e39c5000
> close(3)                                = 0
> open("/usr/local/ssl/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\4\2\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0755, st_size=1689360, ...}) = 0
> mmap(NULL, 3795296, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb2e340d000
> mprotect(0x7fb2e35a2000, 2097152, PROT_NONE) = 0
> mmap(0x7fb2e37a2000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x195000) = 0x7fb2e37a2000
> mmap(0x7fb2e37a8000, 14688, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb2e37a8000
> close(3)                                = 0
> mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb2e44d8000
> arch_prctl(ARCH_SET_FS, 0x7fb2e44d9480) = 0
> mprotect(0x7fb2e37a2000, 16384, PROT_READ) = 0
> mprotect(0x7fb2e39c3000, 4096, PROT_READ) = 0
> mprotect(0x7fb2e3bcb000, 4096, PROT_READ) = 0
> mprotect(0x7fb2e402b000, 122880, PROT_READ) = 0
> mprotect(0x7fb2e42bc000, 16384, PROT_READ) = 0
> mprotect(0x55cd26df6000, 4096, PROT_READ) = 0
> mprotect(0x7fb2e44e9000, 4096, PROT_READ) = 0
> munmap(0x7fb2e44da000, 48769)           = 0
> set_tid_address(0x7fb2e44d9750)         = 15182
> set_robust_list(0x7fb2e44d9760, 24)     = 0
> rt_sigaction(SIGRTMIN, {sa_handler=0x7fb2e37b1bd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fb2e37bd0c0}, NULL, 8) = 0
> rt_sigaction(SIGRT_1, {sa_handler=0x7fb2e37b1c60, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7fb2e37bd0c0}, NULL, 8) = 0
> rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
> getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
> brk(NULL)                               = 0x55cd277b4000
> brk(0x55cd277d5000)                     = 0x55cd277d5000
> futex(0x7fb2e4054298, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e4054144, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fb2e3440060}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
> futex(0x7fb2e4054380, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e42c57a0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> sysinfo({uptime=171693, loads=[0, 0, 0], totalram=8362688512, freeram=7017021440, sharedram=29974528, bufferram=207745024, totalswap=3997167616, freeswap=3997167616, procs=199, totalhigh=0, freehigh=0, mem_unit=1}) = 0
> futex(0x7fb2e405427c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e4054274, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e405270c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e42c587c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e40540dc, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e40540d0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e405428c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e405423c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e4054234, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> open("/usr/local/ssl/ssl/openssl.cnf", O_RDONLY) = 3
> fstat(3, {st_mode=S_IFREG|0644, st_size=10771, ...}) = 0
> read(3, "#\n# OpenSSL example configuratio"..., 4096) = 4096
> read(3, "ape crash on BMPStrings or UTF8S"..., 4096) = 4096
> read(3, " is omitted\n# the certificate ca"..., 4096) = 2579
> read(3, "", 4096)                       = 0
> close(3)                                = 0
> futex(0x7fb2e4054268, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> futex(0x7fb2e3bcc0a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> open("/usr/local/ssl/lib/engines-1.1/qat.so", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\236\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0755, st_size=171136, ...}) = 0
> mmap(NULL, 2370360, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb2e31ca000
> mprotect(0x7fb2e31ea000, 2097152, PROT_NONE) = 0
> mmap(0x7fb2e33ea000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x20000) = 0x7fb2e33ea000
> mmap(0x7fb2e33ee000, 125752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb2e33ee000
> close(3)                                = 0
> open("/root/code/build/tls/x86_64/libicp_qa_al_s.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> stat("/root/code/build/tls/x86_64", 0x7ffd24bcebe0) = -1 ENOENT (No such file or directory)
> open("/root/code/build/tls/libicp_qa_al_s.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> stat("/root/code/build/tls", 0x7ffd24bcebe0) = -1 ENOENT (No such file or directory)
> open("/root/code/build/x86_64/libicp_qa_al_s.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> stat("/root/code/build/x86_64", 0x7ffd24bcebe0) = -1 ENOENT (No such file or directory)
> open("/root/code/build/libicp_qa_al_s.so", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\332\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0770, st_size=621504, ...}) = 0
> mmap(NULL, 2918152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb2e2f01000
> mprotect(0x7fb2e2f85000, 2093056, PROT_NONE) = 0
> mmap(0x7fb2e3184000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x83000) = 0x7fb2e3184000
> mmap(0x7fb2e318a000, 259848, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb2e318a000
> close(3)                                = 0
> mprotect(0x7fb2e3184000, 4096, PROT_READ) = 0
> mprotect(0x7fb2e33ea000, 4096, PROT_READ) = 0
> access("/dev/qat_contig_mem", F_OK)     = -1 ENOENT (No such file or directory)
> munmap(0x7fb2e31ca000, 2370360)         = 0
> munmap(0x7fb2e2f01000, 2918152)         = 0
> --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fb2e31e671b} ---
> +++ killed by SIGSEGV +++
> zsh: segmentation fault  strace ./openssl engine -t -c -vvv qat

**Comment by stevelinsell** [comment]
Hi @rokoman,

It appears you do not have the pinned contiguous memory driver loaded (qat_contig_mem).
This is necessary as the QuickAssist accelerator expects the memory it will be operating on to be DMAable.
For instructions on how to build and load the qat_contig_mem kernel module please see the following section of the README.md:
https://github.com/intel/QAT_Engine#build-and-install-a-contiguous-memory-driver

Hope this helps,

Steve.

**Comment by rokoman** [comment]
Hi @stevelinsell

qat_config_mem load
when run test but error  "can't use that engine"

> lab# ./openssl speed -engine qat -elapsed -async_jobs 72 rsa2048
> can't use that engine
> 140701742572672:error:8007B0A0:lib(128):qat_engine_init:instance unavailable:e_qat.c:367:
> 140701742572672:error:260B806D:engine routines:engine_table_register:init failed:crypto/engine/eng_table.c:130:
> You have chosen to measure elapsed time instead of user CPU time.
> Doing 2048 bit private rsa's for 10s: 2051 2048 bit private RSA's in 10.01s
> Doing 2048 bit public rsa's for 10s: 70022 2048 bit public RSA's in 10.00s
> OpenSSL 1.1.0h  27 Mar 2018
> built on: reproducible build, date unspecified
> options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
> compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl/ssl\"" -DENGINESDIR="\"/usr/local/ssl/lib/engines-1.1\""  -Wa,--noexecstack
>                   sign    verify    sign/s verify/s
> rsa 2048 bits 0.004881s 0.000143s    204.9   7002.2

Thanks,
rokoman.

**Comment by stevelinsell** [comment]
Hi @rokoman,

Looking at what you have posted further up and the error you are getting:

> 140701742572672:error:8007B0A0:lib(128):qat_engine_init:instance unavailable:e_qat.c:367:

it would appear that you have not changed the QAT Driver config file:
`/etc/c2xxx_qa_dev0.conf`
to use the file supplied with the QAT Engine (the QAT Engine uses a different section in the file that the default file does not contain).
Please see the following section of the README.md for details:
https://github.com/intel/QAT_Engine/blob/master/README.md#copy-the-correct-intel-quickassist-technology-driver-config-files

Kind Regards,

Steve.
