### ISSUE TITLE
Transplant QAT driver to newer Linux Kernel

### ISSUE THREAD

**Issue by tokers** [intel/QAT_Engine#75]
Hello!

Is there any plans to transplant the QAT driver to to newer Linux Kernel like 4.9.x?

**Comment by stevelinsell** [comment]
Hi @tokers,

Which QAT Driver were you interested in using with a 4.9.x kernel? 

The QAT 1.7 Driver (L.4.2.0-00012 at time of writing) should already compile and run correctly with a 4.9.x kernel.
The QAT 1.5 and QAT 1.6 Drivers do not.
I am not aware of any plans to update the QAT 1.5/QAT 1.6 Driver releases to support the newer kernels, but I'm not involved directly in those releases.
If you would like a definitive answer or to discuss your business needs then I would advise contacting Intel Support directly via your Intel Platform Application Engineer or the usual Intel support channels.

Kind Regards,

Steve.

**Comment by tokers** [comment]
@stevelinsell OK. It seems that the QAT 1.7 driver is what I need :). Thanks very much!

**Comment by tokers** [comment]
Hi @stevelinsell,
By the way, is there any statistics inside /proc filesystem for The QAT 1.7 Driver L.4.2.0-00012, like the/proc/icp_* for QAT1.5 and QAT1.6? :)

**Comment by stevelinsell** [comment]
Hi @tokers,

Yes the statistics have moved location in the filesystem for the latest driver.
You'll find them under `/sys/kernel/debug/qat_c6xx_*:00.0`
You'll need to change `qat_c6xx_` for the product you are using if different.
Also the `*:00.0` is the `<bus>:<slot>.<function>` for that endpoint, so for instance there will be 3 folders for the `qat_c6xx` product but only one folder for` qat_dh895` and `qat_c3xxx`. For instance on my board the folders are:
```
/sys/kernel/debug/qat_c6xx_83:00.0
/sys/kernel/debug/qat_c6xx_84:00.0
/sys/kernel/debug/qat_c6xx_85:00.0
```
The file `fw_counters` in each folder contains the counts of requests that have been offloaded (the equivalent of the `qat` file on QAT1.5 and QAT1.6.

Hope that helps,

Steve.

**Comment by tokers** [comment]
@stevelinsell Thanks again!
