### ISSUE TITLE
qat card utilization report and monitor

### ISSUE THREAD

**Issue by tokers** [intel/QAT_Engine#78]
Hello!

I am using qat card dh8950, and the driver is qat1.7.l.4.2.0-00012.

I want to fetch qat card utilization (just like the cpu util reported by top and pidstat). Is this supported?

By the way, the information inside /sys/kernel/debug/qat_dh895xcc/ seems lack the guide, I only see this in  https://01.org/sites/default/files/downloads/intelr-quickassist-technology/336210qatswprogguiderev001review.pdf, but the description is less. Entries in /sys/kernel/debug/qat_dh895xcc/  are:

```
-r--------  1 root root 0 Jul 13 01:23 dev_cfg
-r--------  1 root root 0 Jul 13 01:23 fw_counters
-r--------  1 root root 0 Jul 13 01:23 heartbeat
-r--------  1 root root 0 Jul 13 01:23 heartbeat_failed
-r--------  1 root root 0 Jul 13 01:23 heartbeat_sent
drwxr-xr-x 34 root root 0 Jul 17 01:17 transport
drwxr-xr-x  2 root root 0 Jul 13 01:23 version
```

I want to do the heartbeat just like the way in qat1.6 (cat heartbeat file and observe the result).

Thanks!

**Comment by stevelinsell** [comment]
Hi @tokers,

Generally the recommended way of using the heartbeat feature is programmatically as detailed in:
[Intel® QuickAssist Technology Software for Linux* - Programmer's Guide - HW version 1.7](https://01.org/sites/default/files/downloads/intelr-quickassist-technology/336210qatswprogguiderev004.pdf) - Section 3.17

If you want to use heartbeat via the `/sys/kernel/debug/qat_dh895xcc` filesystem as you state this is undocumented.
It is my understanding that if you `cat /sys/kernel/debug/qat_dh895xcc/heartbeat` this will issue a heartbeat request to the firmware. You can observe this by checking the value returned by `cat /sys/kernel/debug/qat_dh895xcc/heartbeat_sent` which should increase each time you `cat /sys/kernel/debug/qat_dh895xcc/heartbeat`. If a heartbeat request fails then you can detect this by monitoring the result of  `cat /sys/kernel/debug/qat_dh895xcc/heartbeat_failed` which will increment on a failure. This is all just based on my observation of the feature as like you say it is not officially documented. I will try and find out whether there are plans to document it officially in a future release.

In terms of QAT card utilization, I'm not aware of a way to get this displayed in a useful manner. Obviously there is the count of requests that is accessed via `cat /sys/kernel/debug/fw_counters`. This could be read at a fixed interval (x seconds) and then the data parsed and graphed to show number of requests over time. This would show whether utilization was increasing or decreasing over time. It is hard to graph that with any kind of absolute scale though (0-100% usage) as the types of request are not differentiated. Many small symmetric encryption requests would take far less resource than a single large request and asymmetric RSA sign requests for instance take a large amount of resource but from the counters it is not possible to tell how many of those are happening. If that feature is important to you then I would recommend raising the issue through the standard Intel® Support Channels.

Hope this information is helpful,

Steve.

**Comment by tokers** [comment]
@stevelinsell. Thanks for the detailed answers!
