### ISSUE TITLE
qat_engine in external polling

### ISSUE THREAD

**Issue by tsenghu** [intel/QAT_Engine#8]
this does not work.
when in external polling mode, it failed to retrieve polling FD. 
the issue is as follow:
1. after engine is inited, the eventPoll_ns is running. this thread needs to remove when external polling mode is enabled. 
2. I have modified codes when external polling mode is enabled, it will first call qat_engine_finish before external_polling flag is set to one. 
3. now, the issue is one of the qat instance is not running. I am still debugging this issue. If you can provide some suggestions, that is helpful.
thanks

Tseng

**Comment by agrandi** [comment]
Hi Tseng,

If you want to use the external polling mode you will need to use the control command `ENABLE_POLLING` before the initialization of the engine.

From the documentation of `ENABLE_POLLING` contained in the README:

        If required this message must be sent between
        engine creation and engine initialization.


After the initialization, you can use the control message `GET_POLLING_FD` to obtain the file descriptor.

Does this help to solve your issue?

We don't have support for switching from internal polling to external polling after the engine is initialized. Could you change the behavior of the application or this is a requirement of your use case?

**Comment by tsenghu** [comment]
Yes, I did realize that.

Unfortunately , I can’t figure out how to enable it before engine is initialized. 

 

Thanks

 

 

 

Tseng

 

Here is my code:

       engine = setup_engine(qat_name,0);

        if (engine == NULL) {

            fprintf(stderr," cant load qat \n");

            exit(1);

        }

        func = ENGINE_get_ctrl_function(engine);

#if 1

        func(engine,QAT_CMD_ENABLE_POLLING,0,engine,NULL);

               func(engine,QAT_CMD_GET_NUM_CRYPTO_INSTANCES,0,&numinstances,NULL);

        func(engine,QAT_CMD_ENABLE_EVENT_DRIVEN_MODE,0,NULL,NULL);

**Comment by stevelinsell** [comment]
Hi Tseng,

Just a thought but have you considered using the openssl.cnf file to enable the engine? It might not suit your use case but have a look at the end of the README.md as we added a new section last week detailing how to use it. My suggestion would be to set it up as in the example in the README.md including the additional custom messages:
ENABLE_POLLING = EMPTY 
ENABLE_EVENT_DRIVEN_MODE = EMPTY
as both of these messages should be sent before initialising the engine.
I believe you should then still be able to make the calls to get the number of crypto instances and to get the event driven polling fds which should both be called after the engine has been initialised anyway and as both return values can't be called from the openssl.cnf file.

P.S. Do remember that you need to make a call to:
OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL);
as your first call to the OpenSSL library in order for OpenSSL to read in the openssl.cnf file.

**Comment by tsenghu** [comment]
Thanks,

 

I will look into it.

 

What I have do is as follow:

Modified these two parameters in e_qat.c and recompiled it.

The issue with that is, when external threads are running.  ( one thread per instance)

I got message saying “ [error] cpaCyEcPointMultiply() - : Instance not in a Running state.

 

I know for sure it is in running state after qat is initialized.

 

 

 

Tseng

**Comment by agrandi** [comment]
Hi Tseng,

Using the approach suggested by Steve you won't need to modify `e_qat.c` and recompile the engine.

With regard to the error with the instances, is your application initializing the engine multiple times - i.e. one for every thread?

Andrea

**Comment by tsenghu** [comment]
Only once, perhaps it is caused by the way I have changed in e_qat.c. 

I have followed what Steve have suggested. I don’t see any difference.

Perhaps, it is not reading openssl.cnf from /etc/ssl.

 

Tseng

**Comment by tsenghu** [comment]
Sorry to bother you again.

Here is what happen after I use openssl.cnf

 

OPENSSL_INIT: ossl_init_base: Setting up stop handlers

OPENSSL_INIT: ossl_init_config: openssl_config(NULL)

OPENSSL_INIT: ossl_init_engine_rdrand: engine_load_rdrand_int()

OPENSSL_INIT: ossl_init_load_crypto_strings: err_load_crypto_strings_int         ()

OPENSSL_INIT: ossl_init_thread_start: marking thread for err_state

OPENSSL_INIT: ossl_init_engine_dynamic: engine_load_dynamic_int()

CONF_modules_load_file ...(null) (null)

CONF_get1_default_config_file /etc/ssl/openssl.cnf

CONF_modules_load_file .../etc/ssl/openssl.cnf

vsection openssl_init

vsection openssl_init values ...12f99e0

name engines value 12fa080

module_run name engines md 0x12e7170

module_run ........

Called engine module: name engines, value engine_section

int_engine_module_init   name qat val qat_section

Configuring engine qat

ENGINE conf: doing ctrl(engine_id,qat)

ENGINE conf: doing ctrl(dynamic_path,/usr/local/openssl-1.1.0/lib/engine         s-1.1/qat.so)

[bind_qat] id=(null)

bind_qat: About to set mem functions

ENGINE conf: doing ctrl(ENABLE_EVENT_DRIVEN_MODE,EMPTY)

name ENABLE_EVENT_DRIVEN_MODE ctrlvalue EMPTY

EVENT POLL enabled 1

ENGINE conf: doing ctrl(ENABLE_POLLING,EMPTY)

name ENABLE_POLLING ctrlvalue EMPTY

POLL enabled 1

ENGINE conf: doing ctrl(default_algorithms,ALL)

name default_algorithms ctrlvalue ALL

[qat_engine_init] ---- Engine Initing

 

enable_external_polling 1 inited 0

looking for dir icp_dh895xcc_dev0

looking in /etc/dh895xcc_qa_dev0.conf

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit 0x4c000a30 0

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit pCryptoService 0x4c0         00a30

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit 0x4c000d40 0

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit pCryptoService 0x4c0         00d40

qat_engine_init: 2 Cy instances got

set address  0 0x7f5e4c000a30

start instance  0 0x7f5e4c000a30

Instance 0: 0x7f5e4c000a30 is running

set address  1 0x7f5e4c000d40

start instance  1 0x7f5e4c000d40

Instance 1: 0x7f5e4c000d40 is running

OPENSSL_INIT: ossl_init_add_all_ciphers: openssl_add_all_ciphers_int()

OPENSSL_INIT: ossl_init_add_all_digests: openssl_add_all_digests()

port 8000 mode 1

num of instances 2

number of instances 2  numinstances 2  cache enabled

OPENSSL_INIT: ossl_init_async: async_init()

POLL FD get 10 handle 0x7f5e4c000a30

ns_qat_epoll_create fd 10 efd 9 epoll 0x7f5e43fff2d8

0 cpu bind to 2 size 0

use_fd 0 sd =11 efd=9

set instance for thread 0 0x7f5e4c000a30

SET INSTANCE for thread 0

POLL FD get 13 handle 0x7f5e4c000d40

ns_qat_epoll_create fd 13 efd 12 epoll 0x7f5e47fff470

1 cpu bind to 3 size 0

use_fd 0 sd =14 efd=12

set instance for thread 1 0x7f5e4c000d40

SET INSTANCE for thread 1

0 : open 0 closed 0 del 0

1 : open 0 closed 0 del 0

Opened 0 closed 0 freeed 0 errors 0 ssl errors 0 epoll add 0 epoll del          0 qat_epoll 0  del 0

OPENSSL_INIT: ossl_init_thread_start: marking thread for async

OPENSSL_INIT: ossl_init_thread_start: marking thread for err_state

qat_ecdh_compute_key been called

qat_setup_async_event_notification create_fd 17

[qat_engine_init] ---- Engine Initing

 

enable_external_polling 1 inited 1

Instance 0x7f5e4c000a30 is running

get_next_inst 0x7f5e4c000a30

cpaCyEcPointMultiply 0x7f5e4c000a30

qat_pause_job job=0x7f5e50002710

ns_qat_epoll chann 0...

poll_one num 0 0x7f5e4c000a30 0x7f5e4c000a30

e_qat.qat_crypto_callbackFn: opDone->job 0x7f5e50002710

qat_wake_job ....

qat_wake_job write  fd=17 stat=8

qat_pause_job pause resume job=0x7f5e50002710

qat_pause_job waitctx = 0x7f5e500021e0

qat_pause_job get_fd 17

qat_pause_job return from read 17 stat 8

[qat_rsa_priv_enc] --- called.

[build_decrypt_op_buf] --- flen =36, padding = 1

qat_setup_async_event_notification get_fd 17

[qat_engine_init] ---- Engine Initing

 

enable_external_polling 1 inited 1

[error] Sal_ServiceIsRunning() - :  Instance not in a Running state 0x4c         000d40 state 1

[error] Sal_ServiceIsRunning() - : 0x4c000d40 ......

 

Instance 0x7f5e4c000d40 is running

get_next_inst 0x7f5e4c000d40

cpaCyRsaDecrypt  instance=0x7f5e4c000d40

[error] Sal_ServiceIsRunning() - :  Instance not in a Running state 0x4c         000d40 state 1

[error] Sal_ServiceIsRunning() - : 0x4c000d40 ......

 

[error] cpaCyRsaDecrypt() - : Instance not in a Running state

[qat_rsa_decrypt] --- cpaCyRsaDecrypt failed, sts=-1. instance=0x7f5e4c0         00d40

[qat_rsa_priv_enc] --- cpaCyRsaDecrypt failed!

0 : open 0 closed 0 del 0

1 : open 1 closed 0 del 0

Opened 1 closed 0 freeed 0 errors 0 ssl errors 0 epoll add 1 epoll del          1 qat_epoll 1  del 0

0 : open 0 closed 0 del 0

1 : open 1 closed 0 del 0

Opened 1 closed 0 freeed 0 errors 0 ssl errors 0 epoll add 1 epoll del          1 qat_epoll 1  del 0

^C

root@ubuntu-hu3:/home/tseng/epoll-engine#

**Comment by stevelinsell** [comment]
Hi Tseng,

I notice you are using both SET_INSTANCE_FOR_THREAD and ENABLE_POLLING (or I think you are, correct me if I'm wrong).
We are wondering if there is some interaction between the two going on that is causing your issue.
Is there any chance you can disable the SET_INSTANCE_FOR_THREAD calls for now and see if your problem goes away?

Steve.

**Comment by tsenghu** [comment]
Indeed, that is the case.

I will disable it.

Thanks

 

Tseng

 

 

From: tseng hu [mailto:tseng@netskope.com] 
Sent: Wednesday, October 05, 2016 9:33 AM
To: '01org/QAT_Engine'; '01org/QAT_Engine'
Cc: 'Author'
Subject: RE: [01org/QAT_Engine] qat_engine in external polling (#8)

 

Sorry to bother you again.

Here is what happen after I use openssl.cnf

 

OPENSSL_INIT: ossl_init_base: Setting up stop handlers

OPENSSL_INIT: ossl_init_config: openssl_config(NULL)

OPENSSL_INIT: ossl_init_engine_rdrand: engine_load_rdrand_int()

OPENSSL_INIT: ossl_init_load_crypto_strings: err_load_crypto_strings_int         ()

OPENSSL_INIT: ossl_init_thread_start: marking thread for err_state

OPENSSL_INIT: ossl_init_engine_dynamic: engine_load_dynamic_int()

CONF_modules_load_file ...(null) (null)

CONF_get1_default_config_file /etc/ssl/openssl.cnf

CONF_modules_load_file .../etc/ssl/openssl.cnf

vsection openssl_init

vsection openssl_init values ...12f99e0

name engines value 12fa080

module_run name engines md 0x12e7170

module_run ........

Called engine module: name engines, value engine_section

int_engine_module_init   name qat val qat_section

Configuring engine qat

ENGINE conf: doing ctrl(engine_id,qat)

ENGINE conf: doing ctrl(dynamic_path,/usr/local/openssl-1.1.0/lib/engine         s-1.1/qat.so)

[bind_qat] id=(null)

bind_qat: About to set mem functions

ENGINE conf: doing ctrl(ENABLE_EVENT_DRIVEN_MODE,EMPTY)

name ENABLE_EVENT_DRIVEN_MODE ctrlvalue EMPTY

EVENT POLL enabled 1

ENGINE conf: doing ctrl(ENABLE_POLLING,EMPTY)

name ENABLE_POLLING ctrlvalue EMPTY

POLL enabled 1

ENGINE conf: doing ctrl(default_algorithms,ALL)

name default_algorithms ctrlvalue ALL

[qat_engine_init] ---- Engine Initing

 

enable_external_polling 1 inited 0

looking for dir icp_dh895xcc_dev0

looking in /etc/dh895xcc_qa_dev0.conf

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit 0x4c000a30 0

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit pCryptoService 0x4c0         00a30

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit 0x4c000d40 0

[error] SalCtrl_CryptoInit() - : SalCtrl_CryptoInit pCryptoService 0x4c0         00d40

qat_engine_init: 2 Cy instances got

set address  0 0x7f5e4c000a30

start instance  0 0x7f5e4c000a30

Instance 0: 0x7f5e4c000a30 is running

set address  1 0x7f5e4c000d40

start instance  1 0x7f5e4c000d40

Instance 1: 0x7f5e4c000d40 is running

OPENSSL_INIT: ossl_init_add_all_ciphers: openssl_add_all_ciphers_int()

OPENSSL_INIT: ossl_init_add_all_digests: openssl_add_all_digests()

port 8000 mode 1

num of instances 2

number of instances 2  numinstances 2  cache enabled

OPENSSL_INIT: ossl_init_async: async_init()

POLL FD get 10 handle 0x7f5e4c000a30

ns_qat_epoll_create fd 10 efd 9 epoll 0x7f5e43fff2d8

0 cpu bind to 2 size 0

use_fd 0 sd =11 efd=9

set instance for thread 0 0x7f5e4c000a30

SET INSTANCE for thread 0

POLL FD get 13 handle 0x7f5e4c000d40

ns_qat_epoll_create fd 13 efd 12 epoll 0x7f5e47fff470

1 cpu bind to 3 size 0

use_fd 0 sd =14 efd=12

set instance for thread 1 0x7f5e4c000d40

SET INSTANCE for thread 1

0 : open 0 closed 0 del 0

1 : open 0 closed 0 del 0

Opened 0 closed 0 freeed 0 errors 0 ssl errors 0 epoll add 0 epoll del          0 qat_epoll 0  del 0

OPENSSL_INIT: ossl_init_thread_start: marking thread for async

OPENSSL_INIT: ossl_init_thread_start: marking thread for err_state

qat_ecdh_compute_key been called

qat_setup_async_event_notification create_fd 17

[qat_engine_init] ---- Engine Initing

 

enable_external_polling 1 inited 1

Instance 0x7f5e4c000a30 is running

get_next_inst 0x7f5e4c000a30

cpaCyEcPointMultiply 0x7f5e4c000a30

qat_pause_job job=0x7f5e50002710

ns_qat_epoll chann 0...

poll_one num 0 0x7f5e4c000a30 0x7f5e4c000a30

e_qat.qat_crypto_callbackFn: opDone->job 0x7f5e50002710

qat_wake_job ....

qat_wake_job write  fd=17 stat=8

qat_pause_job pause resume job=0x7f5e50002710

qat_pause_job waitctx = 0x7f5e500021e0

qat_pause_job get_fd 17

qat_pause_job return from read 17 stat 8

[qat_rsa_priv_enc] --- called.

[build_decrypt_op_buf] --- flen =36, padding = 1

qat_setup_async_event_notification get_fd 17

[qat_engine_init] ---- Engine Initing

 

enable_external_polling 1 inited 1

[error] Sal_ServiceIsRunning() - :  Instance not in a Running state 0x4c         000d40 state 1

[error] Sal_ServiceIsRunning() - : 0x4c000d40 ......

 

Instance 0x7f5e4c000d40 is running

get_next_inst 0x7f5e4c000d40

cpaCyRsaDecrypt  instance=0x7f5e4c000d40

[error] Sal_ServiceIsRunning() - :  Instance not in a Running state 0x4c         000d40 state 1

[error] Sal_ServiceIsRunning() - : 0x4c000d40 ......

 

[error] cpaCyRsaDecrypt() - : Instance not in a Running state

[qat_rsa_decrypt] --- cpaCyRsaDecrypt failed, sts=-1. instance=0x7f5e4c0         00d40

[qat_rsa_priv_enc] --- cpaCyRsaDecrypt failed!

0 : open 0 closed 0 del 0

1 : open 1 closed 0 del 0

Opened 1 closed 0 freeed 0 errors 0 ssl errors 0 epoll add 1 epoll del          1 qat_epoll 1  del 0

0 : open 0 closed 0 del 0

1 : open 1 closed 0 del 0

Opened 1 closed 0 freeed 0 errors 0 ssl errors 0 epoll add 1 epoll del          1 qat_epoll 1  del 0

^C

root@ubuntu-hu3:/home/tseng/epoll-engine#

**Comment by tsenghu** [comment]
Hi steve:

 

Epoll_wait with timeout value of 1000 millisecond is long.

Is there any reason for that ?

 

Please advice

 

Thanks

 

Tseng

**Comment by agrandi** [comment]
Hi Tseng,

we use a value of 1000ms as the timeout of epoll_wait() to reduce the CPU usage and at the same time not have a synchronous call.

When an event is sent from the crypto instance, `epoll_wait()` will resume immediately without actually waiting for the 1000ms to pass.
The function will return if after 1000ms no event has occurred so that we have a chance to check the flag `keep_polling` and potentially terminate the polling thread if the engine is finishing.

If you reduce the timeout to a very small value and the engine is not actually processing any crypto operation you will see that the CPU consumption of the polling thread won't be entirely negligible.

However, this should not have an impact on the max performance when the application is heavily loaded.

Hope this helps.

**Comment by tsenghu** [comment]
Thanks,

 

Tseng

**Comment by tsenghu** [comment]
I am sorry to bother you. I need some advice from you.

 

We have decided to upgrade to Ubuntu 16.04/linux kernel 4.4.0-57-generic.

After linux is up, I see two drivers that is related to QAT. 

One is qat_dh895xcc and another one is intel_qat. 

After I inserted two drivers (icp_qa_al.ko and qat_contig_mem.ko) and try to run “service qat_service start”.

It failed to start.

 

What do I need to do/change?

Please advice

 

Tseng

**Comment by stevelinsell** [comment]
Hi Tseng,

I've moved your question into it's own issue as I think it maybe relevant to others.
Please find it located here #14 

Steve.

**Comment by tsenghu** [comment]
Thanks

 

Tseng
