### ISSUE TITLE
Make for QAT engine not working on latest Linux/Ubuntu

### ISSUE THREAD

**Issue by athyagat** [intel/QAT_Engine#83]
Hi,

The make command produces following error, 

/qat_rsa_crt.o .libs/qat_ciphers.o .libs/qat_dh.o .libs/qat_dsa.o .libs/qat_ec.o .libs/qat_prf.o .libs/qat_parseconf.o .libs/qae_mem_utils.o .libs/e_qat_err.o   -L/home/athyagat/workdir/qat_linux_driver/build -licp_qa_al_s  -g -O2 -Wl,-rpath -Wl,/home/athyagat/workdir/qat_linux_driver/build   -Wl,-soname -Wl,libqat.so.0 -o .libs/libqat.so.0.0.0
**/usr/bin/x86_64-linux-gnu-ld: cannot find -licp_qa_al_s**
collect2: error: ld returned 1 exit status
Makefile:603: recipe for target 'libqat.la' failed
make[1]: *** [libqat.la] Error 1
make[1]: Leaving directory '/home/athyagat/workdir/openssl/engines/QAT_Engine'
Makefile:514: recipe for target 'all' failed
make: *** [all] Error 2

/* Linux version */

root@ubuntu2:/home/athyagat/workdir/qat_linux_driver# uname -a
Linux ubuntu2 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/* Configure output */

root@ubuntu2:/home/athyagat/workdir/qat_linux_driver# ./configure --with-qat_dir=/home/athyagat/workdir/qat_linux_driver --with-openssl_dir=/home/athyagat/workdir/openssl --with-openssl_install_dir=/usr/local/ssl
configure: WARNING: unrecognized options: --with-qat_dir, --with-openssl_dir, --with-openssl_install_dir
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gawk... (cached) gawk
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... none
checking for cc... cc
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking whether cc understands -c and -o together... yes
checking dependency style of cc... none
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for C compiler vendor... gnu
checking for a sed that does not truncate output... /bin/sed
checking for C compiler version... 7.3.0
checking for C++ compiler vendor... gnu
checking for C++ compiler version... 7.3.0
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking libudev.h usability... yes
checking libudev.h presence... yes
checking for libudev.h... yes
checking for libudev... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking utmpx.h usability... yes
checking utmpx.h presence... yes
checking for utmpx.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for pid_t... yes
checking for C/C++ restrict keyword... __restrict
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking for alarm... yes
checking for getpagesize... (cached) yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for munmap... yes
checking for rmdir... yes
checking for select... yes
checking for strerror... yes
checking for strtol... yes
checking for strtoul... yes
checking for strtoull... yes
checking for kernel sources... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
configure: WARNING: unrecognized options: --with-qat_dir, --with-openssl_dir, --with-openssl_install_dir

root@ubuntu2:/home/athyagat/workdir/qat_linux_driver#

**Comment by stevelinsell** [comment]
Hi @athyagat,

At a guess I would say the issue is likely to be because you are running the QAT 1.7 Driver (also referred to as upstream driver), but have not specified the --enable-upstream_driver flag as part of the ./configure.
Please see the https://github.com/intel/QAT_Engine#build-the-intel-quickassist-technology-openssl-engine section of the README.md file.
An example of the ./configure you would use when using the QAT 1.7 Upstream Driver is:

```
cd /QAT_Engine
./configure \
--with-qat_dir=/QAT \
--with-openssl_dir=/openssl \
--with-openssl_install_dir=/usr/local/ssl \
--enable-upstream_driver \
--enable-usdm
make
make install
```

Let me know if that is your issue,

Steve.

**Comment by athyagat** [comment]
The issue is resolved after passing the "--enable-upstream_driver" parameter.

./configure --with-qat_dir=/home/athyagat/workdir/qat_linux_driver/ --with-openssl_dir=/home/athyagat/workdir/openssl/ --with-openssl_install_dir=/usr/local/ssl/ --enable-upstream_driver
