### ISSUE TITLE
QAT VF multi process failed

### ISSUE THREAD

**Issue by fansongsen** [intel/QAT_Engine#85]
hello, I split the qat PF to 16 VF,when I start the first process with QAT Engine,it works well. but when I start the second process, it failed:
icp_adf_userProcessToStart function, and res = write(process_info_file, name_tml, name_len) failed with res=1
can someone please tell me how to do with this problem.

**Comment by stevelinsell** [comment]
Hi @fansongsen,

I need a little more info to try and help you.
1) Which QAT Product are you using?
2) Which QAT Driver are you using, i.e QAT 1.7.L.4.2.0-00012?
3) Which OS are you using?
4)  Are you following the virtualization guide here: [Using Intel® Virtualization Technology (Intel® VT) with Intel® QuickAssist Technology Application Note](https://01.org/sites/default/files/downloads/intelr-quickassist-technology/330689qatvirtualizationappnoter006usreview.pdf)?
5) Are you running with SR-IOV?
6) Are you trying to use acceleration on the guest or host?

Kind Regards,

Steve.

**Comment by fansongsen** [comment]
Hi @stevelinsell 
1.The qat chip I use is c62X series on soc，it has 2 PF，every PF split 16 VF，so it has 32 VF. 14 VF was bind to dpdk. the other 18 VF I want to use for QAT Engine. All the VF was on the host that was a debian system.
2. The qat dirver I use is qat1.7.l.4.1.0-00022，the QAT Engine is QAT_Engine-0.5.35.
3. The OS is debian
4.I follow the virtualization guide you support.
5.I use the SR-IOV
6.All acceleration  was on the host

**Comment by stevelinsell** [comment]
Hi @fansongsen, 

Can you paste the contents of one of the driver config files you use for the PF's and one of the config files for the VF's you are using for QAT Engine. Have you got different driver config files for the VF's you are using for DPDK compared to the VF's you are using for QAT?

Kind Regards,

Steve.

**Comment by fansongsen** [comment]
Hi @stevelinsell ,
The PF's config file is:
[GENERAL]
ServicesEnabled = cy

ConfigVersion = 2

#Default values for number of concurrent requests*/
CyNumConcurrentSymRequests = 512
CyNumConcurrentAsymRequests = 64

#Statistics, valid values: 1,0
statsGeneral = 1
statsDh = 1
statsDrbg = 1
statsDsa = 1
statsEcc = 1
statsKeyGen = 1
statsDc = 1
statsLn = 1
statsPrime = 1
statsRsa = 1
statsSym = 1
KptEnabled = 0

# This flag is to enable SSF features (CNV and BnP)
StorageEnabled = 0

# Disable public key crypto and prime number
# services by specifying a value of 1 (default is 0)
PkeServiceDisabled = 0

# Specify size of intermediate buffers for which to
# allocate on-chip buffers. Legal values are 32 and
# 64 (default is 64). Specify 32 to optimize for
# compressing buffers <=32KB in size.
DcIntermediateBufferSizeInKB = 64

##############################################
# Kernel Instances Section
##############################################
[KERNEL]
NumberCyInstances = 0
NumberDcInstances = 0

##############################################
# User Process Instance Section
##############################################
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 4
LimitDevAccess = 0

# Crypto - User instance #0
Cy0Name = "UserCY0"
Cy0IsPolled = 2
# List of core affinities
Cy0CoreAffinity = 0


The PF's config file is:
[GENERAL]
ServicesEnabled = cy

ConfigVersion = 2

#Default values for number of concurrent requests*/
CyNumConcurrentSymRequests = 512
CyNumConcurrentAsymRequests = 64

#Statistics, valid values: 1,0
statsGeneral = 1
statsDh = 1
statsDrbg = 1
statsDsa = 1
statsEcc = 1
statsKeyGen = 1
statsDc = 1
statsLn = 1
statsPrime = 1
statsRsa = 1
statsSym = 1

##############################################
# Kernel Instances Section
##############################################
[KERNEL]
NumberCyInstances = 0
NumberDcInstances = 0

##############################################
# User Process Instance Section
##############################################
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 1
LimitDevAccess = 0

# Crypto - User instance #0
Cy0Name = "UserCY0"
Cy0IsPolled = 2
# List of core affinities
Cy0CoreAffinity = 0

**Comment by fansongsen** [comment]
Hi @stevelinsell ,
I had try set the VF's config file NumProcesses=2 or more, The VF will failed to init.

**Comment by mythi** [comment]
Same as #70?
