### ISSUE TITLE
QAT Engine tested with latest openssl and tls1.3?

### ISSUE THREAD

**Issue by felix94536** [intel/QAT_Engine#87]
Hi, Is QAT Engine tested with openssl 1.1.1 and tls1.3? Thanks.

**Comment by stevelinsell** [comment]
Hi @felix94536, 

We expect OpenSSL to make the official OpenSSL 1.1.1 release tomorrow (11th Sep 18) unless something unexpected crops up as they froze their repo to all commits on Sunday.
At that point we will begin testing against OpenSSL 1.1.1. We'll begin with testing TLS 1.2 for regression and move onto TLS 1.3 to test RSA-PSS and elliptical curves for handshaking. I expect there to be a few weeks lead time before we make a new QAT Engine release confirming things are working correctly. As part of the engine release we will be moving our default QAT Engine build to be against the OpenSSL 1.1.1 baseline (as it is the LTS baseline) and an additional configure option will be required to continue building against OpenSSL 1.1.0.

Kind Regards,

Steve.

**Comment by felix94536** [comment]
Sounds great. I will check back after a few weeks. Thanks, Steve!
